import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

async function loadWorker(){const url=new URL("../dist/server/index.js",import.meta.url);url.searchParams.set("context-test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(url.href)).default;}
const runtime={waitUntil(){},passThroughOnException(){}};
const lines=["Siempre pensé que poner un protector de pantalla era cuestión de suerte.","O quedaba una burbuja, entraba polvo o terminaba completamente torcido.","Pero mira esto. Coloco el teléfono aquí, presiono y simplemente deslizo.","Mientras lo hago, el sistema ayuda a retirar el polvo y al mismo tiempo coloca el protector automáticamente.","En unos 10 segundos ya está instalado. Mira la pantalla de cerca: sin polvo, sin burbujas y perfectamente alineada.","De frente puedes ver la pantalla normalmente, pero cuando la miras desde un lado, la protección de privacidad de 28 grados hace que sea mucho más difícil ver el contenido.","Además, mira cómo resbalan las gotas sobre la superficie.","Si eres de los que siempre termina peleándose con el protector de pantalla, esto te hace la instalación muchísimo más fácil."];
const script={title:"Instalación sin suerte",product:"变形金刚钢化膜",language:"西班牙语",country:"西班牙",style:"KOC / UGC",creativeAngle:"Instalación automática demostrada paso a paso",hookType:"好奇",framework:"PAS",hook:lines[0],alternateHooks:[],narration:lines.join(" "),conflict:lines[1],productReveal:lines[2],proof:lines.slice(3,7).join(" "),sellingPoints:"10秒自动除尘安装；无尘无气泡；28°防窥；疏水表面",cta:lines[7],scenes:lines.map((line,index)=>({time:`${index*4}-${Math.min(30,(index+1)*4)}`,visual:index<2?"Primer plano del fallo de instalación":index<5?"Proceso continuo de colocar, presionar y deslizar":index===5?"Comparación frontal y lateral de la misma pantalla":index===6?"Gotas deslizándose sobre la superficie":"Producto y teléfono en el mismo escritorio",line,edit:index===0?"Hard cut":"Jump cut"}))};
const context={product:"变形金刚钢化膜",sellingPoints:script.sellingPoints,audience:"Personas que fallan al instalar protectores",market:"Spain",language:"西班牙语",platform:"TikTok",targetDuration:30,creativeMode:"KOC / UGC",hookStrategy:"好奇",framework:"PAS",creativeAngle:script.creativeAngle,productKnowledge:{name:"变形金刚钢化膜",sellingPoints:script.sellingPoints,parameters:"10秒安装；左右28°防窥",notes:"自动除尘安装；疏水表面"},sourceType:"script-studio"};
async function call(payload){delete process.env.DEEPSEEK_API_KEY;const worker=await loadWorker();const response=await worker.fetch(new Request("http://localhost/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),{},runtime);return{response,data:await response.json()};}

test("A real Spanish screen-protector script stays isolated and grounded",async()=>{const {response,data}=await call({script,context,settings:{provider:"deepseek"}});assert.equal(response.status,200);assert.equal(data.metadata.contextIntegrity.status,"Complete");const surface=JSON.stringify({plan:data.directorPlan,shots:data.shots}).toLowerCase();for(const stale of ["cinta adhesiva","malla","pesa","peso colgante"])assert.equal(surface.includes(stale),false,stale);for(const grounded of ["安装","灰尘","气泡","28","水滴"])assert.equal(surface.includes(grounded),true,grounded);});
test("B at least five shots trace to current Structured Script blocks",async()=>{const {data}=await call({script,context,settings:{provider:"deepseek"}}),ids=new Set(script.scenes.map((_,index)=>`scene-${index+1}`));assert.ok(data.shots.length>=5);for(const shot of data.shots.slice(0,5))assert.ok(ids.has(shot.sourceBlockId),`${shot.shotId}:${shot.sourceBlockId}`);});
test("Phase 5.6B Director context binds project and stable script revision",async()=>{const first=await call({projectId:"project-a",scriptRevisionId:"revision-a",script,context,settings:{provider:"deepseek"}}),second=await call({projectId:"project-a",scriptRevisionId:"revision-b",script,context,settings:{provider:"deepseek"}});assert.equal(first.data.metadata.sourceScriptRevisionId,"revision-a");assert.equal(second.data.metadata.sourceScriptRevisionId,"revision-b");assert.notEqual(first.data.metadata.contextId,second.data.metadata.contextId);});
test("D/E context switch changes identity and stale regenerate is rejected",async()=>{const first=await call({script,context,settings:{provider:"deepseek"}}),scriptB={...script,title:"Otro producto",product:"另一个产品",hook:"Un guion completamente diferente",scenes:[{time:"0-3",visual:"Nuevo contexto",line:"Un guion completamente diferente",edit:"Cut"},...script.scenes.slice(1)]},contextB={...context,product:"另一个产品",sellingPoints:"卖点B",productKnowledge:{name:"另一个产品",sellingPoints:"卖点B"}};const second=await call({script:scriptB,context:contextB,settings:{provider:"deepseek"}});assert.notEqual(first.data.metadata.contextId,second.data.metadata.contextId);const currentShot=first.data.shots[0],rejected=await call({script:scriptB,context:contextB,contextId:first.data.metadata.contextId,settings:{provider:"deepseek"},action:"regenerate-shot",directorPlan:first.data.directorPlan,currentShot,sourceBlock:{id:currentShot.sourceBlockId,stage:currentShot.stage,text:scriptB.scenes[0].line}});assert.equal(rejected.response.status,409);assert.equal(rejected.data.contextIntegrity.status,"Needs Attention");});
test("F/G/H workspace exposes context gate, compact cards, useful inspector and timeline states",async()=>{const [ui,route,page]=await Promise.all([readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/director/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/page.tsx",import.meta.url),"utf8")]);for(const marker of ["检测到当前脚本已变化","为当前脚本生成新导演方案","返回旧导演方案（只读）","选择一个镜头进行编辑","导演备注","摄影 / 道具 / 剪辑 / 连贯性","needs-attention","AI 重新生成","复制镜头","状态"])assert.ok(ui.includes(marker),marker);assert.ok(route.includes("safeGenerationContext"));assert.ok(route.includes("currentStructuredScript"));const payload=page.slice(page.indexOf("const directorInput"),page.indexOf("return ("));assert.equal(payload.includes("referenceScript:"),false);});
