import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import ts from "typescript";

async function workspace(){const source=await readFile(new URL("../app/director-workspace.ts",import.meta.url),"utf8");const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`);}
const shot=(order,stage="BODY",duration=4)=>({shotId:`shot-${order}`,order,startTime:(order-1)*duration,endTime:order*duration,duration,sourceBlockId:`scene-${order}`,stage,purpose:stage==="HOOK"?"Attention":stage==="CTA"?"Close / Action":"Narrative",shotType:"Action Shot",framing:"Medium",cameraAngle:"Eye Level",cameraMovement:"Static",visualDescription:`visual ${order}`,subject:"product",productAction:"action",talentAction:"talent",props:["phone"],environment:"desk",dialogue:"",voiceover:"",onScreenText:"",proofRequirement:stage==="PROOF"?"proof":"",transition:"Hard Cut",editingNotes:"cut",audioSfx:"sound",continuityNotes:"same phone",priority:stage==="PROOF"||stage==="HOOK"?"Critical":"Normal",locked:false,status:"Draft"});

test("A manual edit timeline update changes only the selected shot",async()=>{const {recalculateTimeline}=await workspace();const before=[shot(1,"HOOK",3),shot(2,"BODY",4),shot(3,"PROOF",5)];const next=recalculateTimeline(before.map((item,index)=>index===1?{...item,visualDescription:"edited",framing:"Close-Up",duration:6}:item));assert.equal(next[0].visualDescription,before[0].visualDescription);assert.equal(next[1].visualDescription,"edited");assert.equal(next[2].visualDescription,before[2].visualDescription);assert.equal(next[2].startTime,9);});
test("B rewrite UI preserves Before / After and accept-reject flow",async()=>{const ui=await readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8");for(const marker of ["BEFORE","AFTER","Reject","Accept","setUndo","Fact Guard"])assert.ok(ui.includes(marker),marker);});
test("C locked shots are excluded from unlocked rebuild and duration changes",async()=>{const {autoRebalance}=await workspace();const shots=[{...shot(1,"HOOK",3),locked:true},{...shot(2,"PROOF",8),locked:true},shot(3,"BODY",10),shot(4,"CTA",4)];const result=autoRebalance(shots,20);assert.deepEqual(result.shots.slice(0,2).map(x=>x.duration),[3,8]);assert.equal(result.afterPlanned,20);const ui=await readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8");assert.match(ui,/shot\.locked\?-1:index/);});
test("D duplicate delete and insert recalculate IDs, order and time",async()=>{const {duplicateShot,deleteShot,insertShot}=await workspace();let shots=[shot(1,"HOOK",3),shot(2,"PROOF",5),shot(3,"CTA",2)];shots=duplicateShot(shots,0);assert.equal(new Set(shots.map(x=>x.shotId)).size,4);shots=deleteShot(shots,2);shots=insertShot(shots,1,{...shot(8,"BODY",1),shotId:"temp"});assert.deepEqual(shots.map(x=>x.order),[1,2,3,4]);assert.equal(shots.every((x,i)=>i===0||x.startTime===shots[i-1].endTime),true);});
test("E reorder preserves source IDs and durations but emits continuity warning",async()=>{const {reorderShots,checkDirectorIntegrity}=await workspace();const before=[shot(1,"HOOK",3),shot(2,"BODY",4),shot(3,"PROOF",5),shot(4,"CTA",2)];const next=reorderShots(before,2,1);assert.deepEqual(next.map(x=>x.duration),[3,5,4,2]);assert.deepEqual(next.map(x=>x.sourceBlockId),["scene-1","scene-3","scene-2","scene-4"]);assert.ok(checkDirectorIntegrity(next,14,"proof").issues.some(x=>x.code==="continuity_warning"));});
test("F auto rebalance protects locked, Hook and Proof minimums",async()=>{const {autoRebalance}=await workspace();const input=[{...shot(1,"HOOK",4),locked:true},shot(2,"BODY",9),shot(3,"PROOF",8),shot(4,"CTA",4)];const result=autoRebalance(input,18);assert.equal(result.shots[0].duration,4);assert.ok(result.shots[2].duration>=3);assert.ok(result.shots[3].duration>=1.2);assert.equal(result.delta,0);});
test("G integrity detects missing Proof",async()=>{const {checkDirectorIntegrity}=await workspace();const result=checkDirectorIntegrity([shot(1,"HOOK",3),shot(2,"PRODUCT REVEAL",5),shot(3,"CTA",2)],10,"10秒自动安装；防窥");assert.equal(result.status,"Needs Attention");assert.ok(result.issues.some(x=>x.code==="proof_missing"));});
test("H versions are immutable and confirmed edits return to Draft",async()=>{const {createDirectorVersion}=await workspace();const plan={creativeIntent:"intent"},shots=[shot(1,"HOOK",3)];const version=createDirectorVersion([],plan,shots,"Confirmed");shots[0].visualDescription="changed";assert.equal(version.label,"Director V1");assert.equal(version.status,"Confirmed");assert.notEqual(version.shots[0].visualDescription,shots[0].visualDescription);const ui=await readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8");assert.match(ui,/setListStatus\("Draft"\)/);});
test("I Director workspace keeps Studio, Replication, Knowledge and Provider integrations",async()=>{const files=await Promise.all(["page.tsx","script-studio.tsx","viral-replication.tsx","knowledge-context.ts","provider-router.ts","api/director/route.ts"].map(file=>readFile(new URL(`../app/${file}`,import.meta.url),"utf8")));const all=files.join("\n");for(const marker of ["进入 AI 导演","采用并进入 AI Director","buildKnowledgeContext","callProvider","regenerate-shot","suggest-shot","validateScriptLanguage","directorFactViolations"])assert.ok(all.includes(marker),marker);});
