import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

async function loadWorker(){const url=new URL("../dist/server/index.js",import.meta.url);url.searchParams.set("intelligence-test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(url.href)).default;}
const runtime={waitUntil(){},passThroughOnException(){}};
const script={title:"安装失败反转",product:"变形金刚钢化膜",language:"西班牙语",country:"西班牙",style:"KOC / UGC",creativeAngle:"自动安装过程证明",hookType:"好奇",framework:"PAS",hook:"¿Por qué siempre queda una burbuja?",alternateHooks:[],narration:"",conflict:"Siempre queda polvo.",productReveal:"Uso el aplicador.",proof:"Instalación visible en 10 segundos y privacidad de 28°.",sellingPoints:"10秒自动除尘安装；无尘无气泡；28°防窥",cta:"Comprueba tu modelo.",scenes:[{time:"0-3",visual:"Macro de una burbuja",line:"¿Por qué siempre queda una burbuja?",edit:"Hard cut"},{time:"3-10",visual:"Colocar, presionar y deslizar",line:"Mira cómo lo instalo.",edit:"Jump cut"},{time:"10-14",visual:"Resultado de cerca",line:"Comprueba el resultado.",edit:"Clean cut"}]};
const context={product:"变形金刚钢化膜",sellingPoints:script.sellingPoints,audience:"贴膜容易失败且在意隐私的用户",market:"西班牙",language:"西班牙语",platform:"TikTok",targetDuration:15,creativeMode:"KOC / UGC",hookStrategy:"好奇",framework:"PAS",creativeAngle:script.creativeAngle,productKnowledge:{name:"变形金刚钢化膜",sellingPoints:script.sellingPoints,parameters:"10秒安装；左右28°防窥",bannedWords:"100%防爆；永不碎"},sourceType:"script-studio"};
const plan={recommendationType:"Director Recommendation",creativeIntent:"用真实安装过程建立信任",visualStyle:"KOC手持与产品微距",hookExecution:"局部失败状态建立缺口",pacingStrategy:"短镜头推进",proofStrategy:"连续记录安装前后",productRevealStrategy:"问题后展示产品",ctaExecution:"自然提示确认型号",shootingComplexity:"Simple",requiredTalent:["同一位KOC模特"],requiredProps:["手机","变形金刚钢化膜"],requiredLocations:["整洁桌面"]};
const shot=(order,stage,sourceBlockId)=>({shotId:`shot-${String(order).padStart(2,"0")}`,order,startTime:(order-1)*4,endTime:order*4,duration:4,sourceBlockId,stage,purpose:stage==="HOOK"?"Attention":stage==="PROOF"?"Demonstration / Verification":"Close / Action",shotType:stage==="HOOK"?"Attention Shot":stage==="PROOF"?"Proof Shot":"CTA Shot",framing:stage==="PROOF"?"Product Macro":"Close-Up",cameraAngle:"Eye Level",cameraMovement:stage==="HOOK"?"Push In":"Static",visualDescription:stage==="HOOK"?"微距展示一处气泡并保留答案缺口":stage==="PROOF"?"连续拍摄放置、按压、滑动与结果":"产品和手机同框",subject:"产品与操作手部",productAction:stage==="PROOF"?"完整执行安装动作":"产品自然入镜",talentAction:"手部执行清晰动作",props:["手机","变形金刚钢化膜"],environment:"整洁桌面",dialogue:"",voiceover:"",onScreenText:"",proofRequirement:stage==="PROOF"?"连续记录10秒安装过程":"",transition:"Hard Cut",editingNotes:"动作完成点剪切",audioSfx:"保留真实操作声",continuityNotes:"同一手机与光线",priority:stage==="CTA"?"High":"Critical"});
const shots=[shot(1,"HOOK","scene-1"),shot(2,"PROOF","scene-2"),shot(3,"CTA","scene-3")];
const responseFor=(items=shots)=>JSON.stringify({evaluations:items.map((item,index)=>({shotId:item.shotId,scores:{hookStrength:index===0?101:72,visualImpact:84,productProof:index===1?93:70,conversionPotential:index===2?89:-2},suggestion:{missing:"补足当前镜头承担的信息",visualUpgrade:"让关键动作和结果在同一机位中清晰可见",conversionUpgrade:"让当前卖点与用户问题形成直接对应"}}))});

async function post(worker,body){const response=await worker.fetch(new Request("http://localhost/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),{},runtime);return{response,data:await response.json()};}
async function generate(worker){delete process.env.DEEPSEEK_API_KEY;const result=await post(worker,{script,context,settings:{provider:"deepseek"}});assert.equal(result.response.status,200);return result.data;}

test("Step 6.4-A A-D: API batch normalizes scores and fingerprint cache tracks shot context",async()=>{const worker=await loadWorker(),director=await generate(worker),batch=director.shots.slice(0,3),payload={script,context,action:"evaluate-shots",contextId:director.metadata.contextId,directorPlan:director.directorPlan,shots:batch,settings:{provider:"deepseek"}};process.env.DIRECTOR_INTELLIGENCE_TEST_MODE="1";process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE=responseFor(batch);try{const first=await post(worker,payload);assert.equal(first.response.status,200);assert.equal(first.data.evaluations.length,3);assert.equal(first.data.evaluations[0].scores.hookStrength,100);assert.equal(first.data.evaluations[1].scores.conversionPotential,0);assert.equal(first.data.metadata.cacheHits,0);assert.equal(first.data.metadata.cacheMisses,3);delete process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE;const second=await post(worker,payload);assert.equal(second.response.status,200);assert.equal(second.data.metadata.providerUsed,"cache");assert.equal(second.data.metadata.cacheHits,3);assert.equal(second.data.metadata.cacheMisses,0);const changed=batch.map((item,index)=>index===1?{...item,visualDescription:`${item.visualDescription}；保持更近景别`}:item);process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE=responseFor(changed);const invalidated=await post(worker,{...payload,shots:changed});assert.equal(invalidated.response.status,200);assert.equal(invalidated.data.metadata.cacheMisses,3);assert.notEqual(invalidated.data.evaluations[1].fingerprint,first.data.evaluations[1].fingerprint);}finally{delete process.env.DIRECTOR_INTELLIGENCE_TEST_MODE;delete process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE;}});

test("Step 6.4-A E: stale context and mismatched batch IDs are rejected",async()=>{const worker=await loadWorker(),director=await generate(worker),batch=director.shots.slice(0,3),payload={script,context,action:"evaluate-shots",contextId:director.metadata.contextId,directorPlan:director.directorPlan,shots:batch,settings:{provider:"deepseek"},force:true};const stale=await post(worker,{...payload,contextId:"director-stale"});assert.equal(stale.response.status,409);process.env.DIRECTOR_INTELLIGENCE_TEST_MODE="1";process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE=responseFor(batch.slice(0,2));try{const mismatch=await post(worker,payload);assert.equal(mismatch.response.status,422);assert.equal(mismatch.data.category,"schema_validation_error");}finally{delete process.env.DIRECTOR_INTELLIGENCE_TEST_MODE;delete process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE;}});

test("Step 6.4-A F: unsupported facts in suggestions are blocked",async()=>{const worker=await loadWorker(),director=await generate(worker),batch=director.shots.slice(0,3),unsafe=JSON.parse(responseFor(batch));unsafe.evaluations[0].suggestion.conversionUpgrade="增加99%官方认证和限时赠品强化转化";process.env.DIRECTOR_INTELLIGENCE_TEST_MODE="1";process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE=JSON.stringify(unsafe);try{const result=await post(worker,{script,context,action:"evaluate-shots",contextId:director.metadata.contextId,directorPlan:director.directorPlan,shots:batch,settings:{provider:"deepseek"},force:true});assert.equal(result.response.status,422);assert.equal(result.data.category,"fact_validation_error");}finally{delete process.env.DIRECTOR_INTELLIGENCE_TEST_MODE;delete process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE;}});

test("Director Intelligence uses a bounded 90s timeout inside a 120s route window",async()=>{const [engineSource,routeSource]=await Promise.all([readFile(new URL("../app/director-intelligence.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/director/route.ts",import.meta.url),"utf8")]);assert.match(engineSource,/DIRECTOR_INTELLIGENCE_PROVIDER_TIMEOUT_MS=90_000/);assert.match(engineSource,/timeoutMs:DIRECTOR_INTELLIGENCE_PROVIDER_TIMEOUT_MS/);assert.match(routeSource,/export const maxDuration=120/);assert.ok(120_000>90_000);});

test("Director Intelligence provider timeout remains a structured 502",async()=>{const worker=await loadWorker(),director=await generate(worker),batch=director.shots.slice(0,1);process.env.DIRECTOR_INTELLIGENCE_TEST_MODE="1";process.env.DIRECTOR_INTELLIGENCE_TEST_ERROR="timeout";try{const result=await post(worker,{script,context,action:"evaluate-shots",contextId:director.metadata.contextId,directorPlan:director.directorPlan,shots:batch,settings:{provider:"deepseek"},force:true});assert.equal(result.response.status,502);assert.equal(result.data.category,"timeout");assert.equal(result.data.error,"Shot Intelligence 评分超时，请重试。");}finally{delete process.env.DIRECTOR_INTELLIGENCE_TEST_MODE;delete process.env.DIRECTOR_INTELLIGENCE_TEST_ERROR;}});

test("Director Intelligence single-shot retry evaluates only its target and accepts compact neighbors",async()=>{const worker=await loadWorker(),director=await generate(worker),target=director.shots[1],previousShot={stage:director.shots[0].stage,purpose:director.shots[0].purpose,visualDescription:director.shots[0].visualDescription},nextShot={stage:director.shots[2].stage,purpose:director.shots[2].purpose,visualDescription:director.shots[2].visualDescription};process.env.DIRECTOR_INTELLIGENCE_TEST_MODE="1";process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE=responseFor([target]);try{const result=await post(worker,{script,context,action:"evaluate-shots",contextId:director.metadata.contextId,directorPlan:director.directorPlan,shots:[target],previousShot,nextShot,settings:{provider:"deepseek"},force:true});assert.equal(result.response.status,200);assert.equal(result.data.evaluations.length,1);assert.equal(result.data.evaluations[0].shotId,target.shotId);assert.equal(result.data.metadata.batchSize,1);assert.equal(result.data.metadata.cacheMisses,1);}finally{delete process.env.DIRECTOR_INTELLIGENCE_TEST_MODE;delete process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE;}});

test("Director Intelligence clamps suggestion length without regressing parse or schema validation",async()=>{const worker=await loadWorker(),director=await generate(worker),target=director.shots[0],longSuggestion="让关键动作与结果保持清晰可见。".repeat(30),response=JSON.stringify({evaluations:[{shotId:target.shotId,scores:{hookStrength:80,visualImpact:81,productProof:82,conversionPotential:83},suggestions:{missing:longSuggestion,visualUpgrade:longSuggestion,conversionUpgrade:longSuggestion}}]});process.env.DIRECTOR_INTELLIGENCE_TEST_MODE="1";process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE=response;try{const result=await post(worker,{script,context,action:"evaluate-shots",contextId:director.metadata.contextId,directorPlan:director.directorPlan,shots:[target],settings:{provider:"deepseek"},force:true});assert.equal(result.response.status,200);for(const value of Object.values(result.data.evaluations[0].suggestion))assert.ok(value.length<=160);}finally{delete process.env.DIRECTOR_INTELLIGENCE_TEST_MODE;delete process.env.DIRECTOR_INTELLIGENCE_TEST_RESPONSE;}});

test("Director Intelligence low-latency path is isolated from Provider Router defaults and main generation",async()=>{const [engine,router,route,ui]=await Promise.all([readFile(new URL("../app/director-intelligence.ts",import.meta.url),"utf8"),readFile(new URL("../app/provider-router.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/director/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8")]);assert.match(engine,/thinking:"disabled"/);assert.match(engine,/shotIntelligenceMaxTokens\(misses\.length\)/);assert.match(engine,/targets:misses\.map\(compactShot\)/);assert.doesNotMatch(engine,/renderKnowledgeContext|startTime:shot\.startTime|endTime:shot\.endTime|dialogue:shot\.dialogue|voiceover:shot\.voiceover/);assert.match(router,/thinking\?:"enabled"\|"disabled"\|"auto"/);assert.match(router,/request\.thinking\?\{thinking:\{type:request\.thinking\}\}/);assert.doesNotMatch(route,/maxTokens:7500[^\n]*thinking/);assert.match(ui,/analyzeShots\(\[shots\[index\]\],force,/);assert.doesNotMatch(ui,/shots\.slice\(from,to\)/);});

test("Step 6.4-B Regression: UI integration preserves sealed schemas and image route",async()=>{const [engineSource,route,memory,ui,imageRoute,layout,styles]=await Promise.all([readFile(new URL("../app/director-intelligence.ts",import.meta.url),"utf8"),readFile(new URL("../app/api/director/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/project-memory.ts",import.meta.url),"utf8"),readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8"),readFile(new URL("../app/api/images/generate/route.ts",import.meta.url),"utf8"),readFile(new URL("../app/layout.tsx",import.meta.url),"utf8"),readFile(new URL("../app/styles/director-intelligence-ui.css",import.meta.url),"utf8")]);for(const marker of ["callProvider","evaluateShotIntelligenceBatch","shotIntelligenceFingerprint","ShotImprovementSuggestion","CACHE_TTL_MS","CACHE_MAX_ENTRIES","structuredClone"])assert.ok(engineSource.includes(marker),marker);assert.ok(route.includes('"evaluate-shots"'));assert.match(memory,/PROJECT_MEMORY_VERSION = 1/);for(const marker of ["evaluate-shots","shot-intelligence-rail","assistant-intelligence","重新分析当前镜头","生成 5 个创意方向","DirectorShotImage"])assert.ok(ui.includes(marker),marker);assert.ok(layout.includes("director-intelligence-ui.css"));assert.ok(styles.includes("Dark")&&styles.includes("shot-intelligence-rail"));assert.doesNotMatch(engineSource+route,/\/api\/images\/generate|ImageProviderRouter/);assert.ok(imageRoute.includes("routeImageGeneration"));});
