import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

async function loadWorker(){const url=new URL("../dist/server/index.js",import.meta.url);url.searchParams.set("director-test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(url.href)).default;}
const runtime={waitUntil(){},passThroughOnException(){}};
const script={title:"Instalación sin repetir",product:"变形金刚钢化膜",language:"西班牙语",country:"西班牙",style:"KOC / UGC",creativeAngle:"Una instalación que resuelve el fallo cotidiano",hookType:"好奇",framework:"PAS",hook:"¿Por qué este pequeño paso cambia todo?",alternateHooks:[],narration:"",conflict:"Polvo y burbujas",productReveal:"Aplicador automático",proof:"Instalación en 10 segundos, sin polvo ni burbujas, y privacidad de 28°",sellingPoints:"10秒自动除尘安装；无尘无气泡；28°防窥",cta:"Comprueba tu modelo.",scenes:[{time:"0-3",visual:"Macro de una burbuja sin revelar toda la herramienta",line:"¿Por qué este pequeño paso cambia todo?",edit:"Hard cut"},{time:"3-7",visual:"Mostrar polvo y una instalación fallida",line:"Siempre quedaba polvo o una burbuja.",edit:"Jump cut"},{time:"7-12",visual:"El aplicador entra en cuadro",line:"Ahora uso este aplicador.",edit:"Reveal"},{time:"12-21",visual:"Colocar, presionar y deslizar sin cortar",line:"Coloco el móvil, presiono y deslizo.",edit:"Proceso continuo"},{time:"21-26",visual:"Macro del resultado y cambio de ángulo",line:"Queda limpio y desde el lado cambia la visibilidad.",edit:"Before after"},{time:"26-30",visual:"Producto y modelo compatible",line:"Comprueba tu modelo.",edit:"Clean cut"}]};
const context={product:"变形金刚钢化膜",sellingPoints:"10秒自动除尘安装；无尘无气泡；28°防窥",audience:"贴膜容易失败且在意隐私的用户",market:"西班牙",language:"西班牙语",platform:"TikTok",targetDuration:30,creativeMode:"KOC / UGC",hookStrategy:"好奇",framework:"PAS",creativeAngle:script.creativeAngle,offer:"",productKnowledge:{name:"变形金刚钢化膜",sellingPoints:"10秒自动除尘安装；无尘无气泡；28°防窥",parameters:"左右28°防窥",bannedWords:"100%防爆；永不碎"},sourceType:"script-studio"};
async function requestDirector(overrides={}){delete process.env.DEEPSEEK_API_KEY;const worker=await loadWorker();const response=await worker.fetch(new Request("http://localhost/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({script,context:{...context,...overrides}})}),{},runtime);assert.equal(response.status,200);return response.json();}

test("A 30s KOC uses a visual information gap and controlled duration",async()=>{const data=await requestDirector();assert.match(data.shots[0].visualDescription,/局部结果|答案缺口|异常细节/);assert.ok(data.shots[0].endTime<=3);assert.equal(data.metadata.targetDuration,30);assert.equal(data.metadata.plannedDuration,30);assert.equal(data.metadata.durationDelta,0);assert.equal(data.metadata.fallbackUsed,true);assert.match(data.metadata.contextId,/^director-/);assert.equal(data.metadata.contextIntegrity.status,"Complete",JSON.stringify(data.metadata.contextIntegrity.issues));});
test("B product demonstration with result-first starts on the result",async()=>{const data=await requestDirector({creativeMode:"产品演示",hookStrategy:"结果前置"});assert.match(data.shots[0].visualDescription,/第一帧直接展示.*完成结果/);assert.equal(data.shots.some(x=>/Proof Shot/.test(x.shotType)&&/操作前|完整拍|安装器/.test(x.visualDescription)),true);});
test("C proof points become executable installation, bubble and privacy shots",async()=>{const data=await requestDirector();const proof=data.shots.filter(x=>x.proofRequirement).map(x=>`${x.visualDescription} ${x.proofRequirement}`).join("\n");assert.match(proof,/安装器.*按压.*滑动/);assert.match(proof,/灰尘.*气泡/);assert.match(proof,/正面.*侧面.*可视变化/);assert.equal(data.metadata.factGuardPassed,true);});
test("D/E every shot maps to a Script Block and timing is contiguous",async()=>{const data=await requestDirector();const ids=new Set(script.scenes.map((_,i)=>`scene-${i+1}`));let cursor=0;for(const shot of data.shots){assert.ok(ids.has(shot.sourceBlockId));assert.equal(shot.startTime,cursor);cursor=shot.endTime;}assert.equal(cursor,30);assert.equal(data.shots.at(-1).endTime,30);});
test("F/G Director inputs preserve Studio, history and Replication context",async()=>{const [page,studio,replication,director]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/script-studio.tsx",import.meta.url),"utf8"),readFile(new URL("../app/viral-replication.tsx",import.meta.url),"utf8"),readFile(new URL("../app/shooting-director.tsx",import.meta.url),"utf8")]);for(const marker of ["directorInput","productKnowledge:directorProduct","sourceType:directorSourceType","replication:{","proofMapping","sellingPointMapping","setDirectorSourceType(\"history\")","setDirectorSourceType(\"viral-replication\")"])assert.ok(page.includes(marker),marker);assert.ok(studio.includes("进入 AI 导演"));assert.ok(replication.includes("采用并进入 AI Director"));for(const marker of ["导演方案","sourceBlockId","证明要求","安全回退","产品知识"])assert.ok(director.includes(marker),marker);});
test("H sealed product capabilities remain present",async()=>{const files=await Promise.all(["script-studio.tsx","viral-analyzer.tsx","viral-replication.tsx","knowledge-context.ts","provider-router.ts"].map(file=>readFile(new URL(`../app/${file}`,import.meta.url),"utf8")));const all=files.join("\n");for(const marker of ["compareOpen","checkCompliance","Similarity","buildKnowledgeContext","callProvider"])assert.ok(all.includes(marker),marker);});
test("Step 5.2 single-shot regenerate returns a candidate without replacing the Director",async()=>{delete process.env.DEEPSEEK_API_KEY;const director=await requestDirector();const worker=await loadWorker(),currentShot=director.shots.find(x=>x.proofRequirement)||director.shots[1];const response=await worker.fetch(new Request("http://localhost/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({script,context,contextId:director.metadata.contextId,settings:{provider:"deepseek"},action:"regenerate-shot",directorPlan:director.directorPlan,currentShot,previousShot:director.shots[currentShot.order-2],nextShot:director.shots[currentShot.order],sourceBlock:{id:currentShot.sourceBlockId,stage:currentShot.stage,text:script.scenes[currentShot.order-1]?.line||script.proof},preset:"更有视觉冲击",instruction:"保持证明逻辑但容易用手机拍"})}),{},runtime);assert.equal(response.status,200);const data=await response.json();assert.equal(data.candidate.shotId,currentShot.shotId);assert.equal(data.candidate.duration,currentShot.duration);assert.equal(data.metadata.fallbackUsed,true);assert.equal(data.metadata.factGuardPassed,true);assert.equal(director.shots[currentShot.order-1].visualDescription,currentShot.visualDescription);});
