import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

async function loadWorker(){const url=new URL("../dist/server/index.js",import.meta.url);url.searchParams.set("replication-test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(url.href)).default;}
const runtime={waitUntil(){},passThroughOnException(){}};
const sourceCase={id:"source-1",title:"English certified bottle",createdAt:new Date(0).toISOString(),source:{sourceText:"Stop buying ordinary bottles. This military-grade certified bottle keeps drinks cold for 72 hours and costs only $19. Slide the lock, turn it over, and watch it stay dry. Get yours before midnight.",inputType:"transcript",language:"English",product:"Source Bottle"},analysis:{summary:"",contentType:"Demonstration",targetAudience:"",corePromise:"",creativeAngle:"Negative warning plus leak test",hook:{original:"Stop buying ordinary bottles.",type:"Warning",mechanism:"Negative warning + information gap",informationGap:"Which option works",conflict:"Ordinary bottle leaks",curiosity:"",promise:"",payoff:"",whyItWorks:""},structure:[{stage:"Hook",content:"",purpose:"",viewerPsychology:""},{stage:"Problem",content:"",purpose:"",viewerPsychology:""},{stage:"Proof",content:"",purpose:"",viewerPsychology:""},{stage:"CTA",content:"",purpose:"",viewerPsychology:""}],pacing:{assessment:"Fast reveal and proof",retentionBeats:[]},emotionCurve:[],sellingPoints:[],proofMechanisms:[{type:"Stress Test",content:"Turn bottle upside down",observed:true}],objections:[],productReveal:"",cta:"Get yours before midnight.",ctaStyle:"Urgent direct CTA",viralMechanisms:["Negative warning opens a loop","Visible proof pays it off"],reusableFormula:["Warning","Problem","Reveal","Proof","CTA"],replicationNotes:{visualSuggestions:[],copySuggestions:[],editingSuggestions:[]},risks:[],timeline:[],score:{hookStrength:80,structureClarity:80,proofStrength:70,informationDensity:70,ctaIntegration:70,replicability:80,total:75,explanation:[]},metadata:{analysisProvider:"deepseek",inputType:"transcript",transcriptProvided:true,visualEvidenceAvailable:false,timelineEstimated:true,productContextUsed:false,marketContextUsed:false,scoringModel:"viralflow-rule-v1"}}};
const target={product:"变形金刚钢化膜",sellingPoints:"10秒自动除尘安装；无灰尘无气泡；28°防窥",audience:"贴膜容易失败的用户",country:"西班牙",language:"西班牙语",platform:"TikTok",duration:"30",offer:"",productKnowledge:{name:"变形金刚钢化膜",sellingPoints:"10秒自动除尘安装；无灰尘无气泡；28°防窥",parameters:"28°防窥",bannedWords:"100%防爆；永不碎"}};
const setup={mode:"formula",intensity:"medium",market:"西班牙",language:"西班牙语",platform:"TikTok",duration:"30",instruction:"尽量保持原文，只换产品名。"};
const strategy={sourceMechanism:["Negative warning"],transferableElements:["Open loop","Proof position"],nonTransferableElements:["72 hours","military-grade certified","$19"],targetProductFit:"安装痛点可承接",targetAudienceFit:"贴膜失败人群",hookPlan:"用新的西语失败场景开头",structurePlan:["Hook","Problem","Reveal","Proof","CTA"],scenarioPlan:"Dormitorio desk",proofPlan:"10秒安装演示",sellingPointPlan:"10秒安装为主",ctaPlan:"核对型号",originalityPlan:"更换句式场景与证明动作",sellingPointMapping:[{sourceFunction:"Fast visible result",targetSellingPoint:"10秒自动除尘安装",reason:"同为快速可见结果"}],proofMapping:[{sourceProofFunction:"Stress Test",targetProof:"失败安装 vs 自动对位完成",reason:"符合Target事实"}]};
const concept=(id,direction)=>({id,direction,creativeAngle:`${direction} angle`,hookMechanism:"Information gap",scenario:`Scenario ${id}`,conflict:`Conflict ${id}`,proofMechanism:`Proof ${id}`,sellingPointPriority:id==="B"?"水珠滑落效果":id==="C"?"10秒安装":"10秒自动除尘安装",ctaStyle:"Soft model check",sourceMechanismRetained:["Open loop"],originalElementsIntroduced:[`New ${id}`],whyThisAdaptation:`Why ${id}`});

test("A/C strategy returns three distinct replication directions and blocks copy trap",async()=>{process.env.REPLICATION_TEST_MODE="1";process.env.REPLICATION_TEST_RESPONSE=JSON.stringify({strategy,concepts:[concept("A","Faithful Mechanism"),concept("B","Product Native"),concept("C","Creative Mutation")]});const worker=await loadWorker();try{const response=await worker.fetch(new Request("http://localhost/api/replicate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"strategy",sourceCase,setup,target})}),{},runtime);assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.concepts.map(x=>x.direction),["Faithful Mechanism","Product Native","Creative Mutation"]);assert.equal(data.concepts[1].sellingPointPriority,"10秒自动除尘安装");assert.equal(data.concepts[2].sellingPointPriority,"无灰尘无气泡");assert.equal(data.metadata.sellingPointGuardApplied,true);assert.equal(data.metadata.copyTrapBlocked,true);assert.equal(data.metadata.sourceFactsExcludedFromPrompt,true);}finally{delete process.env.REPLICATION_TEST_MODE;delete process.env.REPLICATION_TEST_RESPONSE;}});

test("B/D similarity and fact guards reject source leakage and unsupported CTA offers",async()=>{const copied={title:"Copied",creativeAngle:"Warning",hook:"Stop buying ordinary bottles.",narration:"Stop buying ordinary bottles. This military-grade certified screen protector works for 72 hours. Get yours before midnight.",cta:"Get yours before midnight.",conflict:"x",productReveal:"x",proof:"x",scenario:"copied",proofMechanism:"copied",concept:{hookMechanism:"Negative warning",scenario:"copied",proofMechanism:"copied",sellingPointPriority:"copied"}};const safe={title:"Nuevo",creativeAngle:"Failure rescue",hook:"¿Otra vez te quedó una burbuja justo en el centro?",narration:"¿Otra vez te quedó una burbuja justo en el centro? Mira el fallo. Coloco el móvil, deslizo el aplicador y en 10 segundos queda alineado. Comprueba tu modelo.",cta:"Comprueba tu modelo.",conflict:"Burbujas",productReveal:"Aplicador",proof:"Instalación visible",scenario:"mesa",proofMechanism:"installation demo",concept:{hookMechanism:"Information gap",scenario:"mesa",proofMechanism:"installation demo",sellingPointPriority:"10 seconds"}};const inventedOffer={...safe,cta:"Quedan pocas unidades e incluye protector de cámara gratis."};const worker=await loadWorker();const response=await worker.fetch(new Request("http://localhost/api/replicate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"check",sourceCase,setup,target,candidates:[{id:"A",script:copied},{id:"B",script:safe},{id:"C",script:inventedOffer}]})}),{},runtime);assert.equal(response.status,200);const data=await response.json();assert.equal(data.checks[0].originalityPassed,false);assert.ok(data.checks[0].sourceLeakage.some(x=>/72 hours|military/i.test(x)));assert.equal(data.checks[1].originalityPassed,true);assert.deepEqual(data.checks[1].factViolations,[]);assert.ok(data.checks[2].factViolations.includes("使用了未提供的促销、赠品或库存信息"));assert.ok(data.checks[1].structureSimilarity>=0);});

test("F mapping uses source selling/proof function and target facts",()=>{assert.deepEqual(strategy.sellingPointMapping[0],{sourceFunction:"Fast visible result",targetSellingPoint:"10秒自动除尘安装",reason:"同为快速可见结果"});assert.equal(strategy.proofMapping[0].targetProof,"失败安装 vs 自动对位完成");assert.doesNotMatch(JSON.stringify(strategy.proofMapping),/72 hours|military-grade|\$19/i);});

test("G/H UI adopts into existing Studio and preserves sealed capabilities",async()=>{const [replication,page,studio]=await Promise.all([readFile(new URL("../app/viral-replication.tsx",import.meta.url),"utf8"),readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/script-studio.tsx",import.meta.url),"utf8")]);for(const marker of ["复刻策略","A / B / C 三种原创方向","主卖点","采用此方向 →","来源与新版本对比","采用此版本 → Script Studio","采用并进入 AI Director","onAdopt(chosen.script,reference,setup)"])assert.ok(replication.includes(marker),marker);for(const marker of ["adoptReplication","setResult(adopted)","setActive(next)","duration:setup.duration"])assert.ok(page.includes(marker),marker);for(const marker of ["undoLastRewrite","saveVersion","重写未锁定","锁定","checkCompliance","onGenerateRace","compareOpen"])assert.ok(studio.includes(marker),marker);});
