import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createJiti } from "jiti";

const jiti=createJiti(import.meta.url);
const {scriptQualityFewShotLibrary,selectScriptQualityFewShots,fewShotSimilarityIssues,MIN_RELEVANCE_SCORE}=await jiti.import("../app/script-quality/few-shots/index.ts");
const {writerMessages,criticMessages}=await jiti.import("../app/script-quality/prompts.ts");
const {runScriptQualityEngine,resolveScriptEngineMode}=await jiti.import("../app/script-quality/engine.ts");
const query={market:"Spain",platform:"TikTok",productCategory:"3C 数码",contentFormat:"Visual Test",creatorPersona:"普通手机用户",hookMechanism:"Visual Test",primarySellingPoint:"防窥效果",proofMechanism:"角度变化",language:"西班牙语"};
const concept={id:"A",creativeAngle:"角度实测",hookMechanism:"Visual Test",hookLine:"转动手机",openingVisual:"手机正侧转动",corePainPoint:"公共场合隐私",primarySellingPoint:"防窥效果",proofMechanism:"角度变化",creatorPersona:"普通手机用户",contentFormat:"Visual Test",ctaDirection:"检查型号",riskNotes:[]};
const input={product:"Transformers Screen Protector",sellingPoints:"防窥效果；安装器辅助对位",audience:"手机用户",country:"Spain",language:"西班牙语",platform:"TikTok",duration:"25",offer:"",style:"UGC",knowledgePrompt:"只使用已提供事实",outputCount:1};

test("1 library exposes exactly five human-approved and five curated drafts",()=>{assert.equal(scriptQualityFewShotLibrary.length,10);assert.equal(scriptQualityFewShotLibrary.filter(item=>item.status==="approved").length,5);assert.equal(scriptQualityFewShotLibrary.filter(item=>item.status==="curated-draft").length,5)});
test("2/3 selector returns at most three and never pads below relevance threshold",()=>{const broad={market:"Spain Mexico United States United Kingdom",platform:"TikTok",productCategory:"3C 数码美妆个护家居日用食品饮料健身运动",language:"西班牙语 英语"};assert.equal(MIN_RELEVANCE_SCORE,10);assert.equal(selectScriptQualityFewShots(broad).length,3);assert.equal(selectScriptQualityFewShots(broad,{limit:99}).length,3);assert.equal(selectScriptQualityFewShots({market:"Mars",platform:"YouTube",language:"日语"}).length,0)});
test("production selector naturally allows one or two relevant references",()=>{const one=selectScriptQualityFewShots({market:"Mexico",platform:"TikTok",productCategory:"美妆个护",hookMechanism:"Comment Reply",language:"西班牙语"});const two=selectScriptQualityFewShots(query);assert.equal(one.length,1);assert.equal(two.length,2)});
test("4 same category is prioritized",()=>{const selected=selectScriptQualityFewShots(query);assert.equal(selected.length,2);assert.ok(selected.every(item=>item.productCategory==="3C 数码"))});
test("5 diversity replacement prevents one Hook or Proof mechanism taking every slot",()=>{const selected=selectScriptQualityFewShots({market:"Spain Mexico United States United Kingdom",platform:"TikTok",productCategory:"3C 数码美妆个护家居日用",language:"西班牙语 英语"});assert.ok(new Set(selected.map(item=>item.hookMechanism)).size>1);assert.ok(new Set(selected.map(item=>item.proofMechanism)).size>1)});
test("6 library and selector never read project history or a database",async()=>{const source=await Promise.all(["../app/script-quality/few-shots/library.ts","../app/script-quality/few-shots/select.ts"].map(path=>readFile(new URL(path,import.meta.url),"utf8")));assert.doesNotMatch(source.join("\n"),/project-memory|localStorage|database|db\/|read.*history|recentScripts/i)});
test("7 Writer receives compact Reference Examples with anti-copy and CTA anti-pattern rules",()=>{const references=selectScriptQualityFewShots(query);const messages=writerMessages(input,concept,references);const section=messages[1].content.split("Reference Examples")[1];assert.match(messages[0].content,/不得复制具体措辞/);assert.match(messages[1].content,/Reference Examples/);assert.match(section,/whyItWorks/);assert.match(messages[1].content,/CTA Anti-Pattern Rule/);assert.match(messages[1].content,/可以不出现、评论互动、场景建议/);assert.doesNotMatch(section,/doNotCopyLiterally|productCategory|creatorPersona/)});
test("8 legacy default remains unchanged",()=>{assert.equal(resolveScriptEngineMode(undefined),"legacy");assert.equal(resolveScriptEngineMode("legacy"),"legacy")});
test("9 Critic prompt does not receive Few-shot references",()=>{const messages=criticMessages(input,concept,scriptQualityFewShotLibrary[0].example,[concept]);assert.doesNotMatch(messages.map(item=>item.content).join("\n"),/Reference Examples|whyItWorks|doNotCopyLiterally/)});

test("10 copied reference triggers one few_shot_similarity targeted rewrite",async()=>{
  const reference=scriptQualityFewShotLibrary[0],copied=reference.example;
  assert.ok(fewShotSimilarityIssues(copied,[reference]).some(issue=>issue.type==="few_shot_similarity"&&issue.severity==="high"));
  const concepts=[concept,{...concept,id:"B",hookMechanism:"Pain Point",openingVisual:"贴歪边缘",primarySellingPoint:"对位",proofMechanism:"四边检查",creatorPersona:"新手",contentFormat:"Problem Solution"},{...concept,id:"C",hookMechanism:"Comment Reply",openingVisual:"评论与除尘条",primarySellingPoint:"除尘",proofMechanism:"屏幕近景",creatorPersona:"测评者",contentFormat:"Reply"},{...concept,id:"D",hookMechanism:"Curiosity",openingVisual:"水滴滚动",primarySellingPoint:"疏油层",proofMechanism:"水滴与纸巾",creatorPersona:"通勤者",contentFormat:"Daily Scene"},{...concept,id:"E",hookMechanism:"First Experience",openingVisual:"安装器落下",primarySellingPoint:"滑动顺畅",proofMechanism:"连续滑动",creatorPersona:"首次用户",contentFormat:"One Take"}];
  const rewritten={creativeDirection:"在桌面检查贴合结果",hook:{line:"先看这条边，我刚把安装器拿开。",visual:"手拿走安装器并指向手机上边缘。"},spokenScript:"先看这条边，我刚把安装器拿开。 我把手机放平，再沿着四边慢慢转一圈。 这里能看到膜和边框的位置。 接着装回手机壳，检查边缘没有被顶起。 需要换膜的话，先确认自己的手机型号。",shots:[{time:"0-3s",visual:"拿走安装器并指向上边缘。",line:"先看这条边，我刚把安装器拿开。",edit:"桌面近景。"},{time:"3-9s",visual:"放平手机并沿四边移动镜头。",line:"我把手机放平，再沿着四边慢慢转一圈。",edit:"连续移动。"},{time:"9-15s",visual:"停在膜与边框交界处。",line:"这里能看到膜和边框的位置。",edit:"微距。"},{time:"15-21s",visual:"装回手机壳并按压四角。",line:"接着装回手机壳，检查边缘没有被顶起。",edit:"四角特写。"},{time:"21-26s",visual:"手机型号页入镜。",line:"需要换膜的话，先确认自己的手机型号。",edit:"自然收尾。"}],proof:{claim:"安装完成后可检查贴合位置",visualEvidence:"连续展示四边并装回手机壳检查边缘。"},cta:"需要换膜的话，先确认自己的手机型号。"};
  const queue=[{concepts},copied,{pass:true,issues:[],preserve:[]},rewritten];let calls=0;
  const result=await runScriptQualityEngine(input,{statuses:()=>({deepseek:{configured:true,model:"deepseek-test"},openai:{configured:true,model:"gpt-test"},doubao:{configured:false,model:null}}),selectFewShots:()=>[reference],call:async()=>({content:JSON.stringify(queue[calls++]),responseTimeMs:5,status:200,finishReason:"stop"})});
  assert.equal(result.status,"success");assert.equal(result.metadata.rewriteTriggered,true);assert.equal(result.metadata.rewrite.length,1);assert.equal(calls,4);
});

test("11/12 public Script contract and database schema stay outside the Few-shot change",async()=>{const [types,memory]=await Promise.all([readFile(new URL("../app/script-quality/types.ts",import.meta.url),"utf8"),readFile(new URL("../app/project-memory.ts",import.meta.url),"utf8")]);assert.match(types,/StructuredScript\[\]/);assert.match(memory,/PROJECT_MEMORY_VERSION = 1/)});
