import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";

async function loadWorker(){const url=new URL("../dist/server/index.js",import.meta.url);url.searchParams.set("analyzer-test",`${process.pid}-${Date.now()}-${Math.random()}`);return(await import(url.href)).default;}
const runtime={waitUntil(){},passThroughOnException(){}};
const transcript="No compres otro protector todavía. Siempre me quedaban burbujas y polvo, pero este aplicador alinea el cristal y retira el polvo en diez segundos. Lo deslicé una vez y quedó recto, sin burbujas. Comprueba tu modelo en el enlace.";
const providerResult={summary:"Una demostración de instalación convierte un problema cotidiano en una prueba visible.",contentType:"UGC demonstration",targetAudience:"Personas que instalan mal sus protectores",corePromise:"Instalación sencilla",creativeAngle:"Fracaso cotidiano seguido de demostración",hook:{original:"No compres otro protector todavía.",type:"Advertencia",mechanism:"Interrupción + información incompleta",informationGap:"Qué protector sí conviene",conflict:"Instalaciones con polvo y burbujas",curiosity:"Promete revelar una alternativa",promise:"Evitar otra mala compra",payoff:"Muestra una instalación recta",whyItWorks:"Interrumpe la compra y deja la solución abierta."},structure:[{stage:"Hook",content:"No compres otro protector todavía.",purpose:"Detener el scroll",viewerPsychology:"Evitar una mala decisión"},{stage:"Problem",content:"Siempre me quedaban burbujas y polvo.",purpose:"Identificación",viewerPsychology:"Reconocer el dolor"},{stage:"Proof",content:"Lo deslicé una vez y quedó recto.",purpose:"Demostrar",viewerPsychology:"Reducir duda"},{stage:"CTA",content:"Comprueba tu modelo.",purpose:"Acción",viewerPsychology:"Validar compatibilidad"}],pacing:{assessment:"Información nueva en cada frase",retentionBeats:["Advertencia abierta","Problema reconocible","Demostración","Resultado"]},emotionCurve:[{stage:"Hook",emotion:"Curiosidad",trigger:"Advertencia"},{stage:"Proof",emotion:"Confianza",trigger:"Resultado visible"}],sellingPoints:[{point:"Instalación en diez segundos",priority:"primary",evidence:"en diez segundos"}],proofMechanisms:[{type:"Demonstration",content:"Desliza el aplicador y muestra el resultado",observed:true}],objections:["Miedo a dejar burbujas"],productReveal:"Después del problema",cta:"Comprueba tu modelo en el enlace.",ctaStyle:"Natural y de compatibilidad",viralMechanisms:["El Hook abre una decisión sin resolver","La demostración paga la promesa"],reusableFormula:["Advertencia","Dolor cotidiano","Producto retrasado","Demostración","Resultado","CTA natural"],replicationNotes:{visualSuggestions:["Plano cenital de la instalación"],copySuggestions:["Mantener la advertencia sin copiar la frase"],editingSuggestions:["Corte en cada paso"]},risks:[],timeline:[{start:"0s",end:"5s",stage:"Hook",spokenContent:"No compres otro protector todavía.",visualDescription:"pantalla en primer plano",editingNote:"corte rápido",purpose:"Detener el scroll",retentionMechanism:"Open Loop"}]};
const input={sourceText:transcript,inputType:"transcript",platform:"TikTok",market:"España",language:"Español",durationSeconds:30,product:"protector de pantalla"};

async function analyze(body=input,response=JSON.stringify(providerResult)){process.env.ANALYZE_TEST_MODE="1";process.env.ANALYZE_TEST_RESPONSE=response;const worker=await loadWorker();try{return await worker.fetch(new Request("http://localhost/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),{},runtime);}finally{delete process.env.ANALYZE_TEST_MODE;delete process.env.ANALYZE_TEST_RESPONSE;delete process.env.ANALYZE_TEST_RESPONSES;}}

test("A returns structured hook, structure, proof, CTA, mechanism and formula",async()=>{const response=await analyze();assert.equal(response.status,200);const {analysis,provider}=await response.json();assert.equal(provider,"deepseek");assert.equal(analysis.hook.mechanism,"Interrupción + información incompleta");assert.equal(analysis.structure.length,4);assert.equal(analysis.proofMechanisms[0].observed,true);assert.ok(analysis.viralMechanisms.length);assert.ok(analysis.reusableFormula.length);assert.equal(analysis.metadata.scoringModel,"viralflow-rule-v1");});

test("B/C transcript-only never invents visuals and labels estimated timeline",async()=>{const response=await analyze();const {analysis}=await response.json();assert.equal(analysis.metadata.visualEvidenceAvailable,false);assert.equal(analysis.metadata.timelineEstimated,true);assert.equal(analysis.timeline[0].visualDescription,"unknown / not provided");assert.equal(analysis.timeline[0].editingNote,"unknown / not provided");assert.ok(analysis.replicationNotes.visualSuggestions.length);});

test("D/E/F case storage, Knowledge Engine and replication adapters are wired",async()=>{const [page,core,knowledge]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../app/viral-analysis.ts",import.meta.url),"utf8"),readFile(new URL("../app/knowledge-context.ts",import.meta.url),"utf8")]);for(const marker of ["viralflow-viral-cases-v1","adaptLegacyCases","saveViralCases","爆款案例库","用于脚本生成","replicateViralCase"])assert.ok(page.includes(marker),marker);for(const marker of ["[VIRALFLOW_CASE_V1]","Hook Mechanism:","Creative Angle:","Reusable Formula:"])assert.ok(core.includes(marker),marker);assert.ok(knowledge.includes('labeled("Hook Mechanism")'));assert.ok(knowledge.includes('labeled("CTA Style")'));});

test("G keeps Step 2.4 Studio regression capabilities",async()=>{const source=await readFile(new URL("../app/script-studio.tsx",import.meta.url),"utf8");for(const marker of ["onGenerateRace","adoptRace","compareOpen","重写未锁定","undoLastRewrite","saveVersion","checkCompliance","scoreScript"])assert.ok(source.includes(marker),marker);});

test("H accepts a JSON object wrapped in a Markdown fence",async()=>{const response=await analyze(input,`\uFEFF  \`\`\`json\n${JSON.stringify(providerResult)}\n\`\`\`  `);assert.equal(response.status,200);const {analysis}=await response.json();assert.equal(analysis.hook.type,"Advertencia");});

test("I extracts a balanced JSON object without being confused by braces in strings",async()=>{const result={...providerResult,summary:"Informe {estable} con texto adicional"};const response=await analyze(input,`Resultado del análisis:\n${JSON.stringify(result)}\nFin del análisis.`);assert.equal(response.status,200);const {analysis}=await response.json();assert.equal(analysis.summary,"Informe {estable} con texto adicional");});

test("J retries once after a truncated structured response",async()=>{process.env.ANALYZE_TEST_RESPONSES=JSON.stringify([JSON.stringify(providerResult).slice(0,-12),JSON.stringify(providerResult)]);const response=await analyze(input);assert.equal(response.status,200);const {analysis}=await response.json();assert.equal(analysis.contentType,"UGC demonstration");});

test("K keeps the public error contract when both structured responses are invalid",async()=>{process.env.ANALYZE_TEST_RESPONSES=JSON.stringify(["not-json","still-not-json"]);const response=await analyze(input);assert.equal(response.status,502);assert.deepEqual(await response.json(),{error:"爆款分析暂时失败，请重试"});});

test("L rejects an empty provider content without changing the public contract",async()=>{const response=await analyze(input,"");assert.equal(response.status,502);assert.deepEqual(await response.json(),{error:"爆款分析暂时失败，请重试"});});
