import {buildKnowledgeContext,findFactViolations,type ProductKnowledge} from "./knowledge-context";
import type {StructuredScript} from "./script-generation";
import type {ProviderErrorType,ProviderId} from "./provider-types";

export const framingValues=["Extreme Close-Up","Close-Up","Medium Close-Up","Medium","Wide","Over-the-Shoulder","Top-Down","Product Macro"] as const;
export const cameraAngleValues=["Eye Level","High Angle","Low Angle","Top-Down","Side Angle","45 Degree"] as const;
export const cameraMovementValues=["Static","Push In","Pull Out","Pan","Tilt","Handheld","Tracking"] as const;
export type DirectorSourceType="script-studio"|"viral-replication"|"history";
export type DirectorShot={shotId:string;order:number;startTime:number;endTime:number;duration:number;sourceBlockId:string;stage:string;purpose:string;shotType:string;framing:typeof framingValues[number];cameraAngle:typeof cameraAngleValues[number];cameraMovement:typeof cameraMovementValues[number];visualDescription:string;subject:string;productAction:string;talentAction:string;props:string[];environment:string;dialogue:string;voiceover:string;onScreenText:string;proofRequirement:string;transition:string;editingNotes:string;audioSfx:string;continuityNotes:string;priority:"Critical"|"High"|"Normal"};
export type DirectorPlan={recommendationType:"Director Recommendation";creativeIntent:string;visualStyle:string;hookExecution:string;pacingStrategy:string;proofStrategy:string;productRevealStrategy:string;ctaExecution:string;shootingComplexity:"Simple"|"Standard"|"Advanced";requiredTalent:string[];requiredProps:string[];requiredLocations:string[]};
export type ContextIntegrityIssue={code:"product_identity"|"source_block"|"ungrounded_entity"|"context_identity";message:string;value?:string};
export type ContextIntegrityResult={status:"Complete"|"Needs Attention";issues:ContextIntegrityIssue[]};
export type DirectorMetadata={providerRequested:ProviderId;providerUsed:ProviderId|"local";aiGenerated:boolean;fallbackUsed:boolean;providerErrorType:ProviderErrorType|null;responseTimeMs:number|null;targetDuration:number;plannedDuration:number;durationDelta:number;durationRebalanced:boolean;shotCount:number;sourceType:DirectorSourceType;productKnowledgeUsed:boolean;factGuardPassed:boolean;contextId:string;sourceScriptRevisionId?:string;contextIntegrity:ContextIntegrityResult};
export type DirectorResult={directorPlan:DirectorPlan;shots:DirectorShot[];metadata:DirectorMetadata};
export type DirectorRequest={projectId?:string;scriptRevisionId?:string;script:StructuredScript;context:{product:string;sellingPoints:string;audience:string;market:string;language:string;platform:string;targetDuration:number;creativeMode:string;hookStrategy:string;framework:string;creativeAngle:string;offer?:string;productKnowledge?:ProductKnowledge;referenceScript?:string;sourceType:DirectorSourceType;replication?:{sourceMechanism?:string;replicationStrategy?:string;proofMapping?:string;sellingPointMapping?:string}};settings?:{talent?:string;environment?:string;provider?:ProviderId}};

const text=(value:unknown)=>typeof value==="string"?value.trim():"";
const split=(value:string)=>value.split(/[；;\n]+/).map(x=>x.trim()).filter(Boolean);
const round10=(value:number)=>Math.round(value*10)/10;
const normalized=(value:unknown)=>text(value).normalize("NFKC").toLowerCase().replace(/\s+/g," ");
const hash=(value:string)=>{let output=2166136261;for(let index=0;index<value.length;index++){output^=value.charCodeAt(index);output=Math.imul(output,16777619);}return(output>>>0).toString(36);};
export function directorContextId(request:DirectorRequest){const replication=request.context.replication;return`director-${hash(JSON.stringify({projectId:request.projectId||"legacy-project",scriptRevisionId:request.scriptRevisionId||"legacy-revision",script:scriptBlocks(request.script).map(x=>({id:x.id,stage:x.stage,text:normalized(x.text),visual:normalized(x.visual)})),product:normalized(request.context.product),source:request.context.sourceType,duration:targetDuration(request.context.targetDuration),language:normalized(request.context.language),replication:replication?{sourceMechanism:normalized(replication.sourceMechanism),sellingPointMapping:normalized(replication.sellingPointMapping),proofMapping:normalized(replication.proofMapping),creativeAngle:normalized(request.context.creativeAngle)}:null}))}`;}
export function targetDuration(value:unknown){const number=Number(value);return [15,20,30,45,60].includes(number)?number:Math.min(60,Math.max(15,Number.isFinite(number)?number:30));}
export function scriptBlocks(script:StructuredScript){
 const sceneList=script.scenes||[];
 const scenes=sceneList.map((scene,index)=>({id:`scene-${index+1}`,stage:index===0?"HOOK":index===sceneList.length-1?"CTA":/安装|测试|证明|结果|install|prueba|test|result|burbuja|polvo|privacy|privacidad/i.test(`${scene.visual} ${scene.line}`)?"PROOF":"BODY",text:scene.line,visual:scene.visual,edit:scene.edit}));
 return scenes.length?scenes:[{id:"hook",stage:"HOOK",text:script.hook,visual:"",edit:""},{id:"conflict",stage:"CONFLICT",text:text(script.conflict),visual:"",edit:""},{id:"reveal",stage:"PRODUCT REVEAL",text:text(script.productReveal),visual:"",edit:""},{id:"proof",stage:"PROOF",text:text(script.proof),visual:"",edit:""},{id:"selling-points",stage:"SELLING POINT",text:text(script.sellingPoints),visual:"",edit:""},{id:"cta",stage:"CTA",text:text(script.cta),visual:"",edit:""}].filter(x=>x.text);}
function proofVisual(point:string){
 if(/安装|对位|除尘|气泡|贴歪|install|align|dust|bubble|polvo|burbuja/i.test(point))return "手机屏幕微距先记录灰尘或旧贴膜失败状态；手机放入安装器后保持同一机位，完整拍下按压与滑动动作；移除安装器后沿四角移动微距焦点，检查屏幕表面、边缘、灰尘和气泡变化。";
 if(/防窥|隐私|28|privacy|privacidad|ángulo|angle/i.test(point))return "先从正面拍清晰屏幕，再保持同一部手机和亮度不变，将镜头移动到侧面观察角度；用正面与侧面连续切换呈现可视变化。";
 if(/疏水|疏油|水|油|指纹|hydro|agua|huella/i.test(point))return "固定手机角度，在屏幕表面放置一滴水并轻微倾斜手机，近距离记录水滴移动和表面残留；测试前后保持光线一致。";
 if(/抗刮|耐磨|抗冲击|scratch|impact|ray|golpe/i.test(point))return "在受控桌面环境中先拍工具与屏幕完整状态，再以可重复的轻度同条件动作测试；测试后用微距扫过表面并避免声称超出产品知识的结果。";
 return `用固定机位完整拍摄“操作前状态 → ${point}对应动作 → 操作后可见结果”，保留连续过程作为证明。`;
}
function hookVisual(strategy:string,firstVisual:string,product:string){
 if(/结果/.test(strategy))return `第一帧直接展示可验证的完成结果，画面停留足够看清变化；随后切回过程解释。${firstVisual}`;
 if(/冲突/.test(strategy))return `第一帧呈现失败状态、反差或同条件冲突，先让问题成立；${product}延后到后续 Reveal Shot。${firstVisual}`;
 if(/视觉/.test(strategy))return `第一帧由一个无需解释也能看懂的可执行动作驱动，镜头贴近变化区域，口播只解释正在发生的画面。${firstVisual}`;
 return `第一帧只展示异常细节、未完成动作或局部结果，保留答案缺口；不要马上完整讲解${product}，在3秒内给出继续观看的视觉理由。${firstVisual}`;
}
export function rebalanceShots(shots:DirectorShot[],target:number){
 if(!shots.length)return shots;const first=Math.min(3,round10(target*.2)),last=shots.length===1?0:Math.min(3,round10(target*.12)),middleCount=Math.max(0,shots.length-2),middle=middleCount?round10((target-first-last)/middleCount):0;let cursor=0;
 return shots.map((shot,index)=>{const duration=index===0?first:index===shots.length-1?round10(target-cursor):middle;const startTime=round10(cursor);cursor=round10(cursor+duration);return{...shot,order:index+1,shotId:`shot-${String(index+1).padStart(2,"0")}`,startTime,endTime:round10(index===shots.length-1?target:cursor),duration:round10((index===shots.length-1?target:cursor)-startTime)};});
}
export function shootingComplexity(shots:DirectorShot[]){const locations=new Set(shots.map(x=>x.environment).filter(Boolean));const talent=new Set(shots.map(x=>x.subject).filter(x=>/模特|人物|talent|person/i.test(x)));const advanced=shots.filter(x=>/Tracking|Handheld|Pan|Tilt/.test(x.cameraMovement)||/受控|对比|完整过程/.test(x.proofRequirement)).length;return shots.length>=11||locations.size>=3||talent.size>=2||advanced>=4?"Advanced":shots.length>=8||locations.size>=2||advanced>=2?"Standard":"Simple";}
export function fallbackDirector(request:DirectorRequest):Omit<DirectorResult,"metadata">{
 const blocks=scriptBlocks(request.script),points=split(request.context.sellingPoints),proofPoints=points.filter(x=>/安装|除尘|气泡|防窥|隐私|疏水|抗刮|install|dust|bubble|privacy/i.test(x)).slice(0,4);const seed=blocks.flatMap((block,index)=>{
  const isHook=index===0,isCta=index===blocks.length-1;const proof=/PROOF/.test(block.stage)||proofPoints.some(x=>block.text.includes(x));const base:DirectorShot={shotId:"",order:0,startTime:0,endTime:0,duration:0,sourceBlockId:block.id,stage:block.stage,purpose:isHook?"Attention":isCta?"Close / Action":proof?"Demonstration / Verification":"Narrative Progression",shotType:isHook?"Attention Shot":isCta?"CTA Shot":proof?"Proof Shot":"Action Shot",framing:isHook?"Extreme Close-Up":proof?"Product Macro":"Medium Close-Up",cameraAngle:proof?"45 Degree":"Eye Level",cameraMovement:isHook?"Push In":"Static",visualDescription:isHook?hookVisual(request.context.hookStrategy,block.visual,request.context.product):proof?proofVisual(block.text):`${request.settings?.environment||"整洁桌面"}内，${block.visual||`围绕“${block.text}”安排清晰动作`}；镜头必须拍到动作前后变化及该镜头承担的信息。`,subject:/KOC|UGC|口播/i.test(request.context.creativeMode)?"同一位KOC模特":"产品与操作手部",productAction:proof?"产品按证明步骤完整操作，不跳过关键动作":isCta?"产品包装与适配信息自然入镜":"产品只在脚本信息需要时进入画面",talentAction:/KOC|UGC|口播/i.test(request.context.creativeMode)?"模特自然完成口播，并用视线或手势引导观众看产品变化":"手部按画面顺序执行操作，避免遮挡结果",props:proof?[request.context.product,"手机","安装或测试所需工具"]:[request.context.product,"手机"],environment:request.settings?.environment||"同一张整洁桌面",dialogue:/KOC|UGC|口播/i.test(request.context.creativeMode)?block.text:"",voiceover:/KOC|UGC|口播/i.test(request.context.creativeMode)?"":block.text,onScreenText:isHook?block.text.slice(0,38):proof?"操作过程 / 实拍结果":"",proofRequirement:proof?"必须连续拍到操作前、关键动作和操作后结果；只验证知识库已有卖点":"",transition:isHook?"Hard Cut":isCta?"Clean Cut":"Jump Cut",editingNotes:block.edit||"在动作完成点剪切，保留结果观察时间",audioSfx:isHook?"轻量注意力音效；保留真实操作声":proof?"保留滑动、按压或测试的真实声音":"低音量节奏底乐",continuityNotes:"使用同一部手机、同一产品、同一桌面与一致光线；保持安装前后状态连续",priority:isHook||proof?"Critical":isCta?"High":"Normal"};
  return[base];});
 for(const point of proofPoints){if(seed.some(x=>x.proofRequirement&&(`${x.visualDescription}${x.voiceover}${x.dialogue}`).includes(point)))continue;const block=blocks.find(x=>/PROOF|SELLING/.test(x.stage))||blocks[Math.max(1,blocks.length-2)];seed.splice(Math.max(1,seed.length-1),0,{...seed[Math.max(0,seed.length-2)],sourceBlockId:block.id,stage:"PROOF",purpose:"Demonstration / Verification",shotType:"Proof Shot",framing:"Product Macro",cameraAngle:/防窥|隐私|privacy/.test(point)?"Side Angle":"45 Degree",cameraMovement:/防窥|隐私|privacy/.test(point)?"Tracking":"Static",visualDescription:proofVisual(point),dialogue:"",voiceover:`用实拍过程验证：${point}`,onScreenText:point,proofRequirement:`完整证明“${point}”，不得只用口播或字幕代替`,priority:"Critical"});}
 const shots=rebalanceShots(seed,targetDuration(request.context.targetDuration));const props=[...new Set(shots.flatMap(x=>x.props))];const locations=[...new Set(shots.map(x=>x.environment))];const talent=[...new Set(shots.map(x=>x.subject))];
 return{directorPlan:{recommendationType:"Director Recommendation",creativeIntent:`把“${request.context.creativeAngle||request.script.title}”转成清楚、快、原生且证明优先的${request.context.platform}短视频`,visualStyle:/KOC|UGC/i.test(request.context.creativeMode)?"自然KOC手持感与产品微距交替":"产品动作主导的干净桌拍",hookExecution:shots[0]?.visualDescription||"前三秒建立注意力",pacingStrategy:"前3秒建立注意力；中段每1–3秒出现动作或信息变化；Proof保留完整过程；CTA简洁收口",proofStrategy:proofPoints.length?proofPoints.map(proofVisual).join(" "):"只对脚本与产品知识中明确存在的卖点安排操作前、过程、结果证明",productRevealStrategy:/冲突|好奇/.test(request.context.hookStrategy)?"先建立问题或信息缺口，再让产品进入解决动作":"按脚本功能在结果后立即解释产品作用",ctaExecution:"产品、适配信息和下一步动作同框，避免突然硬切促销",shootingComplexity:shootingComplexity(shots),requiredTalent:talent,requiredProps:props,requiredLocations:locations},shots};
}
export function validateDirector(result:Omit<DirectorResult,"metadata">,request:DirectorRequest){const errors:string[]=[];if(!result.directorPlan||!Array.isArray(result.shots)||result.shots.length<5)errors.push("director_structure");const plan=result.directorPlan;if(!plan||![plan.creativeIntent,plan.visualStyle,plan.hookExecution,plan.pacingStrategy,plan.proofStrategy,plan.productRevealStrategy,plan.ctaExecution].every(text)||!["Simple","Standard","Advanced"].includes(plan.shootingComplexity)||![plan.requiredTalent,plan.requiredProps,plan.requiredLocations].every(Array.isArray))errors.push("director_plan_fields");const ids=new Set(scriptBlocks(request.script).map(x=>x.id));for(const shot of result.shots||[]){if(!ids.has(shot.sourceBlockId)&&!shot.sourceBlockId.startsWith("manual:"))errors.push("source_block_mapping");if(![shot.stage,shot.purpose,shot.shotType,shot.visualDescription,shot.subject,shot.productAction,shot.talentAction,shot.environment,shot.transition,shot.editingNotes,shot.audioSfx,shot.continuityNotes].every(text)||!Array.isArray(shot.props)||!["Critical","High","Normal"].includes(shot.priority))errors.push("shot_fields");if(!framingValues.includes(shot.framing)||!cameraAngleValues.includes(shot.cameraAngle)||!cameraMovementValues.includes(shot.cameraMovement))errors.push("camera_enum");}return[...new Set(errors)];}
export function directorKnowledge(request:DirectorRequest){return buildKnowledgeContext({product:request.context.product,sellingPoints:request.context.sellingPoints,audience:request.context.audience,country:request.context.market,language:request.context.language,platform:request.context.platform,offer:request.context.offer||"",productKnowledge:request.context.productKnowledge});}
export function directorFactViolations(result:Omit<DirectorResult,"metadata">,request:DirectorRequest){const knowledge=directorKnowledge(request);const plan=result.directorPlan;const surface=[plan?.creativeIntent,plan?.visualStyle,plan?.hookExecution,plan?.pacingStrategy,plan?.proofStrategy,plan?.productRevealStrategy,plan?.ctaExecution,...(plan?.requiredTalent||[]),...(plan?.requiredProps||[]),...(plan?.requiredLocations||[]),...(result.shots||[]).flatMap(x=>[x.stage,x.purpose,x.shotType,x.visualDescription,x.subject,x.productAction,x.talentAction,...(x.props||[]),x.environment,x.dialogue,x.voiceover,x.onScreenText,x.proofRequirement,x.transition,x.editingNotes,x.audioSfx,x.continuityNotes])].filter(Boolean).join("\n");const scriptGrounding=scriptBlocks(request.script).flatMap(block=>[block.text,block.visual]).join("\n");return findFactViolations(surface,knowledge,scriptGrounding);}
const commonProductionEntities=new Set("phone telefono teléfono mobile móvil screen pantalla product producto package packaging hand hands mano manos finger fingers dedo dedos table mesa desk camera cámara tripod trípode light lighting luz talent model modelo person persona cloth paño tool tools herramienta herramientas applicator aplicador installation instalación closeup macro room studio surface superficie drop drops gotas water agua edge edges esquinas corner background fondo voice audio text result resultado process proceso change cambio detail detalle action acción state estado frame plano shot scene escena angle ángulo side lado front frente time tiempo content contenido problem problema proof prueba字幕 手机 屏幕 产品 包装 手 手指 桌面 镜头 相机 灯光 模特 人物 清洁布 工具 安装器 表面 水滴 边缘 场景".split(/\s+/));
const entityTokens=(value:string)=>normalized(value).replace(/[^\p{L}\p{N}°]+/gu," ").split(/\s+/).filter(token=>token.length>=3&&!commonProductionEntities.has(token));
export function checkContextIntegrity(result:Omit<DirectorResult,"metadata">,request:DirectorRequest,expectedContextId=directorContextId(request)):ContextIntegrityResult{const issues:ContextIntegrityIssue[]=[],scriptProduct=(request.script as StructuredScript&{product?:string}).product||"";if(normalized(scriptProduct)&&normalized(scriptProduct)!==normalized(request.context.product))issues.push({code:"product_identity",message:"Structured Script 与 Director Product identity 不一致",value:`${scriptProduct} != ${request.context.product}`});const ids=new Set(scriptBlocks(request.script).map(x=>x.id));for(const shot of result.shots||[])if(!ids.has(shot.sourceBlockId)&&!shot.sourceBlockId.startsWith("manual:"))issues.push({code:"source_block",message:`Shot ${shot.shotId} 引用了当前脚本不存在的 Source Block`,value:shot.sourceBlockId});const grounded=[request.context.product,request.context.sellingPoints,request.context.audience,request.context.creativeAngle,request.context.productKnowledge?.name,request.context.productKnowledge?.sellingPoints,request.context.productKnowledge?.parameters,...scriptBlocks(request.script).flatMap(x=>[x.text,x.visual])].filter(Boolean).join(" "),groundedNormalized=normalized(grounded);const groundedTokens=new Set(entityTokens(grounded)),surface=[result.directorPlan?.creativeIntent,result.directorPlan?.hookExecution,result.directorPlan?.proofStrategy,...(result.shots||[]).flatMap(shot=>[shot.visualDescription,shot.productAction])].filter(Boolean).join(" "),mentioned=[...surface.matchAll(/\b(?:un|una|el|la|los|las)\s+([\p{L}][\p{L}-]{2,})/giu)].map(match=>match[1]);const candidates=[...(result.directorPlan?.requiredProps||[]),...(result.shots||[]).flatMap(x=>x.props||[]),...mentioned];for(const value of candidates){const candidateNormalized=normalized(value),tokens=entityTokens(value),generic=[...commonProductionEntities].some(entity=>entity.length>=2&&candidateNormalized.includes(entity)),isGrounded=generic||groundedNormalized.includes(candidateNormalized)||tokens.some(token=>groundedTokens.has(token)||groundedNormalized.includes(token));if(tokens.length&&!isGrounded)issues.push({code:"ungrounded_entity",message:"Director 使用了当前 Script / Product Context 未提供的核心实体",value});}if(expectedContextId!==directorContextId(request))issues.push({code:"context_identity",message:"Director Context ID 与当前 Script Context 不一致",value:expectedContextId});return{status:issues.length?"Needs Attention":"Complete",issues:[...new Map(issues.map(issue=>[`${issue.code}:${issue.value}`,issue])).values()]};}
