const groups = [
  ["高度递增", ["Treinta centímetros. Nada. Cincuenta. Ya se rompió. Ahora vamos a subir a ochenta.", "Veinte centímetros. Cuarenta. Sesenta. Este protector no llegó ni al último nivel.", "Primera altura. Segunda altura. Tercera altura. La pantalla ya está pidiendo ayuda.", "Empezamos bajo. Ahora medio metro. Y esto todavía no es la prueba fuerte.", "Treinta, cincuenta, ochenta. Si falla aquí, no merece estar en tu móvil."]],
  ["重量加压", ["Un kilo. Dos kilos. Cuatro kilos. Mira cuál se rinde primero.", "Primero una botella llena. Ahora dos. El protector ya está cediendo.", "Poco peso. Más peso. Todo el peso. Así se descubre una protección falsa.", "Esto pesa de verdad. Lo coloco encima y no voy a cortar el vídeo.", "Una pesa, dos pesas, tres pesas. El último resultado cambia todo."]],
  ["斧头威力", ["Un hacha de verdad. Mira primero lo que le hace a esta madera.", "Este es mi nuevo juguete. Corta madera. Ahora vamos a llevarlo al móvil.", "Madera contra hacha. Ahora protector contra la misma hacha.", "No es de plástico. No está trucada. Y la prueba será exactamente la misma.", "Si puede abrir esto de un golpe, imagina lo que hará con un protector normal."]],
  ["锤击升级", ["Un golpe suave. Otro más fuerte. El tercero rompe el protector normal.", "Martillo pequeño. Martillo grande. Misma pantalla, resultado muy distinto.", "Primero desde aquí. Ahora más arriba. El protector normal no aguanta otra.", "No voy a cambiar de martillo. Solo voy a cambiar el protector.", "Este golpe no parece fuerte hasta que ves cómo queda el cristal normal."]],
  ["胶带附着", ["Mira la fuerza de esta cinta. La botella está llena, no vacía.", "Esta cinta levanta una botella completa. Ahora mira lo que hace con cada protector.", "Cinta nueva. Botella llena. Protector sin capa oleofóbica: se queda pegado.", "Primera cinta. Segunda cinta. El mismo protector vuelve a quedarse pegado.", "La cinta sigue pegando. El problema no es la cinta; es la superficie."]],
  ["液体竞速", ["Una gota aquí. Otra aquí. Solo una se desliza sin dejar rastro.", "Agua, café y aceite. Tres líquidos, cuatro superficies.", "Inclino las pantallas al mismo tiempo. Mira cuál se limpia sola.", "No voy a secarlo. Quiero que veas dónde se queda atrapada el agua.", "Misma cantidad de agua. Mismo ángulo. Resultados completamente distintos."]],
  ["油污指纹", ["Un dedo limpio. Un dedo con aceite. Mira qué pantalla queda marcada.", "Una pasada, dos pasadas, diez huellas. Esta ya no se puede ni mirar.", "Pongo la misma cantidad de aceite en las dos. Solo una queda limpia.", "Toca, arrastra y mira la marca. Eso pasa cada vez que usas el móvil.", "No es suciedad vieja. Acabo de limpiar ambas pantallas delante de ti."]],
  ["刀片刮擦", ["Primero una llave. Después una cuchilla. Al final usaré el taladro.", "Escucha este sonido. La cuchilla ya está marcando el protector normal.", "Una raya horizontal. Otra vertical. El cristal normal no pasó la primera fase.", "Misma cuchilla, misma presión. Solo voy a cambiar la superficie.", "Si llevas llaves en el bolso, esta prueba te interesa más de lo que crees."]],
  ["钥匙包内", ["Llaves, monedas y cremallera. Esto vive junto a tu móvil cada día.", "Metí el teléfono en el bolso durante una hora. Mira cómo salió la pantalla.", "No hace falta un martillo. Tus propias llaves ya hacen este daño.", "Agito el bolso diez segundos. El protector normal sale completamente marcado.", "Esto no es una prueba de laboratorio. Es exactamente lo que pasa en tu bolso."]],
  ["灰尘消失", ["Voy a echar polvo a propósito. Sí, directamente sobre la pantalla.", "Polvo aquí, polvo aquí, mucho polvo. Ahora observa dónde termina.", "No voy a limpiar esta partícula. Quiero ver si el aplicador la elimina.", "Esta pantalla está llena de polvo. La voy a instalar así, sin trucos.", "Una mota basta para arruinar un protector normal. Hoy voy a usar muchas."]],
  ["气泡翻车", ["Una burbuja. Dos burbujas. Y esta esquina ni siquiera está alineada.", "Diez minutos instalando esto y todavía parece un desastre.", "Levanto, recoloco, vuelvo a presionar. Cada intento deja más polvo.", "Este es el resultado cuando intentas alinear el protector con los dedos.", "Polvo, burbujas, desalineación. Los tres problemas en una sola instalación."]],
  ["十秒挑战", ["Diez segundos. Si queda una burbuja, pierdo el reto.", "Pon el cronómetro. No voy a cortar ni repetir la instalación.", "Tres pasos, diez segundos y una sola oportunidad.", "El tiempo empieza ahora. Colocar, deslizar y retirar.", "¿Se puede instalar perfecto antes de que termine esta cuenta atrás? Vamos."]],
  ["竞品淘汰", ["Vidrio normal. Hidrogel. Cerámica. Ninguno llegó al final.", "Protector barato. Protector mate. Imitación. Los tres fallaron de forma distinta.", "Uno se raya. Otro se rompe. El tercero queda lleno de burbujas.", "Tres protectores, tres promesas y el mismo resultado: dinero perdido.", "Voy a eliminar uno por uno hasta que solo quede el que realmente protege."]],
  ["真假对决", ["Magic John falso. Protector sin marca. Copia barata. Vamos a comprobarlo.", "Se ven iguales en la caja. La diferencia aparece cuando empieza la prueba.", "Original a la derecha. Imitación a la izquierda. Misma herramienta.", "Este cuesta menos. Pero mira cuánto puede costarte después.", "No mires el envase. Mira lo que pasa cuando los dos reciben el mismo golpe."]],
  ["重复洗脑", ["Papel. Papel. Papel. Tres protectores que solo gastan tu dinero.", "Raya. Burbuja. Polvo. Raya, burbuja, polvo. Basta ya.", "Uno roto. Otro roto. Otro roto. Necesitamos algo diferente.", "Dinero aquí. Dinero aquí. Dinero aquí. Todo directo a la basura.", "Protector normal. Protector mate. Protector barato. Ninguno sirve para esta prueba."]],
  ["公共防窥", ["Me siento a tu lado y puedo leer cada mensaje de tu pantalla.", "Mira de frente. Ahora desde un lado. Tu secreto ya no es secreto.", "Metro lleno, pantalla encendida y la persona de al lado viendo todo.", "Pongo el mismo mensaje en dos móviles. Desde aquí solo uno desaparece.", "Veintiocho grados a la izquierda. Veintiocho a la derecha. Mira quién puede leerlo."]],
  ["触控顺滑", ["Mismo juego, mismo dedo. Una pantalla se frena y la otra vuela.", "Deslizo una vez. La huella se queda. En la otra, nada.", "Voy a escribir la misma palabra en las dos pantallas al mismo tiempo.", "Un protector puede proteger y aun así arruinar el tacto. Mira esto.", "Movimiento lento. Movimiento rápido. Solo una superficie sigue el dedo."]],
  ["一镜到底", ["Una toma. Sin cortes. Desde la caja hasta la prueba final.", "No voy a esconder ningún paso. Todo ocurre delante de la cámara.", "Mira mis dos manos. No hay cambio de móvil ni cambio de protector.", "Empiezo con la pantalla sucia y termino con el golpe, todo en el mismo plano.", "Si crees que está editado, no apartes la vista: esta vez no habrá cortes."]],
  ["导演玩具", ["Este es el nuevo juguete de mi amigo director. Nadie adivinó para qué sirve.", "Hoy apareció esto en el estudio. Primero lo probamos con cartón.", "Mi director dijo que no acercara esto al móvil. Obviamente lo hice.", "No sé quién trajo esta herramienta al rodaje, pero vamos a probarla.", "Parece un accesorio de cine. En un momento entenderás por qué está junto al teléfono."]],
  ["分屏反转", ["A la izquierda, diez minutos y un desastre. A la derecha, diez segundos.", "Misma pantalla dividida en dos. Un lado atrapa polvo; el otro queda limpio.", "Dos manos, dos métodos y una diferencia imposible de ignorar.", "Antes y después en la misma toma. No hace falta explicar cuál ganó.", "Un protector se levanta en las esquinas. El otro ni siquiera se mueve."]],
] as const;

export const seedHooks = groups.flatMap(([group, copies], groupIndex) => copies.map((copy, index) => ({
  id: 10001 + groupIndex * 5 + index,
  title: `${group} ${index + 1}`,
  language: "西班牙语",
  copy,
})));
