"use client";
import {useEffect,useMemo,useState} from "react";
import type {ActiveView} from "./navigation";
import type {DemoProject} from "./demo-data";
type ProjectInput={name:string;product:string;market:string;platform:string;language:string};
type Props={projects:DemoProject[];initialProjectKey?:string|null;saveState:"saved"|"saving";onNavigate:(view:ActiveView)=>void;onSelect:(id:string)=>void;onCreate:(input:ProjectInput)=>void;onRename:(id:string,name:string)=>void;onDuplicate:(id:string)=>void;onDelete:(id:string)=>void};
const flow:Array<{key:keyof DemoProject["assets"];label:string;view:ActiveView;icon:string}>=[
 {key:"analysis",label:"爆款研究",view:"breakdown",icon:"◇"},{key:"replication",label:"创意复刻",view:"replicate",icon:"◎"},{key:"scripts",label:"AI 脚本",view:"create",icon:"✦"},{key:"director",label:"AI 导演",view:"director",icon:"◉"},{key:"voice",label:"AI 配音",view:"voice",icon:"♫"},{key:"reviews",label:"成片生成（未来）",view:"reviews",icon:"▥"},
];
const initialDraft:ProjectInput={name:"",product:"",market:"西班牙",platform:"TikTok",language:"西班牙语"};
const time=(value?:string)=>value?new Date(value).toLocaleString("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}):"暂无";
const assetCount=(project:DemoProject)=>Object.values(project.assets).reduce((sum,value)=>sum+value,0);
export default function ProjectWorkspace({projects,initialProjectKey,saveState,onNavigate,onSelect,onCreate,onRename,onDuplicate,onDelete}:Props){
 const [selectedKey,setSelectedKey]=useState<string|null>(initialProjectKey||null);const [query,setQuery]=useState("");const [filter,setFilter]=useState("全部项目");const [dialog,setDialog]=useState<"create"|"rename"|"delete"|null>(null);const [draft,setDraft]=useState<ProjectInput>(initialDraft);const [rename,setRename]=useState("");
 useEffect(()=>setSelectedKey(initialProjectKey||null),[initialProjectKey]);
 const selected=projects.find(item=>item.key===selectedKey)||null;
 const visible=useMemo(()=>projects.filter(item=>{const matches=!query.trim()||`${item.projectName}${item.product}${item.market}${item.platform}`.toLowerCase().includes(query.trim().toLowerCase());return matches&&(filter==="全部项目"||item.status===filter)}),[projects,query,filter]);
 const choose=(id:string)=>{setSelectedKey(id);onSelect(id)};const close=()=>setDialog(null);
 const modal=dialog&&<div className="project-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="project-dialog-title"><header><div><span>PROJECT ACTION</span><h3 id="project-dialog-title">{dialog==="create"?"新建项目":dialog==="rename"?"重命名项目":"删除项目"}</h3></div><button type="button" aria-label="关闭" onClick={close}>×</button></header>{dialog==="create"?<form onSubmit={event=>{event.preventDefault();onCreate(draft);setDraft(initialDraft);close()}}><label>项目名称<input autoFocus required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="CrystalArmor Spain TikTok"/></label><label>产品名称<input required value={draft.product} onChange={e=>setDraft({...draft,product:e.target.value})} placeholder="CrystalArmor"/></label><div><label>市场<input required value={draft.market} onChange={e=>setDraft({...draft,market:e.target.value})}/></label><label>平台<select value={draft.platform} onChange={e=>setDraft({...draft,platform:e.target.value})}><option>TikTok</option><option>Reels</option><option>YouTube Shorts</option></select></label></div><label>输出语言<input required value={draft.language} onChange={e=>setDraft({...draft,language:e.target.value})}/></label><footer><button type="button" onClick={close}>取消</button><button type="submit">创建并进入</button></footer></form>:dialog==="rename"?<form onSubmit={event=>{event.preventDefault();if(selected&&rename.trim())onRename(selected.key,rename);close()}}><label>项目名称<input autoFocus required value={rename} onChange={e=>setRename(e.target.value)}/></label><footer><button type="button" onClick={close}>取消</button><button type="submit">保存名称</button></footer></form>:<div className="project-delete-confirm"><p>确定删除「{selected?.projectName}」吗？项目及其关联资产将从当前项目记忆中移除，此操作无法撤销。</p><footer><button type="button" onClick={close}>取消</button><button className="danger" type="button" onClick={()=>{if(selected)onDelete(selected.key);close()}}>确认删除</button></footer></div>}</section></div>;
 if(selected){const total=assetCount(selected);return <section className="project-detail">{modal}<div className="project-detail-top"><button className="project-back" type="button" onClick={()=>setSelectedKey(null)}>← 返回我的项目</button><span className={`project-save-state ${saveState}`}>{saveState==="saving"?"正在保存...":"✓ 已保存"}</span></div><header className="project-detail-hero"><div className="project-logo">{selected.product.slice(0,1)}</div><div><span>{selected.market} · AI CREATIVE PIPELINE</span><h2>{selected.projectName}</h2><p>{selected.product} · {selected.platform} · {selected.language}</p></div><div className="project-detail-actions"><small>最近更新 {time(selected.updatedAt)}</small><button type="button" onClick={()=>onNavigate(flow.find(x=>x.label.includes(selected.stage))?.view||"create")}>继续创作 <i>→</i></button></div></header><section className="project-progress"><header><div><span>AI Creative Pipeline</span><strong>{selected.progress}%</strong></div><p>当前阶段：<b>{selected.stage}</b> · 共 {total} 项资产</p></header><div><i style={{width:`${selected.progress}%`}}/></div></section><div className="project-detail-grid"><main><section className="project-section-head"><div><span>PRODUCTION WORKSPACE</span><h3>完整创意生产流程</h3></div><p>现有资产统一挂载到当前项目</p></section><div className="project-flow-grid">{flow.map((item,index)=>{const count=selected.assets[item.key];const current=item.label.includes(selected.stage);const previousDone=flow.slice(0,index).every(step=>selected.assets[step.key]>0);const state=count>0?"已完成":current||previousDone?"进行中":"未开始";return <button type="button" key={item.key} className={current?"current":""} onClick={()=>onNavigate(item.view)}><span>{item.icon}</span><div><small>STEP {index+1}</small><h4>{item.label}</h4><p>{count?`${count} 项项目资产`:item.key==="reviews"?"规划中":"尚无资产"}</p></div><em data-state={state}>{state}</em><i>→</i></button>})}</div></main><aside><section><span>项目信息</span><h3>{selected.product}</h3><dl><div><dt>目标市场</dt><dd>{selected.market}</dd></div><div><dt>发布平台</dt><dd>{selected.platform}</dd></div><div><dt>输出语言</dt><dd>{selected.language}</dd></div><div><dt>创建时间</dt><dd>{time(selected.createdAt)}</dd></div></dl></section><section><span>项目操作</span><div className="project-action-list"><button type="button" onClick={()=>{setRename(selected.projectName);setDialog("rename")}}>重命名项目</button><button type="button" onClick={()=>onDuplicate(selected.key)}>复制项目</button><button className="danger" type="button" onClick={()=>setDialog("delete")}>删除项目</button></div></section><section><span>资产目录</span><p>Analyzer · {selected.assets.analysis}</p><p>Replication · {selected.assets.replication}</p><p>Scripts · {selected.assets.scripts}</p><p>Director · {selected.assets.director}</p><p>Voice · {selected.assets.voice}</p><p>Future Assets · {selected.assets.reviews}</p></section></aside></div></section>}
 return <section className="projects-page">{modal}<header><div><span>PROJECT WORKSPACE</span><h2>我的项目</h2><p>以项目为中心管理短视频 AI 创意生产全流程。</p></div><div className="projects-head-actions"><span className={`project-save-state ${saveState}`}>{saveState==="saving"?"正在保存...":"✓ 已保存"}</span><button type="button" onClick={()=>setDialog("create")}><b>＋</b> 新建项目</button></div></header><section className="projects-toolbar"><div>{["全部项目","创作中","待审核","已完成"].map(item=><button type="button" className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}{item==="全部项目"&&<em>{projects.length}</em>}</button>)}</div><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索项目、产品、市场…"/></label></section><div className="project-card-grid">{visible.map(item=><article key={item.key} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter")choose(item.key)}} onClick={()=>choose(item.key)}><header><div className="project-logo">{item.product.slice(0,1)}</div><span className={`project-status status-${item.status}`}>{item.status}</span></header><h3>{item.projectName}</h3><p>{item.product}</p><div className="project-tags"><span>{item.market}</span><span>{item.platform}</span><span>{item.language}</span></div><section><div><span>当前阶段</span><b>{item.stage}</b></div><div><span>项目资产</span><b>{assetCount(item)}</b></div><aside><i style={{width:`${item.progress}%`}}/></aside></section><div className="project-dates"><span>创建 {time(item.createdAt)}</span><span>更新 {time(item.updatedAt)}</span></div><footer><div><small>负责人 · {item.owner}</small></div><button type="button" onClick={e=>{e.stopPropagation();choose(item.key)}}>进入工作区 <i>→</i></button></footer></article>)}</div>{!visible.length&&<div className="projects-empty"><span>▤</span><h3>{projects.length?"没有找到匹配项目":"还没有项目"}</h3><p>{projects.length?"换一个关键词或筛选条件试试。":"创建第一个项目，开始完整创意生产流程。"}</p>{!projects.length&&<button type="button" onClick={()=>setDialog("create")}>新建项目</button>}</div>}</section>
}
