"use client";
import {useMemo,useRef,useState} from "react";
import {cameraAngleValues,cameraMovementValues,directorContextId,framingValues,scriptBlocks,type DirectorRequest,type DirectorResult,type DirectorShot} from "./director-core";
import {autoRebalance,checkDirectorIntegrity,createDirectorVersion,deleteShot,duplicateShot,insertShot,plannedDuration,recalculateTimeline,reorderShots,workspaceShots,type DirectorVersion,type WorkspaceShot} from "./director-workspace";

type Props={input:DirectorRequest|null;onNavigate?:(view:"create"|"history"|"replicate")=>void};
type RewritePreview={index:number;before:WorkspaceShot;after:WorkspaceShot;metadata:{providerUsed:string;fallbackUsed:boolean;factGuardPassed:boolean}};
const presets=["更有视觉冲击","更 TikTok 原生","更容易拍","更强 Proof","更自然 KOC","换景别","换场景","自定义要求"];
const editable:Array<[keyof WorkspaceShot,string,"text"|"textarea"|"number"|"framing"|"angle"|"movement"]>=[
 ["duration","Duration","number"],["framing","Framing","framing"],["cameraAngle","Camera Angle","angle"],["cameraMovement","Camera Movement","movement"],["visualDescription","Visual Description","textarea"],["talentAction","Talent Action","textarea"],["productAction","Product Action","textarea"],["dialogue","Dialogue","textarea"],["voiceover","Voiceover","textarea"],["onScreenText","On-screen Text","textarea"],["props","Props（；分隔）","text"],["environment","Environment","text"],["proofRequirement","Proof Requirement","textarea"],["transition","Transition","text"],["editingNotes","Editing Notes","textarea"],["audioSfx","Audio / SFX","text"]
];
const emptyFrom=(basis:WorkspaceShot):WorkspaceShot=>({...basis,shotId:"manual",sourceBlockId:`manual:${Date.now().toString(36)}`,stage:"BODY",purpose:"Transition / Support",shotType:"Action Shot",visualDescription:"",productAction:"",talentAction:"",dialogue:"",voiceover:"",onScreenText:"",proofRequirement:"",duration:1.5,props:[],locked:false,status:"Draft"});

function ShotCard({shot,selected,onSelect,onToggleLock,onDuplicate,onDelete,onRegenerate,onDragStart,onDrop}:{shot:WorkspaceShot;selected:boolean;onSelect:()=>void;onToggleLock:()=>void;onDuplicate:()=>void;onDelete:()=>void;onRegenerate:()=>void;onDragStart:()=>void;onDrop:()=>void}){
 const [expanded,setExpanded]=useState(false);
 return <article id={`director-${shot.shotId}`} className={`director-shot-card workspace ${selected?"selected":""}`} draggable onDragStart={onDragStart} onDragOver={event=>event.preventDefault()} onDrop={onDrop}>
  <header><button className="shot-drag" aria-label="拖动排序">⠿</button><div onClick={onSelect}><b>SHOT {String(shot.order).padStart(2,"0")} · {shot.stage} · {shot.duration.toFixed(1)}s</b><span>{shot.startTime.toFixed(1)}–{shot.endTime.toFixed(1)}s · {shot.status}</span></div><nav><button onClick={onToggleLock} aria-label={shot.locked?"解锁镜头":"锁定镜头"}>{shot.locked?"🔒":"🔓"}</button><button onClick={onSelect}>Edit</button><details><summary>⋯</summary><menu><button onClick={onRegenerate}>AI 重生成</button><button onClick={onDuplicate}>复制</button><button className="danger" onClick={onDelete}>删除</button></menu></details></nav></header>
  <section className="director-visual" onClick={onSelect}><small>画面 · DIRECTOR RECOMMENDATION</small><p>{shot.visualDescription||"尚未填写可执行画面"}</p></section>
  <div className="shot-essentials"><article><b>动作</b><p><strong>模特</strong> {shot.talentAction||"—"}</p><p><strong>产品</strong> {shot.productAction||"—"}</p></article><article><b>口播</b><p>{shot.dialogue||shot.voiceover||"—"}</p>{shot.onScreenText?<small>字幕：{shot.onScreenText}</small>:null}</article><article><b>Proof</b><p>{shot.proofRequirement||"—"}</p></article><article><b>Director Note</b><p>{shot.editingNotes||shot.purpose||"—"}</p></article></div>
  <div className="director-shot-tags"><span>{shot.framing}</span><span>{shot.cameraAngle}</span><span>{shot.cameraMovement}</span><span>{shot.sourceBlockId}</span></div>
  <button className="shot-expand" onClick={()=>setExpanded(value=>!value)}>{expanded?"收起 Camera / Props / Editing / Continuity":"展开 Camera / Props / Editing / Continuity"}</button>
  {expanded?<dl className="director-shot-grid"><div><dt>Product Action</dt><dd>{shot.productAction||"—"}</dd></div><div><dt>On-screen Text</dt><dd>{shot.onScreenText||"—"}</dd></div><div><dt>Props / Environment</dt><dd>{shot.props.join("、")||"—"}<br/>{shot.environment}</dd></div><div><dt>Transition / Edit</dt><dd>{shot.transition}<br/>{shot.editingNotes}</dd></div><div><dt>Audio / SFX</dt><dd>{shot.audioSfx||"—"}</dd></div><div><dt>Continuity</dt><dd>{shot.continuityNotes||"—"}</dd></div></dl>:null}
 </article>;
}

export default function ShootingDirector({input,onNavigate}:Props){
 const [talent,setTalent]=useState("单人手模 / KOC"),[environment,setEnvironment]=useState("同一张整洁桌面"),[result,setResult]=useState<DirectorResult|null>(null),[shots,setShots]=useState<WorkspaceShot[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<number|null>(null),[preset,setPreset]=useState(presets[0]),[instruction,setInstruction]=useState(""),[preview,setPreview]=useState<RewritePreview|null>(null),[undo,setUndo]=useState<{index:number;shot:WorkspaceShot}|null>(null),[versions,setVersions]=useState<DirectorVersion[]>([]),[listStatus,setListStatus]=useState<"Draft"|"Confirmed">("Draft"),[rebalance,setRebalance]=useState<{beforePlanned:number;afterPlanned:number;target:number;delta:number}|null>(null),[showArchived,setShowArchived]=useState(false);
 const dragged=useRef<number|null>(null),currentContextId=input?directorContextId(input):"",target=input?.context.targetDuration||30,planned=plannedDuration(shots),delta=Math.round((planned-target)*10)/10,contextChanged=Boolean(result&&result.metadata.contextId!==currentContextId);
 const sourceIds=useMemo(()=>input?scriptBlocks(input.script).map(block=>block.id):[],[input]);
 const contextMessages=useMemo(()=>result?.metadata.contextIntegrity.issues.map(issue=>`${issue.message}${issue.value?`：${issue.value}`:""}`)||[],[result]);
 const integrity=useMemo(()=>checkDirectorIntegrity(shots,target,input?.context.sellingPoints||"",sourceIds,contextMessages),[shots,target,input?.context.sellingPoints,sourceIds,contextMessages]);
 const props=useMemo(()=>[...new Set(shots.flatMap(x=>x.props))],[shots]);
 function commit(next:WorkspaceShot[]){setShots(recalculateTimeline(next.map(x=>({...x,status:"Draft"}))));setListStatus("Draft");setRebalance(null);}
 async function generate(){if(!input||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,action:"generate",settings:{...input.settings,talent,environment,provider:"deepseek"}})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Director生成失败");if(result&&contextChanged){const archived=createDirectorVersion(versions,result.metadata.contextId,result.directorPlan,shots,listStatus);setVersions(value=>[...value,archived]);}setResult(data);setShots(workspaceShots(data.shots));setSelected(null);setPreview(null);setShowArchived(false);setListStatus("Draft");}catch(e){setError(e instanceof Error?e.message:"Director生成失败");}finally{setBusy(false);}}
 async function requestCandidate(index:number,action:"regenerate-shot"|"suggest-shot"){if(!input||!result||busy||contextChanged)return null;const current=shots[index];if(action==="regenerate-shot"&&current.locked&&!window.confirm("当前镜头已锁定。确认主动重生成这个镜头？"))return null;setBusy(true);setError("");try{const block=scriptBlocks(input.script).find(x=>x.id===current.sourceBlockId);const response=await fetch("/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,action,contextId:result.metadata.contextId,currentShot:current,previousShot:shots[index-1],nextShot:shots[index+1],directorPlan:result.directorPlan,sourceBlock:block,preset,instruction})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Shot重生成失败");return{...data.candidate,locked:false,status:"Draft",metadata:data.metadata};}catch(e){setError(e instanceof Error?e.message:"Shot重生成失败");return null;}finally{setBusy(false);}}
 async function regenerate(index:number){const candidate=await requestCandidate(index,"regenerate-shot");if(candidate)setPreview({index,before:structuredClone(shots[index]),after:candidate,metadata:candidate.metadata});}
 async function suggest(index:number){const candidate=await requestCandidate(index,"suggest-shot");if(candidate){const {metadata:_,...shot}=candidate;void _;commit(insertShot(shots,index,shot));setSelected(index+1);}}
 async function rebuildUnlocked(){if(!input||!result||busy||contextChanged)return;const indexes=shots.map((shot,index)=>shot.locked?-1:index).filter(index=>index>=0);setBusy(true);setError("");try{const blocks=scriptBlocks(input.script);const candidates=await Promise.all(indexes.map(async index=>{const response=await fetch("/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,action:"regenerate-shot",contextId:result.metadata.contextId,currentShot:shots[index],previousShot:shots[index-1],nextShot:shots[index+1],directorPlan:result.directorPlan,sourceBlock:blocks.find(x=>x.id===shots[index].sourceBlockId),preset:"保持上下镜头连续，重做未锁定镜头",instruction})});if(!response.ok)return null;return(response.json() as Promise<{candidate:DirectorShot}>);}));const next=shots.map((shot,index)=>{const position=indexes.indexOf(index),data=position>=0?candidates[position]:null;return data?{...data.candidate,locked:false,status:"Draft" as const}:shot;});commit(next);}catch{setError("部分镜头重做失败，当前 Director 已保留");}finally{setBusy(false);}}
 function acceptPreview(){if(!preview)return;setUndo({index:preview.index,shot:preview.before});commit(shots.map((shot,index)=>index===preview.index?{...preview.after,locked:shot.locked,status:"Draft"}:shot));setPreview(null);}
 function updateShot(index:number,key:keyof WorkspaceShot,value:string|number|string[]){commit(shots.map((shot,i)=>i===index?{...shot,[key]:value}:shot));}
 function remove(index:number){if(window.confirm(`删除 SHOT ${String(index+1).padStart(2,"0")}？删除后不会自动恢复缺失的 Hook / Proof / CTA。`)){commit(deleteShot(shots,index));setSelected(null);}}
 function addManual(index:number){const basis=shots[index]||shots.at(-1);if(!basis)return;commit(insertShot(shots,index,emptyFrom(basis)));setSelected(index+1);}
 function doRebalance(){const summary=autoRebalance(shots,target);commit(summary.shots);setRebalance(summary);}
 function saveVersion(){if(!result)return;const version=createDirectorVersion(versions,result.metadata.contextId,result.directorPlan,shots,listStatus);setVersions(value=>[...value,version]);}
 function confirmList(){setShots(value=>value.map(shot=>({...shot,status:"Confirmed"})));setListStatus("Confirmed");}
 function scrollToShot(index:number){setSelected(index);document.getElementById(`director-${shots[index].shotId}`)?.scrollIntoView({behavior:"smooth",block:"center"});}
 if(result&&contextChanged)return <section className="director-studio director-workspace"><header><div><p className="eyebrow">AI DIRECTOR · CONTEXT INTEGRITY</p><h1>检测到当前脚本已变化</h1><p>旧 Director Workspace 已隔离，不会作为当前脚本的 Shots 继续编辑。</p></div><div className="status needs"><i/> CONTEXT CHANGED</div></header><div className="context-change-gate"><div><span>CURRENT SCRIPT</span><h2>{input?.script.title||"当前脚本"}</h2><p>Context ID：{currentContextId}</p></div><div><span>EXISTING DIRECTOR</span><h2>{result.directorPlan.creativeIntent}</h2><p>Context ID：{result.metadata.contextId}</p></div><footer><button className="primary" disabled={busy} onClick={generate}>{busy?"正在生成…":"为当前脚本生成新的 Director"}</button><button onClick={()=>setShowArchived(value=>!value)}>{showArchived?"收起旧 Director":"返回旧 Director（只读）"}</button></footer></div>{showArchived?<section className="archived-director"><header><b>旧 Director · 只读</b><span>{shots.length} Shots · {plannedDuration(shots)}s</span></header>{shots.map(shot=><article key={shot.shotId}><b>SHOT {String(shot.order).padStart(2,"0")} · {shot.stage}</b><p>{shot.visualDescription}</p><small>{shot.sourceBlockId}</small></article>)}</section>:null}{error?<p className="director-error">{error}</p>:null}</section>;
 return <section className="director-studio director-workspace"><header><div><p className="eyebrow">AI DIRECTOR · SHOT WORKSPACE</p><h1>导演分镜工作台</h1><p>Director Plan → Edit / Lock / Regenerate / Reorder → Confirmed Shot List</p></div><div className="status"><i/> {listStatus.toUpperCase()} · DIRECTOR RECOMMENDATION</div></header>
  {!result?<div className="director-layout"><aside className="director-form"><span className="modal-kicker">DIRECTOR INPUT</span><h2>{input?.script.title||"等待采用脚本"}</h2>{input?<><dl className="director-input-summary"><div><dt>产品</dt><dd>{input.context.product}</dd></div><div><dt>来源</dt><dd>{input.context.sourceType}</dd></div><div><dt>Hook</dt><dd>{input.context.hookStrategy}</dd></div><div><dt>时长</dt><dd>{target}s</dd></div></dl><section className="director-script-source"><b>Product Knowledge</b><p>{input.context.productKnowledge?"Ready":"Creative Brief fallback"}</p></section><label>模特配置<input value={talent} onChange={e=>setTalent(e.target.value)}/></label><label>主拍摄环境<input value={environment} onChange={e=>setEnvironment(e.target.value)}/></label><button className="director-generate" disabled={busy} onClick={generate}>{busy?"正在生成 Director Plan + Shot List…":"✦ 生成可执行 Shot List"}</button>{error?<p className="director-error">{error}</p>:null}</>:<div className="director-no-input"><b>还没有 Current Script</b><p>先从现有脚本入口选择一条采用稿，再进入 Director。</p><div className="director-empty-actions"><button onClick={()=>onNavigate?.("create")}>从 Script Studio 选择</button><button onClick={()=>onNavigate?.("history")}>从历史脚本选择</button><button onClick={()=>onNavigate?.("replicate")}>从 Viral Replication 选择</button></div></div>}</aside><main className="director-output"><div className="director-empty"><span>🎬</span><h2>{busy?"正在规划镜头与时长":"等待生成导演方案"}</h2><p>Step 5.1 Engine 将生成可编辑的结构化工作区；AI失败会明确显示 SAFE FALLBACK。</p></div></main></div>:<>
   <div className="workspace-topbar"><div><span>{input?.script.title}</span><b>{listStatus} · {integrity.status}</b></div><section><article><small>Target</small><strong>{target}s</strong></article><article><small>Planned</small><strong>{planned}s</strong></article><article className={Math.abs(delta)>.5?"warn":""}><small>Delta</small><strong>{delta>0?"+":""}{delta}s</strong></article><article><small>Shots</small><strong>{shots.length}</strong></article><article><small>Complexity</small><strong>{result.directorPlan.shootingComplexity}</strong></article><article><small>Provider</small><strong>{result.metadata.providerUsed}</strong></article></section><nav><button onClick={doRebalance}>重新平衡时长</button><button onClick={saveVersion}>保存 Director Version</button><button className="primary" onClick={confirmList}>确认导演分镜</button></nav></div>
   <div className="workspace-shell"><aside className="plan-sidebar"><span>DIRECTOR PLAN</span><h2>{result.directorPlan.creativeIntent}</h2>{[["Hook Execution",result.directorPlan.hookExecution],["Pacing",result.directorPlan.pacingStrategy],["Proof Strategy",result.directorPlan.proofStrategy],["Product Reveal",result.directorPlan.productRevealStrategy],["CTA",result.directorPlan.ctaExecution]].map(([label,value])=><details key={label}><summary>{label}</summary><p>{value}</p></details>)}<details><summary>Production Requirements</summary><p>Talent: {result.directorPlan.requiredTalent.join("、")}</p><p>Props: {props.join("、")}</p><p>Locations: {result.directorPlan.requiredLocations.join("、")}</p></details><article className={integrity.status==="Complete"?"integrity-ok":"integrity-warn"}><b>Context Integrity · {integrity.status}</b>{integrity.issues.length?integrity.issues.map((issue,index)=><p key={`${issue.code}-${index}`}>• {issue.message}</p>):<p>当前 Script、Product、Source Blocks、Duration 与 Timeline 均一致。</p>}</article>{versions.length?<article><b>Versions</b>{versions.map(version=><p key={version.id}>{version.label} · {version.status}</p>)}</article>:null}</aside>
    <main className="shot-workspace"><div className="workspace-actions"><div><b>{shots.filter(x=>x.locked).length} Locked</b><span>锁定镜头是 HARD CONSTRAINT</span></div><button disabled={busy} onClick={rebuildUnlocked}>{busy?"AI 正在处理…":"✦ AI 重做未锁定镜头"}</button>{undo?<button onClick={()=>{commit(shots.map((shot,index)=>index===undo.index?undo.shot:shot));setUndo(null);}}>Undo 最近 Rewrite</button>:null}</div>{error?<p className="director-error">{error}</p>:null}
     <div className="director-shot-list">{shots.map((shot,index)=><div className="shot-row" key={shot.shotId}><ShotCard shot={shot} selected={selected===index} onSelect={()=>setSelected(index)} onToggleLock={()=>setShots(value=>value.map((item,i)=>i===index?{...item,locked:!item.locked}:item))} onDuplicate={()=>commit(duplicateShot(shots,index))} onDelete={()=>remove(index)} onRegenerate={()=>regenerate(index)} onDragStart={()=>{dragged.current=index;}} onDrop={()=>{if(dragged.current!==null){commit(reorderShots(shots,dragged.current,index));dragged.current=null;}}}/><div className="add-shot"><button onClick={()=>addManual(index)}>＋ Manual Empty Shot</button><button disabled={busy} onClick={()=>suggest(index)}>✦ AI Suggested Shot</button></div></div>)}</div>
    </main>
    <aside className="shot-inspector">{selected===null||!shots[selected]?<div className="inspector-empty"><b>SHOT INSPECTOR</b><h3>选择一个镜头进行编辑</h3><dl><div><dt>Shots</dt><dd>{shots.length}</dd></div><div><dt>Duration</dt><dd>{planned}s / {target}s</dd></div><div><dt>Locked</dt><dd>{shots.filter(shot=>shot.locked).length}</dd></div><div><dt>Draft</dt><dd>{shots.filter(shot=>shot.status==="Draft").length}</dd></div><div><dt>Integrity</dt><dd>{integrity.status}</dd></div></dl></div>:<><header><div><span>EDIT SHOT</span><h3>SHOT {String(selected+1).padStart(2,"0")}</h3></div><button onClick={()=>setSelected(null)}>×</button></header><nav className="inspector-actions"><button onClick={()=>setShots(value=>value.map((shot,index)=>index===selected?{...shot,locked:!shot.locked}:shot))}>{shots[selected].locked?"Unlock":"Lock"}</button><button onClick={()=>regenerate(selected)}>AI Regenerate</button><button onClick={()=>commit(duplicateShot(shots,selected))}>Duplicate</button><button className="danger" onClick={()=>remove(selected)}>Delete</button></nav><label className="inspector-status">Status<select value={shots[selected].status} onChange={event=>updateShot(selected,"status",event.target.value)}><option>Draft</option><option>Confirmed</option><option>Shot</option><option>Retake</option></select></label><div className="inspector-fields">{editable.map(([key,label,type])=><label key={key}>{label}{type==="framing"||type==="angle"||type==="movement"?<select value={String(shots[selected][key])} onChange={e=>updateShot(selected,key,e.target.value)}>{(type==="framing"?framingValues:type==="angle"?cameraAngleValues:cameraMovementValues).map(value=><option key={value}>{value}</option>)}</select>:type==="textarea"?<textarea value={String(shots[selected][key]||"")} onChange={e=>updateShot(selected,key,e.target.value)}/>:<input type={type} step={type==="number"?.1:undefined} value={Array.isArray(shots[selected][key])?(shots[selected][key] as string[]).join("；"):String(shots[selected][key]||"")} onChange={e=>updateShot(selected,key,key==="props"?e.target.value.split(/[；;]+/).filter(Boolean):type==="number"?Number(e.target.value):e.target.value)}/>}</label>)}</div><section className="ai-shot-panel"><b>User Instruction / AI Regenerate</b><select value={preset} onChange={e=>setPreset(e.target.value)}>{presets.map(value=><option key={value}>{value}</option>)}</select><textarea placeholder="可用中文输入要求；目标台词与字幕仍保持 Script Output Language。" value={instruction} onChange={e=>setInstruction(e.target.value)}/><button disabled={busy} onClick={()=>regenerate(selected)}>生成 Before / After</button></section></>}</aside>
   </div>
   <section className={`director-timeline ${integrity.status==="Needs Attention"?"needs-attention":""}`}><header><b>Timeline / Duration Bar</b><span>0s → {planned}s · Target {target}s</span></header><div>{shots.map((shot,index)=><button key={shot.shotId} style={{flexGrow:Math.max(.5,shot.duration)}} className={[selected===index?"selected":"",shot.locked?"locked":"",shot.status.toLowerCase(),integrity.status==="Needs Attention"?"attention":""].filter(Boolean).join(" ")} onClick={()=>scrollToShot(index)}><b>{String(index+1).padStart(2,"0")}</b><span>{shot.duration}s · {shot.stage}</span></button>)}</div>{rebalance?<p>Before {rebalance.beforePlanned}s → After {rebalance.afterPlanned}s · Target {rebalance.target}s · Delta {rebalance.delta}s</p>:null}</section>
   {preview?<div className="rewrite-modal"><div><header><div><span>AI SHOT REWRITE · BEFORE / AFTER</span><h2>SHOT {String(preview.index+1).padStart(2,"0")}</h2></div><button onClick={()=>setPreview(null)}>×</button></header><section><article><b>BEFORE</b><p>{preview.before.visualDescription}</p><small>{preview.before.framing} · {preview.before.cameraMovement}</small><p>{preview.before.proofRequirement}</p></article><article><b>AFTER</b><p>{preview.after.visualDescription}</p><small>{preview.after.framing} · {preview.after.cameraMovement}</small><p>{preview.after.proofRequirement}</p></article></section><footer><span>Provider {preview.metadata.providerUsed} · Fact Guard {preview.metadata.factGuardPassed?"Passed":"Review"} · Fallback {String(preview.metadata.fallbackUsed)}</span><button onClick={()=>setPreview(null)}>Reject</button><button className="primary" onClick={acceptPreview}>Accept</button></footer></div></div>:null}
  </>}</section>;
}
