"use client";
import {useMemo,useRef,useState} from "react";
import WorkspaceState from "./components/ui/workspace-state";
import ConfirmDialog from "./components/ui/confirm-dialog";
import {notifyWorkspace} from "./components/ui/workspace-feedback";
import {cameraAngleValues,cameraMovementValues,directorContextId,framingValues,scriptBlocks,type DirectorRequest,type DirectorResult,type DirectorShot} from "./director-core";
import {autoRebalance,checkDirectorIntegrity,createDirectorVersion,deleteShot,duplicateShot,insertShot,plannedDuration,recalculateTimeline,reorderShots,workspaceShots,type DirectorVersion,type WorkspaceShot} from "./director-workspace";

type Props={input:DirectorRequest|null;onNavigate?:(view:"create"|"history"|"replicate")=>void};
type RewritePreview={mode:"replace"|"insert";index:number;before:WorkspaceShot;after:WorkspaceShot;metadata:{providerUsed:string;fallbackUsed:boolean;factGuardPassed:boolean}};
const presets=["更有视觉冲击","更 TikTok 原生","更容易拍","更强 Proof","更自然 KOC","换景别","换场景","自定义要求"];
const editable:Array<[keyof WorkspaceShot,string,"text"|"textarea"|"number"|"framing"|"angle"|"movement"]>=[
 ["duration","时长","number"],["framing","景别","framing"],["cameraAngle","机位","angle"],["cameraMovement","运镜","movement"],["visualDescription","画面描述","textarea"],["talentAction","模特动作","textarea"],["productAction","产品动作","textarea"],["dialogue","现场台词","textarea"],["voiceover","口播","textarea"],["onScreenText","屏幕字幕","textarea"],["props","道具（；分隔）","text"],["environment","拍摄环境","text"],["proofRequirement","证明要求","textarea"],["transition","转场","text"],["editingNotes","剪辑备注","textarea"],["audioSfx","音效","text"]
];
const stageLabel=(value:string)=>({HOOK:"开场钩子",BODY:"正文",CONFLICT:"冲突",PROOF:"证明镜头",SELLING_POINT:"卖点",PRODUCT_REVEAL:"产品出场",CTA:"行动引导"}[value]||value.replaceAll("_"," "));
const statusLabel=(value:string)=>({Draft:"草稿",Confirmed:"已确认",Shot:"已拍摄",Retake:"重拍"}[value]||value);
const integrityLabel=(value:string)=>value==="Complete"?"完整":"需要处理";
const cameraLabel=(value:string)=>({"Extreme Close-Up":"超特写","Close-Up":"特写","Medium Close-Up":"中近景",Medium:"中景",Wide:"全景","Over-the-Shoulder":"越肩镜头","Top-Down":"俯拍","Product Macro":"产品微距","Eye Level":"平视","High Angle":"高机位","Low Angle":"低机位","Side Angle":"侧面机位","45 Degree":"45度机位",Static:"固定", "Push In":"推进","Pull Out":"拉远",Pan:"横摇",Tilt:"竖摇",Handheld:"手持",Tracking:"跟拍"}[value]||value);
const emptyFrom=(basis:WorkspaceShot):WorkspaceShot=>({...basis,shotId:"manual",sourceBlockId:`manual:${Date.now().toString(36)}`,stage:"BODY",purpose:"Transition / Support",shotType:"Action Shot",visualDescription:"",productAction:"",talentAction:"",dialogue:"",voiceover:"",onScreenText:"",proofRequirement:"",duration:1.5,props:[],locked:false,status:"Draft"});

function ShotCard({shot,selected,onSelect,onToggleLock,onDuplicate,onDelete,onRegenerate,onDragStart,onDrop}:{shot:WorkspaceShot;selected:boolean;onSelect:()=>void;onToggleLock:()=>void;onDuplicate:()=>void;onDelete:()=>void;onRegenerate:()=>void;onDragStart:()=>void;onDrop:()=>void}){
 const [expanded,setExpanded]=useState(false);
 return <article id={`director-${shot.shotId}`} className={`director-shot-card workspace ${selected?"selected":""}`} draggable onDragStart={onDragStart} onDragOver={event=>event.preventDefault()} onDrop={onDrop}>
  <header><button className="shot-drag" aria-label="拖动排序">⠿</button><div onClick={onSelect}><b>镜头 {String(shot.order).padStart(2,"0")} · {stageLabel(shot.stage)} · {shot.duration.toFixed(1)}秒</b><span>{shot.startTime.toFixed(1)}–{shot.endTime.toFixed(1)}秒 · {statusLabel(shot.status)}</span></div><nav><button onClick={onToggleLock} aria-label={shot.locked?"解锁镜头":"锁定镜头"}>{shot.locked?"🔒":"🔓"}</button><button onClick={onSelect}>编辑</button><details><summary>⋯</summary><menu><button onClick={onRegenerate}>AI 重新生成</button><button onClick={onDuplicate}>复制镜头</button><button className="danger" onClick={onDelete}>删除镜头</button></menu></details></nav></header>
  <section className="director-visual" onClick={onSelect}><small>画面 · 导演建议</small><p>{shot.visualDescription||"尚未填写可执行画面"}</p></section>
  <div className="shot-essentials"><article><b>动作</b><p><strong>模特</strong> {shot.talentAction||"—"}</p><p><strong>产品</strong> {shot.productAction||"—"}</p></article><article><b>口播</b><p>{shot.dialogue||shot.voiceover||"—"}</p>{shot.onScreenText?<small>字幕：{shot.onScreenText}</small>:null}</article><article><b>证明要求</b><p>{shot.proofRequirement||"—"}</p></article><article><b>导演备注</b><p>{shot.editingNotes||shot.purpose||"—"}</p></article></div>
  <div className="director-shot-tags"><span>{cameraLabel(shot.framing)}</span><span>{cameraLabel(shot.cameraAngle)}</span><span>{cameraLabel(shot.cameraMovement)}</span><span>{shot.sourceBlockId}</span></div>
  <button className="shot-expand" onClick={()=>setExpanded(value=>!value)}>{expanded?"收起摄影 / 道具 / 剪辑 / 连贯性":"展开摄影 / 道具 / 剪辑 / 连贯性"}</button>
  {expanded?<dl className="director-shot-grid"><div><dt>产品动作</dt><dd>{shot.productAction||"—"}</dd></div><div><dt>屏幕字幕</dt><dd>{shot.onScreenText||"—"}</dd></div><div><dt>道具 / 环境</dt><dd>{shot.props.join("、")||"—"}<br/>{shot.environment}</dd></div><div><dt>转场 / 剪辑</dt><dd>{shot.transition}<br/>{shot.editingNotes}</dd></div><div><dt>音效</dt><dd>{shot.audioSfx||"—"}</dd></div><div><dt>连贯性</dt><dd>{shot.continuityNotes||"—"}</dd></div></dl>:null}
 </article>;
}

export default function ShootingDirector({input,onNavigate}:Props){
 const [talent,setTalent]=useState("单人手模 / KOC"),[environment,setEnvironment]=useState("同一张整洁桌面"),[result,setResult]=useState<DirectorResult|null>(null),[shots,setShots]=useState<WorkspaceShot[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<number|null>(null),[preset,setPreset]=useState(presets[0]),[instruction,setInstruction]=useState(""),[preview,setPreview]=useState<RewritePreview|null>(null),[undo,setUndo]=useState<{index:number;shot:WorkspaceShot}|null>(null),[versions,setVersions]=useState<DirectorVersion[]>([]),[listStatus,setListStatus]=useState<"Draft"|"Confirmed">("Draft"),[rebalance,setRebalance]=useState<{beforePlanned:number;afterPlanned:number;target:number;delta:number}|null>(null),[showArchived,setShowArchived]=useState(false),[pendingDelete,setPendingDelete]=useState<number|null>(null);
 const dragged=useRef<number|null>(null),currentContextId=input?directorContextId(input):"",target=input?.context.targetDuration||30,planned=plannedDuration(shots),delta=Math.round((planned-target)*10)/10,contextChanged=Boolean(result&&result.metadata.contextId!==currentContextId);
 const sourceIds=useMemo(()=>input?scriptBlocks(input.script).map(block=>block.id):[],[input]);
 const contextMessages=useMemo(()=>result?.metadata.contextIntegrity.issues.map(issue=>`${issue.message}${issue.value?`：${issue.value}`:""}`)||[],[result]);
 const integrity=useMemo(()=>checkDirectorIntegrity(shots,target,input?.context.sellingPoints||"",sourceIds,contextMessages),[shots,target,input?.context.sellingPoints,sourceIds,contextMessages]);
 const props=useMemo(()=>[...new Set(shots.flatMap(x=>x.props))],[shots]);
 function commit(next:WorkspaceShot[]){setShots(recalculateTimeline(next.map(x=>({...x,status:"Draft"}))));setListStatus("Draft");setRebalance(null);}
 async function generate(){if(!input||busy)return;setBusy(true);setError("");try{const response=await fetch("/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,action:"generate",settings:{...input.settings,talent,environment,provider:"deepseek"}})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Director生成失败");if(result&&contextChanged){const archived=createDirectorVersion(versions,result.metadata.contextId,result.directorPlan,shots,listStatus);setVersions(value=>[...value,archived]);}setResult(data);setShots(workspaceShots(data.shots));setSelected(null);setPreview(null);setShowArchived(false);setListStatus("Draft");}catch(e){setError(e instanceof Error?e.message:"Director生成失败");}finally{setBusy(false);}}
 async function requestCandidate(index:number,action:"regenerate-shot"|"suggest-shot",requestedInstruction=instruction){if(!input||!result||busy||contextChanged)return null;const current=shots[index]||shots.at(-1);if(!current)return null;if(action==="regenerate-shot"&&current.locked&&!window.confirm("当前镜头已锁定。确认主动重新生成这个镜头？"))return null;setBusy(true);setError("");try{const block=scriptBlocks(input.script).find(x=>x.id===current.sourceBlockId);const response=await fetch("/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,action,contextId:result.metadata.contextId,currentShot:current,previousShot:shots[index-1],nextShot:shots[index+1],directorPlan:result.directorPlan,sourceBlock:block,preset,instruction:requestedInstruction})});const data=await response.json();if(!response.ok)throw new Error(data.error||"镜头生成失败");return{...data.candidate,locked:false,status:"Draft",metadata:data.metadata};}catch(e){setError(e instanceof Error?e.message:"镜头生成失败");return null;}finally{setBusy(false);}}
 async function regenerate(index:number){const candidate=await requestCandidate(index,"regenerate-shot");if(candidate)setPreview({mode:"replace",index,before:structuredClone(shots[index]),after:candidate,metadata:candidate.metadata});}
 async function suggest(index:number,requestedInstruction=instruction){const candidate=await requestCandidate(index,"suggest-shot",requestedInstruction);if(candidate)setPreview({mode:"insert",index,before:structuredClone(shots[index]),after:candidate,metadata:candidate.metadata});}
 async function rebuildUnlocked(){if(!input||!result||busy||contextChanged)return;const indexes=shots.map((shot,index)=>shot.locked?-1:index).filter(index=>index>=0);setBusy(true);setError("");try{const blocks=scriptBlocks(input.script);const candidates=await Promise.all(indexes.map(async index=>{const response=await fetch("/api/director",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...input,action:"regenerate-shot",contextId:result.metadata.contextId,currentShot:shots[index],previousShot:shots[index-1],nextShot:shots[index+1],directorPlan:result.directorPlan,sourceBlock:blocks.find(x=>x.id===shots[index].sourceBlockId),preset:"保持上下镜头连续，重做未锁定镜头",instruction})});if(!response.ok)return null;return(response.json() as Promise<{candidate:DirectorShot}>);}));const next=shots.map((shot,index)=>{const position=indexes.indexOf(index),data=position>=0?candidates[position]:null;return data?{...data.candidate,locked:false,status:"Draft" as const}:shot;});commit(next);}catch{setError("部分镜头重做失败，当前 Director 已保留");}finally{setBusy(false);}}
 function acceptPreview(){if(!preview)return;const {metadata:_,...candidate}=preview.after as WorkspaceShot&{metadata?:unknown};void _;if(preview.mode==="insert"){commit(insertShot(shots,preview.index,candidate));setSelected(preview.index+1);}else{setUndo({index:preview.index,shot:preview.before});commit(shots.map((shot,index)=>index===preview.index?{...candidate,locked:shot.locked,status:"Draft"}:shot));}setPreview(null);}
 function updateShot(index:number,key:keyof WorkspaceShot,value:string|number|string[]){commit(shots.map((shot,i)=>i===index?{...shot,[key]:value}:shot));}
 function remove(index:number){setPendingDelete(index);}
 function confirmDelete(){if(pendingDelete===null)return;commit(deleteShot(shots,pendingDelete));setSelected(null);setPendingDelete(null);notifyWorkspace("镜头已删除",{detail:"导演完整性检查已同步更新",tone:"info"});}
 function addManual(index:number){const basis=shots[index]||shots.at(-1);if(!basis)return;commit(insertShot(shots,index,emptyFrom(basis)));setSelected(index+1);}
 function doRebalance(){const summary=autoRebalance(shots,target);commit(summary.shots);setRebalance(summary);}
 function saveVersion(){if(!result)return;const version=createDirectorVersion(versions,result.metadata.contextId,result.directorPlan,shots,listStatus);setVersions(value=>[...value,version]);notifyWorkspace("导演版本已保存");}
 function confirmList(){setShots(value=>value.map(shot=>({...shot,status:"Confirmed"})));setListStatus("Confirmed");notifyWorkspace("导演分镜已确认",{detail:`共 ${shots.length} 个真实镜头记录`});}
 function scrollToShot(index:number){setSelected(index);document.getElementById(`director-${shots[index].shotId}`)?.scrollIntoView({behavior:"smooth",block:"center"});}
 function repairIntegrity(code:string){if(code==="duration_mismatch"){doRebalance();return;}if(code==="source_block_invalid"){const index=shots.findIndex(shot=>!sourceIds.includes(shot.sourceBlockId)&&!shot.sourceBlockId.startsWith("manual:"));if(index>=0)scrollToShot(index);return;}const ctaIndex=Math.max(0,shots.findIndex(shot=>/CTA/i.test(shot.stage))-1);const index=code==="reveal_missing"?Math.min(1,shots.length-1):ctaIndex;const direction=code==="reveal_missing"?"补充一个产品出场镜头，只使用当前脚本与产品资料。":"补充一个能直接拍摄的卖点证明镜头，只验证当前脚本与产品资料已有事实。";void suggest(index,direction);}
 if(result&&contextChanged)return <section className="director-studio director-workspace"><header><div><p className="eyebrow">AI 拍摄导演 · 上下文检查</p><h1>检测到当前脚本已变化</h1><p>旧导演工作台已隔离，不会作为当前脚本的镜头继续编辑。</p></div><div className="status needs"><i/> 上下文已变化</div></header><div className="context-change-gate"><div><span>当前脚本</span><h2>{input?.script.title||"当前脚本"}</h2><p>上下文 ID：{currentContextId}</p></div><div><span>现有导演方案</span><h2>{result.directorPlan.creativeIntent}</h2><p>上下文 ID：{result.metadata.contextId}</p></div><footer><button className="primary" disabled={busy} onClick={generate}>{busy?"正在生成…":"为当前脚本生成新导演方案"}</button><button onClick={()=>setShowArchived(value=>!value)}>{showArchived?"收起旧导演方案":"返回旧导演方案（只读）"}</button></footer></div>{showArchived?<section className="archived-director"><header><b>旧导演方案 · 只读</b><span>{shots.length} 个镜头 · {plannedDuration(shots)}秒</span></header>{shots.map(shot=><article key={shot.shotId}><b>镜头 {String(shot.order).padStart(2,"0")} · {stageLabel(shot.stage)}</b><p>{shot.visualDescription}</p><small>{shot.sourceBlockId}</small></article>)}</section>:null}{error?<p className="director-error">{error}</p>:null}</section>;
 return <section className="director-studio director-workspace"><header><div><p className="eyebrow">AI 拍摄导演 · 镜头工作台</p><h1>导演分镜工作台</h1><p>导演方案 → 编辑 / 锁定 / 重新生成 / 排序 → 确认分镜</p></div><div className="status"><i/> {statusLabel(listStatus)} · 导演建议</div></header>
  {!result?<div className="director-layout"><aside className="director-form"><span className="modal-kicker">导演输入</span><h2>{input?.script.title||"等待采用脚本"}</h2>{input?<><dl className="director-input-summary"><div><dt>产品</dt><dd>{input.context.product}</dd></div><div><dt>来源</dt><dd>{input.context.sourceType}</dd></div><div><dt>开场策略</dt><dd>{input.context.hookStrategy}</dd></div><div><dt>时长</dt><dd>{target}秒</dd></div></dl><section className="director-script-source"><b>产品知识</b><p>{input.context.productKnowledge?"已就绪":"使用创作需求作为后备"}</p></section><label>模特配置<input value={talent} onChange={e=>setTalent(e.target.value)}/></label><label>主拍摄环境<input value={environment} onChange={e=>setEnvironment(e.target.value)}/></label><button className="director-generate" disabled={busy} onClick={generate}>{busy?"正在生成导演方案与镜头列表…":"✦ 生成可执行镜头列表"}</button>{error?<p className="director-error">{error}</p>:null}</>:<div className="director-no-input"><b>还没有当前采用脚本</b><p>先从现有脚本入口选择一条采用稿，再进入导演工作台。</p><div className="director-empty-actions"><button onClick={()=>onNavigate?.("create")}>从 AI 脚本生成选择</button><button onClick={()=>onNavigate?.("history")}>从历史脚本选择</button><button onClick={()=>onNavigate?.("replicate")}>从爆款复刻选择</button></div></div>}</aside><main className="director-output">{busy?<WorkspaceState kind="loading" title="正在规划镜头与时长" description="AI 正在生成镜头目的、画面、动作、证明方式与拍摄建议。" />:error?<WorkspaceState kind="error" icon="!" title="导演方案生成失败" description={error} primary={{label:"重新生成",onClick:generate,disabled:!input}} secondary={{label:"重新选择脚本",onClick:()=>onNavigate?.("create")}} />:<WorkspaceState icon="◉" title={input?"脚本已就绪，可以开始导演规划":"选择一个脚本开始导演规划"} description="AI 将生成镜头、动作、证明方式和可执行拍摄建议。" primary={input?{label:"生成导演方案",onClick:generate}:{label:"选择脚本",onClick:()=>onNavigate?.("create")}} secondary={{label:"查看历史脚本",onClick:()=>onNavigate?.("history")}} />}</main></div>:<>
   <div className="workspace-topbar"><div><span>{input?.script.title}</span><b>{statusLabel(listStatus)} · {integrityLabel(integrity.status)}</b></div><section><article><small>目标时长</small><strong>{target}秒</strong></article><article><small>计划时长</small><strong>{planned}秒</strong></article><article className={Math.abs(delta)>.5?"warn":""}><small>时长差</small><strong>{delta>0?"+":""}{delta}秒</strong></article><article><small>镜头数量</small><strong>{shots.length}</strong></article><article><small>拍摄复杂度</small><strong>{result.directorPlan.shootingComplexity}</strong></article><article><small>AI 服务</small><strong>{result.metadata.providerUsed}</strong></article></section><nav><button onClick={doRebalance}>重新平衡时长</button><button onClick={saveVersion}>保存导演版本</button><button className="primary" onClick={confirmList}>确认导演分镜</button></nav></div>
   <div className="workspace-shell"><aside className="plan-sidebar"><span>导演方案</span><h2>{result.directorPlan.creativeIntent}</h2>{[["开场钩子",result.directorPlan.hookExecution],["节奏策略",result.directorPlan.pacingStrategy],["证明策略",result.directorPlan.proofStrategy],["产品出场",result.directorPlan.productRevealStrategy],["行动引导",result.directorPlan.ctaExecution]].map(([label,value])=><details key={label}><summary>{label}</summary><p>{value}</p></details>)}<details><summary>拍摄要求</summary><p>模特：{result.directorPlan.requiredTalent.join("、")}</p><p>道具：{props.join("、")}</p><p>场地：{result.directorPlan.requiredLocations.join("、")}</p></details><article className={integrity.status==="Complete"?"integrity-ok":"integrity-warn"}><b>完整性检查 · {integrityLabel(integrity.status)}</b>{integrity.issues.length?integrity.issues.map((issue,index)=><div key={`${issue.code}-${index}`}><p>• {issue.message}</p><button disabled={busy} onClick={()=>repairIntegrity(issue.code)}>{issue.code==="duration_mismatch"?"自动平衡时长":issue.code==="source_block_invalid"?"定位问题镜头":issue.code==="reveal_missing"?"AI 建议补充产品出场镜头":"AI 建议补充证明镜头"}</button></div>):<p>当前脚本、产品、来源段落、时长与时间轴均一致。</p>}</article>{versions.length?<article><b>版本历史</b>{versions.map(version=><p key={version.id}>{version.label} · {statusLabel(version.status)}</p>)}</article>:null}</aside>
    <main className="shot-workspace"><div className="workspace-actions"><div><b>{shots.filter(x=>x.locked).length} 个已锁定</b><span>锁定镜头不会被批量重做或自动调整时长</span></div><button disabled={busy} onClick={rebuildUnlocked}>{busy?"AI 正在处理…":"✦ AI 重做未锁定镜头"}</button>{undo?<button onClick={()=>{commit(shots.map((shot,index)=>index===undo.index?undo.shot:shot));setUndo(null);}}>撤销最近一次修改</button>:null}</div>{error?<p className="director-error">{error}</p>:null}
     <div className="director-shot-list">{shots.map((shot,index)=><div className="shot-row" key={shot.shotId}><ShotCard shot={shot} selected={selected===index} onSelect={()=>setSelected(index)} onToggleLock={()=>setShots(value=>value.map((item,i)=>i===index?{...item,locked:!item.locked}:item))} onDuplicate={()=>commit(duplicateShot(shots,index))} onDelete={()=>remove(index)} onRegenerate={()=>regenerate(index)} onDragStart={()=>{dragged.current=index;}} onDrop={()=>{if(dragged.current!==null){commit(reorderShots(shots,dragged.current,index));dragged.current=null;}}}/><div className="add-shot"><button onClick={()=>addManual(index)}>＋ 添加空白镜头</button><button disabled={busy} onClick={()=>suggest(index)}>✦ AI 建议镜头</button></div></div>)}</div>
    </main>
    <aside className="shot-inspector">{selected===null||!shots[selected]?<div className="inspector-empty"><b>镜头编辑器</b><h3>选择一个镜头进行编辑</h3><dl><div><dt>镜头数量</dt><dd>{shots.length}</dd></div><div><dt>时长</dt><dd>{planned}秒 / {target}秒</dd></div><div><dt>已锁定</dt><dd>{shots.filter(shot=>shot.locked).length}</dd></div><div><dt>草稿</dt><dd>{shots.filter(shot=>shot.status==="Draft").length}</dd></div><div><dt>完整性</dt><dd>{integrityLabel(integrity.status)}</dd></div></dl></div>:<><header><div><span>编辑镜头</span><h3>镜头 {String(selected+1).padStart(2,"0")}</h3></div><button onClick={()=>setSelected(null)}>×</button></header><nav className="inspector-actions"><button onClick={()=>setShots(value=>value.map((shot,index)=>index===selected?{...shot,locked:!shot.locked}:shot))}>{shots[selected].locked?"解锁":"锁定"}</button><button onClick={()=>regenerate(selected)}>AI 重新生成</button><button onClick={()=>commit(duplicateShot(shots,selected))}>复制镜头</button><button className="danger" onClick={()=>remove(selected)}>删除镜头</button></nav><label className="inspector-status">状态<select value={shots[selected].status} onChange={event=>updateShot(selected,"status",event.target.value)}><option value="Draft">草稿</option><option value="Confirmed">已确认</option><option value="Shot">已拍摄</option><option value="Retake">重拍</option></select></label><div className="inspector-fields">{editable.map(([key,label,type])=><label key={key}>{label}{type==="framing"||type==="angle"||type==="movement"?<select value={String(shots[selected][key])} onChange={e=>updateShot(selected,key,e.target.value)}>{(type==="framing"?framingValues:type==="angle"?cameraAngleValues:cameraMovementValues).map(value=><option key={value} value={value}>{cameraLabel(value)}</option>)}</select>:type==="textarea"?<textarea value={String(shots[selected][key]||"")} onChange={e=>updateShot(selected,key,e.target.value)}/>:<input type={type} step={type==="number"?.1:undefined} value={Array.isArray(shots[selected][key])?(shots[selected][key] as string[]).join("；"):String(shots[selected][key]||"")} onChange={e=>updateShot(selected,key,key==="props"?e.target.value.split(/[；;]+/).filter(Boolean):type==="number"?Number(e.target.value):e.target.value)}/>}</label>)}</div><section className="ai-shot-panel"><b>修改要求 / AI 重新生成</b><select value={preset} onChange={e=>setPreset(e.target.value)}>{presets.map(value=><option key={value}>{value}</option>)}</select><textarea placeholder="可以用中文输入要求；目标台词与字幕仍保持脚本设定语言。" value={instruction} onChange={e=>setInstruction(e.target.value)}/><button disabled={busy} onClick={()=>regenerate(selected)}>生成修改前后对比</button></section></>}</aside>
   </div>
   <section className={`director-timeline ${integrity.status==="Needs Attention"?"needs-attention":""}`}><header><b>镜头时间轴</b><span>0秒 → {planned}秒 · 目标 {target}秒</span></header><div>{shots.map((shot,index)=><button key={shot.shotId} style={{flexGrow:Math.max(.5,shot.duration)}} className={[selected===index?"selected":"",shot.locked?"locked":"",shot.status.toLowerCase(),integrity.status==="Needs Attention"?"attention":""].filter(Boolean).join(" ")} onClick={()=>scrollToShot(index)}><b>{String(index+1).padStart(2,"0")}</b><span>{shot.duration}秒 · {stageLabel(shot.stage)}</span></button>)}</div>{rebalance?<p>调整前 {rebalance.beforePlanned}秒 → 调整后 {rebalance.afterPlanned}秒 · 目标 {rebalance.target}秒 · 差值 {rebalance.delta}秒</p>:null}</section>
   {preview?<div className="rewrite-modal"><div><header><div><span>AI 镜头修改 · 修改前 / 修改后</span><h2>{preview.mode==="insert"?"新增镜头预览":`镜头 ${String(preview.index+1).padStart(2,"0")}`}</h2></div><button onClick={()=>setPreview(null)}>×</button></header><section><article><b>修改前</b><p>{preview.before.visualDescription}</p><small>{cameraLabel(preview.before.framing)} · {cameraLabel(preview.before.cameraMovement)}</small><p>{preview.before.proofRequirement}</p></article><article><b>修改后</b><p>{preview.after.visualDescription}</p><small>{cameraLabel(preview.after.framing)} · {cameraLabel(preview.after.cameraMovement)}</small><p>{preview.after.proofRequirement}</p></article></section><footer><span>AI 服务 {preview.metadata.providerUsed} · 事实保护 {preview.metadata.factGuardPassed?"通过":"需要检查"} · 安全回退 {preview.metadata.fallbackUsed?"是":"否"}</span><button onClick={()=>setPreview(null)}>拒绝</button><button className="primary" onClick={acceptPreview}>接受</button></footer></div></div>:null}
  </>}<ConfirmDialog open={pendingDelete!==null} title={pendingDelete===null?"删除镜头":`删除镜头 ${String(pendingDelete+1).padStart(2,"0")}？`} description="删除后不会自动恢复缺失的开场、证明或行动引导，完整性检查会重新计算。" confirmLabel="确认删除" tone="danger" onCancel={()=>setPendingDelete(null)} onConfirm={confirmDelete}/></section>;
}
