"use client";
import {useEffect,useMemo,useState} from "react";
import type {ProductKnowledge} from "./knowledge-context";
import {replicationReference,type ReplicationCandidate,type ReplicationConcept,type ReplicationMode,type ReplicationSetup,type ReplicationStrategy,type SimilarityResult} from "./replication-core";
import type {StructuredScript} from "./script-generation";
import type {ViralCase} from "./viral-analysis";
import type {ReplicationWorkspaceAsset} from "./analyzer-replication-workspace";
import WorkspaceState from "./components/ui/workspace-state";

type Product=ProductKnowledge&{id:number;name:string};
type Form={product:string;sellingPoints:string;audience:string;country:string;language:string;platform?:string;duration:string;offer:string;style:string;framework:string};
type Props={projectId:string|null;initialAsset:ReplicationWorkspaceAsset|null;cases:ViralCase[];initialCase:ViralCase|null;products:Product[];form:Form;onGenerated?:(value:ReplicationWorkspaceAsset)=>void;onAdopt:(script:StructuredScript,reference:string,setup:ReplicationSetup,candidate:ReplicationCandidate,workspace:ReplicationWorkspaceAsset)=>void;onDirector:(script:StructuredScript,reference:string,setup:ReplicationSetup,candidate:ReplicationCandidate,workspace:ReplicationWorkspaceAsset)=>void;onAnalyze:()=>void};
const modeOptions:Array<{id:ReplicationMode;label:string}>=[{id:"structure",label:"结构复刻"},{id:"hook",label:"Hook 机制"},{id:"pacing",label:"节奏复刻"},{id:"proof",label:"Proof 逻辑"},{id:"formula",label:"创意公式"},{id:"free",label:"自由改编"}];
const letters=["A","B","C"];
const conceptLabels:Record<string,string>={"Faithful Mechanism":"Faithful Mechanism","Product Native":"Product Native","Creative Mutation":"Creative Mutation"};

export default function ViralReplication({projectId,initialAsset,cases,initialCase,products,form,onGenerated,onAdopt,onDirector,onAnalyze}:Props){
 const sourceOptions=useMemo(()=>initialCase?[initialCase,...cases.filter(item=>item.id!==initialCase.id)]:cases,[cases,initialCase]);
 const restoredSource=initialAsset?.source||initialCase;
 const [sourceId,setSourceId]=useState(restoredSource?.id||"");
 const source=useMemo(()=>sourceOptions.find(item=>item.id===sourceId)||restoredSource||null,[sourceOptions,sourceId,restoredSource]);
 const [showLibrary,setShowLibrary]=useState(false);
 const [productId,setProductId]=useState(()=>products.find(item=>item.name===form.product)?.id||products[0]?.id||0),profile=products.find(item=>item.id===productId);
 const [target,setTarget]=useState({...form,platform:form.platform||"TikTok"});
 const [setup,setSetup]=useState<ReplicationSetup>(()=>initialAsset?.setup||{mode:"formula",intensity:"medium",market:form.country,language:form.language,platform:form.platform||"TikTok",duration:form.duration,instruction:""});
 const [strategy,setStrategy]=useState<ReplicationStrategy|null>(()=>initialAsset?.strategy||null),[candidates,setCandidates]=useState<ReplicationCandidate[]>(()=>initialAsset?.candidates||[]),[selected,setSelected]=useState(()=>initialAsset?.selected??1),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copyTrapBlocked,setCopyTrapBlocked]=useState(false),[compare,setCompare]=useState(false);
 useEffect(()=>{const projectSource=initialAsset?.source||initialCase;setSourceId(projectSource?.id||"");setTarget({...form,platform:form.platform||"TikTok",...(initialAsset?.target||{})});setSetup(initialAsset?.setup||{mode:"formula",intensity:"medium",market:form.country,language:form.language,platform:form.platform||"TikTok",duration:form.duration,instruction:""});setStrategy(initialAsset?.strategy||null);setCandidates(initialAsset?.candidates||[]);setSelected(initialAsset?.selected??1);setShowLibrary(false);setCompare(false);setError("")},[projectId,initialAsset]);
 const updateProduct=(id:number)=>{setProductId(id);const product=products.find(item=>item.id===id);if(product)setTarget(previous=>({...previous,product:product.name,sellingPoints:product.sellingPoints||previous.sellingPoints,audience:product.audience||previous.audience,country:product.markets?.split(/[、,，]/)[0]||previous.country,offer:product.offer||previous.offer}));setCandidates([]);setStrategy(null)};
 const payload=(strategyValue?:ReplicationStrategy)=>({product:target.product,sellingPoints:target.sellingPoints,audience:target.audience,country:setup.market,language:setup.language,platform:setup.platform,duration:setup.duration,offer:target.offer,style:target.style,framework:target.framework,creationMode:"KOC / UGC",hookStrategy:"好奇",creativity:setup.intensity==="low"?"稳定":setup.intensity==="high"?"激进":"平衡",productKnowledge:profile,referenceScript:source&&strategyValue?replicationReference(source,strategyValue,setup):undefined,recent:[],outputCount:1});
 const workspace=(overrides:Partial<ReplicationWorkspaceAsset>={}):ReplicationWorkspaceAsset=>({sourceId,source,setup,target,strategy,candidates,selected,...overrides});
 async function generateScript(concept:ReplicationConcept,strategyValue:ReplicationStrategy,attempt=0){const response=await fetch("/api/scripts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload(strategyValue),creativeConcept:{...concept,hookMechanism:`${concept.hookMechanism}${attempt?`；原创修复${attempt}：必须更换开头句式、场景措辞和CTA表达`:""}`},nonce:Date.now()+concept.id.charCodeAt(0)*997+attempt*7919})});const data=await response.json();if(!response.ok)throw new Error(data.error||`${concept.id}生成失败`);return data.script as StructuredScript}
 async function check(items:Array<{id:string;script:StructuredScript;regenerated?:boolean}>){const response=await fetch("/api/replicate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"check",sourceCase:source,setup,target:{...payload()},candidates:items})});const data=await response.json();if(!response.ok)throw new Error(data.error||"原创性检查失败");return data as {checks:Array<SimilarityResult&{id:string;factViolations:string[]}>;diversity:{passed:boolean;duplicateIndex:number|null}}}
 async function generate(){if(!source)return;setBusy(true);setError("");setCandidates([]);try{const targetPayload={...payload(),referenceScript:undefined};const response=await fetch("/api/replicate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"strategy",sourceCase:source,setup,target:targetPayload})});const data=await response.json();if(!response.ok)throw new Error(data.error||"策略生成失败");const currentStrategy=data.strategy as ReplicationStrategy;setStrategy(currentStrategy);setCopyTrapBlocked(Boolean(data.metadata?.copyTrapBlocked));const scripts=await Promise.all(data.concepts.map((concept:ReplicationConcept)=>generateScript(concept,currentStrategy)));let checked=await check(scripts.map((script,index)=>({id:letters[index],script})));const attempts=[0,0,0];for(let round=1;round<=2;round++){const failed=new Set(checked.checks.map((item,index)=>item.originalityPassed&&!item.factViolations.length?-1:index).filter(index=>index>=0));if(checked.diversity.duplicateIndex!==null)failed.add(checked.diversity.duplicateIndex);if(!failed.size)break;const replacements=await Promise.all([...failed].map(async index=>({index,script:await generateScript(data.concepts[index],currentStrategy,round)})));for(const item of replacements){scripts[item.index]=item.script;attempts[item.index]=round}checked=await check(scripts.map((script,index)=>({id:letters[index],script,regenerated:attempts[index]>0})))}const generated=scripts.map((script,index)=>({id:letters[index],concept:data.concepts[index],script,similarity:checked.checks[index],regenerationAttempts:attempts[index]}));setCandidates(generated);setSelected(1);onGenerated?.(workspace({strategy:currentStrategy,candidates:generated,selected:1}))}catch(reason){setError(reason instanceof Error?reason.message:"复刻失败")}finally{setBusy(false)}}
 const chosen=candidates[selected]||candidates[0];
 const reference=source&&strategy?replicationReference(source,strategy,setup):"";
 const guardsPassed=chosen&&chosen.similarity.originalityPassed&&chosen.similarity.sourceLeakage.length===0&&!chosen.similarity.factViolations?.length;
 const adopt=(next:"script"|"director")=>{if(!chosen||!guardsPassed)return;const snapshot=workspace({selected:candidates.indexOf(chosen),adoptedCandidate:chosen,adoptedScript:chosen.script});onGenerated?.(snapshot);if(next==="script")onAdopt(chosen.script,reference,setup,chosen,snapshot);else onDirector(chosen.script,reference,setup,chosen,snapshot)};
 const mapping=strategy&&source&&chosen?[
  ["Hook Mechanism",source.analysis.hook.mechanism,chosen.script.hook],
  ["Original Problem",source.analysis.hook.conflict,chosen.script.conflict||chosen.concept.scenario],
  ["Proof Function",strategy.proofMapping.map(item=>item.sourceProofFunction).join("；")||source.analysis.proofMechanisms.map(item=>item.type).join("；"),chosen.script.proof||strategy.proofMapping.map(item=>item.targetProof).join("；")],
  ["Selling Function",strategy.sellingPointMapping.map(item=>item.sourceFunction).join("；"),chosen.concept.sellingPointPriority],
  ["CTA Mechanism",source.analysis.ctaStyle,chosen.script.cta||chosen.concept.ctaStyle],
 ]:[];
 return <section className="replication-workspace" data-project-id={projectId||"none"} aria-busy={busy}>
  <main className="replication-canvas"><header className="workspace-command"><div><span>CREATIVE MAPPING WORKSPACE</span><h1>Creative Replication</h1><p>{source?.title||"当前项目创意迁移"}</p></div><dl><div><dt>产品</dt><dd>{target.product||"—"}</dd></div><div><dt>市场</dt><dd>{setup.market||"—"}</dd></div><div><dt>平台</dt><dd>{setup.platform}</dd></div><div><dt>语言</dt><dd>{setup.language}</dd></div><div><dt>Concept</dt><dd>{chosen?.concept.direction||"—"}</dd></div></dl><button className="vf-button vf-button-primary" disabled={!guardsPassed} onClick={()=>adopt("script")}>发送到 Script Workspace →</button></header>
   {!source?<section className="replication-empty"><WorkspaceState eyebrow="Creative Mapping Canvas" icon="◎" title="还没有复刻来源" description="先完成当前项目 Analyzer，或主动从案例库选择一个参考。" primary={{label:"进入 Analyzer",onClick:onAnalyze}} secondary={{label:"从案例库选择",onClick:()=>setShowLibrary(true)}}/>{showLibrary&&<section className="replication-library"><header><h2>主动选择案例库</h2><button onClick={()=>setShowLibrary(false)}>×</button></header>{cases.map(item=><button key={item.id} onClick={()=>{setSourceId(item.id);setShowLibrary(false)}}><b>{item.title}</b><span>{item.analysis.hook.mechanism}</span></button>)}</section>}</section>:<>
    <section className="replication-source-bar"><div><span>REFERENCE</span><strong>{source.title}</strong><small>{source.source.platform||source.source.inputType} · {source.source.market||setup.market}</small></div><button onClick={()=>setShowLibrary(value=>!value)}>更换案例库来源</button><details><summary>Creative Controls</summary><label>目标产品<select value={productId} onChange={event=>updateProduct(Number(event.target.value))}>{products.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div>{modeOptions.map(item=><button className={setup.mode===item.id?"active":""} key={item.id} onClick={()=>setSetup(previous=>({...previous,mode:item.id}))}>{item.label}</button>)}</div><label>重构强度<select value={setup.intensity} onChange={event=>setSetup(previous=>({...previous,intensity:event.target.value as ReplicationSetup["intensity"]}))}><option value="low">稳健</option><option value="medium">平衡</option><option value="high">突破</option></select></label><label>创意要求<textarea value={setup.instruction} onChange={event=>setSetup(previous=>({...previous,instruction:event.target.value}))}/></label></details></section>
    {showLibrary&&<section className="replication-library inline"><header><h2>案例库 · 仅主动选择</h2><button onClick={()=>setShowLibrary(false)}>×</button></header>{cases.map(item=><button key={item.id} onClick={()=>{setSourceId(item.id);setStrategy(null);setCandidates([]);setShowLibrary(false)}}><b>{item.title}</b><span>{item.analysis.hook.mechanism}</span></button>)}</section>}
    {busy?<WorkspaceState kind="loading" eyebrow="AI Replication" title="正在迁移爆款机制" description="保持说服功能，重新映射当前产品的真实卖点与证明。" steps={["理解来源机制","匹配产品事实","生成并检查 A / B / C"]}/>:!strategy?<section className="replication-understanding"><header><span>ORIGINAL VIRAL PATTERN</span><h2>AI 已读取当前项目 Analyzer Asset</h2><p>不是复制文案，而是迁移爆款机制。</p></header><div>{[["Hook",source.analysis.hook.mechanism],["Problem",source.analysis.hook.conflict],["Proof",source.analysis.proofMechanisms.map(item=>item.type).join(" · ")],["Selling",source.analysis.sellingPoints.map(item=>item.point).join(" · ")],["CTA",source.analysis.ctaStyle]].map(([name,value])=><article key={name}><b>{name}</b><p>{value||"当前分析未提供"}</p></article>)}</div>{copyTrapBlocked&&<p className="copy-trap">Copy Trap 已阻止：只迁移机制，不保留来源表达。</p>}<button className="vf-button vf-button-primary" disabled={!target.product||!target.sellingPoints} onClick={generate}>✦ 生成 A / B / C 创意方向</button></section>:<>
     <section className="mapping-board"><header><div><span>ORIGINAL → PRODUCT</span><h2>爆款机制 × 当前产品知识</h2></div><p>{strategy.targetProductFit}</p></header>{mapping.map(([label,original,adapted])=><article key={label}><div><span>{label}</span><p>{original||"当前来源未提供"}</p></div><i>→</i><div><span>Current Product Adaptation</span><p>{adapted||"当前 Concept 未提供"}</p></div></article>)}</section>
     <section className="concept-rail"><header><div><span>CONCEPT RAIL</span><h2>三个真实生成方向</h2></div><button onClick={()=>setCompare(value=>!value)}>{compare?"退出对比":"Compare"}</button></header><div>{candidates.slice(0,3).map((candidate,index)=>{const safe=candidate.similarity.originalityPassed&&candidate.similarity.sourceLeakage.length===0&&!candidate.similarity.factViolations?.length;return <article className={selected===index?"selected":""} key={candidate.id} onClick={()=>{setSelected(index);onGenerated?.(workspace({selected:index}))}}><header><b>Concept {candidate.id}</b><span>{conceptLabels[candidate.concept.direction]||candidate.concept.direction}</span></header><h3>{candidate.script.hook}</h3><dl><div><dt>Primary Selling Point</dt><dd>{candidate.concept.sellingPointPriority}</dd></div><div><dt>Hook Mechanism</dt><dd>{candidate.concept.hookMechanism}</dd></div><div><dt>Proof Mechanism</dt><dd>{candidate.concept.proofMechanism}</dd></div><div><dt>推荐理由</dt><dd>{candidate.concept.whyThisAdaptation}</dd></div></dl><footer><span className={safe?"pass":"risk"}>{safe?"Fact + Originality Passed":"需要检查"}</span>{initialAsset?.adoptedCandidate?.id===candidate.id&&<em>已采用</em>}<button disabled={!safe} onClick={event=>{event.stopPropagation();setSelected(index);const snapshot=workspace({selected:index,adoptedCandidate:candidate,adoptedScript:candidate.script});onGenerated?.(snapshot)}}>Adopt</button></footer></article>})}</div></section>
     {compare&&<section className="concept-compare">{candidates.slice(0,3).map(candidate=><article key={candidate.id}><b>{candidate.id} · {candidate.concept.direction}</b><p>{candidate.script.hook}</p><small>{candidate.concept.sellingPointPriority} · {candidate.concept.proofMechanism}</small></article>)}</section>}
    </>}{error&&<p className="replication-error">{error}</p>}
   </>}
  </main>
  <aside className="replication-assistant"><header><span>AI REPLICATION ASSISTANT</span><h2>AI 复刻助手</h2><small>{chosen?`Concept ${chosen.id} · ${chosen.concept.direction}`:"等待 Concept"}</small></header>{chosen&&strategy&&source?<><section className="assistant-focus"><span>Selling Point 选择理由</span><h3>{chosen.concept.sellingPointPriority}</h3><p>{chosen.concept.whyThisAdaptation}</p></section><section><span>Retained Viral Mechanism</span>{chosen.concept.sourceMechanismRetained.map((item,index)=><p key={index}>◆ {item}</p>)}</section><section><span>Original Elements</span>{chosen.concept.originalElementsIntroduced.map((item,index)=><p key={index}>＋ {item}</p>)}</section><section className="assistant-guard"><span>Safety & Originality</span><p><b>Product Fact</b>{chosen.similarity.factViolations?.length?chosen.similarity.factViolations.join("；"):"Passed"}</p><p><b>Originality</b>{chosen.similarity.originalityPassed?"Passed":"需要检查"}</p><p><b>Copy Trap</b>{copyTrapBlocked?"Blocked":"Clear"}</p><p><b>Market</b>{setup.market} · {setup.platform} · {setup.language}</p></section><footer><button onClick={generate} disabled={busy}>优化当前 Concept</button><button className="vf-button vf-button-secondary" onClick={()=>adopt("script")} disabled={!guardsPassed}>发送到 Script Workspace →</button><button className="vf-button vf-button-secondary" onClick={()=>adopt("director")} disabled={!guardsPassed}>发送到 AI Director</button></footer></>:<WorkspaceState eyebrow="AI Replication Assistant" title={source?"等待生成 Concept":"等待当前项目来源"} description={source?"生成 A / B / C 后显示真实卖点选择、保留机制、事实安全与原创检查。":"从 Analyzer 发送结果后会自动带入，不需要重复输入。"}/>}</aside>
 </section>;
}
