"use client";
import {useEffect,useMemo,useState} from "react";
import type {AnalysisInput,ViralAnalysisResult,ViralCase} from "./viral-analysis";
import {buildAnalyzerAsset} from "./analyzer-replication-workspace";
import WorkspaceState from "./components/ui/workspace-state";
import {notifyWorkspace} from "./components/ui/workspace-feedback";

type InsightTab="hook"|"structure"|"proof"|"conversion"|"visual";
type Props={projectId:string|null;initialCase:ViralCase|null;cases:ViralCase[];onSave:(item:ViralCase)=>void;onReplicate:(item:ViralCase)=>void;onResult?:(item:ViralCase)=>void;product?:string;market?:string;language?:string;platform?:string};
const empty=(product="",market="",language="",platform="TikTok"):AnalysisInput=>({sourceText:"",inputType:"transcript",platform,market,language,product,category:"",durationSeconds:undefined,views:"",likes:"",comments:"",shares:"",saves:"",gmv:"",sourceUrl:"",notes:"",visualNotes:""});
const present=(value:unknown)=>typeof value==="string"&&value.trim()&&value!=="未识别";
const labels:Record<InsightTab,string>={hook:"Hook",structure:"Structure",proof:"Proof",conversion:"Conversion",visual:"Visual Pattern"};

export default function ViralAnalyzer({projectId,initialCase,cases,onSave,onReplicate,onResult,product="",market="",language="",platform="TikTok"}:Props){
 const [input,setInput]=useState<AnalysisInput>(()=>initialCase?.source||empty(product,market,language,platform));
 const [result,setResult]=useState<ViralAnalysisResult|null>(()=>initialCase?.analysis||null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[creating,setCreating]=useState(false),[tab,setTab]=useState<InsightTab>("hook");
 useEffect(()=>{setInput(initialCase?.source||empty(product,market,language,platform));setResult(initialCase?.analysis||null);setCreating(false);setError("");setTab("hook")},[projectId,initialCase?.id,product,market,language,platform]);
 const patch=(value:Partial<AnalysisInput>)=>setInput(previous=>({...previous,...value}));
 const currentCase=useMemo(()=>result?buildAnalyzerAsset(input,result,projectId||undefined):null,[input,result,projectId]);
 async function analyze(){setBusy(true);setError("");try{const response=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw new Error(data.error||"分析失败");const item=buildAnalyzerAsset(input,data.analysis,projectId||undefined);setResult(item.analysis);onResult?.(item);setCreating(false);notifyWorkspace("爆款结构分析完成",{detail:"结果已保存到当前项目"})}catch(reason){setError(reason instanceof Error?reason.message:"分析失败")}finally{setBusy(false)}}
 const goReplication=()=>{if(currentCase){onSave(currentCase);onReplicate(currentCase)}};
 const assistant=useMemo(()=>{if(!result)return null;if(tab==="hook")return{title:result.hook.mechanism,body:result.hook.whyItWorks,strong:[result.hook.informationGap,result.hook.conflict].filter(present) as string[],risk:result.risks,transfer:result.replicationNotes.copySuggestions};if(tab==="structure")return{title:result.structure.map(x=>x.stage).join(" → "),body:result.pacing.assessment,strong:result.pacing.retentionBeats,risk:result.risks,transfer:result.reusableFormula};if(tab==="proof")return{title:result.proofMechanisms.map(x=>x.type).join(" · ")||"未提供明确 Proof",body:result.proofMechanisms.map(x=>x.content).join("；"),strong:result.proofMechanisms.filter(x=>x.observed).map(x=>x.content),risk:[],transfer:result.replicationNotes.visualSuggestions};if(tab==="conversion")return{title:result.ctaStyle,body:result.cta,strong:result.sellingPoints.map(x=>x.point),risk:result.risks,transfer:result.replicationNotes.copySuggestions};return{title:result.metadata.visualEvidenceAvailable?"已读取用户提供的画面描述":"没有提供画面证据",body:result.metadata.visualEvidenceAvailable?(input.visualNotes||""):"Visual Pattern 只展示用户真实提供的画面信息。",strong:result.replicationNotes.visualSuggestions,risk:[],transfer:result.replicationNotes.editingSuggestions}},[result,tab,input.visualNotes]);
 return <section className="analyzer-workspace" data-project-id={projectId||"none"} aria-busy={busy}>
  <main className="analyzer-canvas"><header className="workspace-command"><div><span>VIRAL INSIGHT WORKSPACE</span><h1>Viral Analyzer</h1><p>{currentCase?.title||"当前项目爆款研究"}</p></div><dl><div><dt>来源</dt><dd>{input.sourceUrl||input.inputType}</dd></div><div><dt>平台</dt><dd>{input.platform||"—"}</dd></div><div><dt>市场</dt><dd>{input.market||"—"}</dd></div><div><dt>状态</dt><dd>{busy?"分析中":result?"已分析":"未开始"}</dd></div></dl><button className="vf-button vf-button-primary" disabled={!currentCase} onClick={goReplication}>发送到创意复刻 →</button></header>
   {busy?<WorkspaceState kind="loading" eyebrow="AI 爆款分析" title="正在理解爆款机制" description="拆解 Hook、结构、节奏、Proof 与转化逻辑。" steps={["读取当前项目参考内容","识别留存与证明机制","生成可迁移结构"]}/>:error?<WorkspaceState kind="error" title="分析暂时中断" description={error} primary={{label:"重新分析",onClick:analyze}}/>:!result?<section className="analyzer-empty"><WorkspaceState eyebrow="Viral Analysis Canvas" icon="◇" title="还没有爆款分析" description="在当前项目中添加一条参考内容，完成后会直接进入结构化洞察画布。" primary={{label:"创建分析",onClick:()=>setCreating(true)}} detail={cases.length?`案例库中有 ${cases.length} 条案例，可在创建面板主动选择。`:"不会自动加载其他项目或全局案例"}/>{creating&&<section className="analyzer-create-panel"><header><div><span>NEW ANALYSIS</span><h2>添加参考内容</h2></div><button onClick={()=>setCreating(false)}>×</button></header><div className="analyzer-source-tabs"><button className={input.inputType==="transcript"?"active":""} onClick={()=>patch({inputType:"transcript"})}>口播文本</button><button className={input.inputType==="copy"?"active":""} onClick={()=>patch({inputType:"copy"})}>文案</button></div><textarea autoFocus rows={10} value={input.sourceText} onChange={event=>patch({sourceText:event.target.value})} placeholder="粘贴完整口播、字幕或参考文案…"/><div className="analyzer-create-grid"><label>平台<input value={input.platform} onChange={event=>patch({platform:event.target.value})}/></label><label>市场<input value={input.market} onChange={event=>patch({market:event.target.value})}/></label><label>语言<input value={input.language} onChange={event=>patch({language:event.target.value})}/></label><label>时长<input type="number" value={input.durationSeconds||""} onChange={event=>patch({durationSeconds:event.target.value?Number(event.target.value):undefined})}/></label></div><details><summary>画面与表现数据（可选）</summary><textarea rows={3} value={input.visualNotes} onChange={event=>patch({visualNotes:event.target.value})} placeholder="仅填写实际观察到的画面"/></details><button className="analyzer-create-submit vf-button vf-button-primary" disabled={input.sourceText.trim().length<20||busy} onClick={analyze}>✦ 开始结构化分析</button></section>}</section>:<div className="analyzer-result">
    <section className="analyzer-overview"><article><span>HOOK TYPE</span><h2>{result.hook.type}</h2><blockquote>{result.hook.original}</blockquote><div className="insight-pairs"><p><b>Mechanism</b>{result.hook.mechanism}</p>{present(result.hook.informationGap)&&<p><b>Information Gap</b>{result.hook.informationGap}</p>}{present(result.hook.conflict)&&<p><b>Conflict</b>{result.hook.conflict}</p>}<p><b>Promise → Payoff</b>{result.hook.promise} → {result.hook.payoff}</p></div></article><aside><strong>{result.score.total}<small>/100</small></strong><span>规则综合评分</span>{[["Hook",result.score.hookStrength],["Structure",result.score.structureClarity],["Proof",result.score.proofStrength],["Density",result.score.informationDensity],["CTA",result.score.ctaIntegration],["Replicability",result.score.replicability]].map(([name,value])=><p key={name}><span>{name}</span><i><b style={{width:`${value}%`}}/></i><em>{value}</em></p>)}</aside></section>
    <section className="analysis-section"><header><span>STRUCTURE & RETENTION</span><h2>内容结构与留存节拍</h2><p>{result.pacing.assessment}</p></header><div className="structure-timeline">{result.structure.map((item,index)=><article key={`${item.stage}-${index}`}><b>{String(index+1).padStart(2,"0")}</b><div><span>{item.stage}</span><h3>{item.content}</h3><p>{item.purpose}</p><small>{item.viewerPsychology}</small></div></article>)}</div>{result.pacing.retentionBeats.length>0&&<div className="retention-beats">{result.pacing.retentionBeats.map((item,index)=><span key={index}>{item}</span>)}</div>}</section>
    {result.timeline.length>0&&<section className="analysis-section"><header><span>TIMELINE</span><h2>画面 / 口播 / 剪辑时间线</h2><p>{result.metadata.timelineEstimated?"Estimated Timeline":"Provided Timeline"} · {result.metadata.visualEvidenceAvailable?"有画面证据":"无画面证据"}</p></header><div className="analysis-timeline">{result.timeline.map((item,index)=><article key={`${item.start}-${index}`}><time>{item.start}–{item.end}</time><div><b>{item.stage}</b><p>{item.spokenContent}</p><small>{item.retentionMechanism}</small></div>{result.metadata.visualEvidenceAvailable&&<aside><p>{item.visualDescription}</p><small>{item.editingNote}</small></aside>}</article>)}</div></section>}
    <div className="analysis-split"><section className="analysis-section"><header><span>PROOF & SELLING</span><h2>卖点与证明机制</h2></header>{result.sellingPoints.map((item,index)=><article className="analysis-evidence" key={index}><b>{item.priority}</b><div><strong>{item.point}</strong><p>{item.evidence}</p></div></article>)}{result.proofMechanisms.map((item,index)=><article className="analysis-evidence" key={`proof-${index}`}><b>{item.observed?"OBSERVED":"ANALYSIS"}</b><div><strong>{item.type}</strong><p>{item.content}</p></div></article>)}</section><section className="analysis-section"><header><span>VIRAL & CONVERSION</span><h2>爆款机制与转化</h2></header><div className="viral-mechanisms">{result.viralMechanisms.map((item,index)=><p key={index}><b>{String(index+1).padStart(2,"0")}</b>{item}</p>)}</div><div className="conversion-card"><span>{result.ctaStyle}</span><strong>{result.cta}</strong><small>{result.corePromise}</small></div>{result.risks.length>0&&<div className="analysis-risks"><b>RISKS</b>{result.risks.map((item,index)=><p key={index}>! {item}</p>)}</div>}</section></div>
   </div>}
  </main>
  <aside className="insight-assistant"><header><span>AI INSIGHT ASSISTANT</span><h2>AI 洞察助手</h2><small>{result?`当前 · ${labels[tab]}`:"等待分析"}</small></header>{result&&assistant?<><nav>{(Object.keys(labels) as InsightTab[]).map(key=><button className={tab===key?"active":""} key={key} onClick={()=>setTab(key)}>{labels[key]}</button>)}</nav><section className="assistant-focus"><span>当前判断</span><h3>{assistant.title||"当前结果未提供"}</h3><p>{assistant.body||"当前结果未提供更多说明"}</p></section>{assistant.strong.length>0&&<section><span>强项 / 关键证据</span>{assistant.strong.map((item,index)=><p key={index}>◆ {item}</p>)}</section>}{assistant.risk.length>0&&<section className="assistant-risk"><span>风险</span>{assistant.risk.map((item,index)=><p key={index}>! {item}</p>)}</section>}{assistant.transfer.length>0&&<section><span>可迁移价值</span>{assistant.transfer.map((item,index)=><p key={index}>→ {item}</p>)}</section>}<footer><button onClick={()=>notifyWorkspace("已聚焦当前机制",{detail:"继续使用现有 Analyzer 结果"})}>深挖当前机制</button><button className="vf-button vf-button-secondary" onClick={goReplication}>发送到 Replication →</button></footer></>:<WorkspaceState eyebrow="AI Insight Assistant" title="等待当前项目分析" description="生成或恢复 Analyzer Result 后，这里会展示真实判断、风险和迁移建议。"/>}</aside>
 </section>;
}
