"use client";
import {useMemo,useState} from "react";
import type {ProductKnowledge} from "./knowledge-context";
import {replicationReference,type ReplicationCandidate,type ReplicationConcept,type ReplicationMode,type ReplicationSetup,type ReplicationStrategy,type SimilarityResult} from "./replication-core";
import type {StructuredScript} from "./script-generation";
import type {ViralCase} from "./viral-analysis";

type Product=ProductKnowledge&{id:number;name:string};
type Form={product:string;sellingPoints:string;audience:string;country:string;language:string;platform?:string;duration:string;offer:string;style:string;framework:string};
type Props={cases:ViralCase[];initialCase:ViralCase|null;products:Product[];form:Form;onAdopt:(script:StructuredScript,reference:string,setup:ReplicationSetup)=>void;onDirector:(script:StructuredScript,reference:string,setup:ReplicationSetup)=>void;onAnalyze:()=>void};
const modeOptions:Array<{id:ReplicationMode;label:string;note:string}>=[{id:"structure",label:"结构复刻",note:"保留信息位置"},{id:"hook",label:"Hook机制",note:"重建开头表达"},{id:"pacing",label:"节奏复刻",note:"迁移信息节拍"},{id:"proof",label:"Proof逻辑",note:"映射证明功能"},{id:"formula",label:"创意公式",note:"使用Formula骨架"},{id:"free",label:"自由改编",note:"只保留心理机制"}];
const letters=["A","B","C"];
export default function ViralReplication({cases,initialCase,products,form,onAdopt,onDirector,onAnalyze}:Props){
 const sourceOptions=useMemo(()=>initialCase&&!cases.some(x=>x.id===initialCase.id)?[initialCase,...cases]:cases,[cases,initialCase]);const [sourceId,setSourceId]=useState(initialCase?.id||cases[0]?.id||"");const source=useMemo(()=>sourceOptions.find(x=>x.id===sourceId)||null,[sourceOptions,sourceId]);
 const [productId,setProductId]=useState(()=>products.find(x=>x.name===form.product)?.id||products[0]?.id||0);const profile=products.find(x=>x.id===productId);
 const [target,setTarget]=useState({...form,platform:form.platform||"TikTok"});const [setup,setSetup]=useState<ReplicationSetup>({mode:"formula",intensity:"medium",market:form.country,language:form.language,platform:form.platform||"TikTok",duration:form.duration,instruction:""});
 const [strategy,setStrategy]=useState<ReplicationStrategy|null>(null),[candidates,setCandidates]=useState<ReplicationCandidate[]>([]),[selected,setSelected]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copyTrapBlocked,setCopyTrapBlocked]=useState(false);
 const updateProduct=(id:number)=>{setProductId(id);const p=products.find(x=>x.id===id);if(p)setTarget(prev=>({...prev,product:p.name,sellingPoints:p.sellingPoints||prev.sellingPoints,audience:p.audience||prev.audience,country:p.markets?.split(/[、,，]/)[0]||prev.country,offer:p.offer||prev.offer}));setCandidates([]);setStrategy(null)};
 const payload=(strategyValue?:ReplicationStrategy)=>({product:target.product,sellingPoints:target.sellingPoints,audience:target.audience,country:setup.market,language:setup.language,platform:setup.platform,duration:setup.duration,offer:target.offer,style:target.style,framework:target.framework,creationMode:"KOC / UGC",hookStrategy:"好奇",creativity:setup.intensity==="low"?"稳定":setup.intensity==="high"?"激进":"平衡",productKnowledge:profile,referenceScript:source&&strategyValue?replicationReference(source,strategyValue,setup):undefined,recent:[],outputCount:1});
 async function generateScript(concept:ReplicationConcept,strategyValue:ReplicationStrategy,attempt=0){const res=await fetch("/api/scripts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload(strategyValue),creativeConcept:{...concept,hookMechanism:`${concept.hookMechanism}${attempt?`；原创修复${attempt}：必须更换开头句式、场景措辞和CTA表达`:""}`},nonce:Date.now()+concept.id.charCodeAt(0)*997+attempt*7919})});const data=await res.json();if(!res.ok)throw new Error(data.error||`${concept.id}生成失败`);return data.script as StructuredScript;}
 async function check(items:Array<{id:string;script:StructuredScript;regenerated?:boolean}>){const res=await fetch("/api/replicate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"check",sourceCase:source,setup,target:{...payload()},candidates:items})});const data=await res.json();if(!res.ok)throw new Error(data.error||"原创性检查失败");return data as {checks:Array<SimilarityResult&{id:string}>;diversity:{passed:boolean;duplicateIndex:number|null}};}
 async function generate(){if(!source)return;setBusy(true);setError("");setCandidates([]);try{const targetPayload={...payload(),referenceScript:undefined};const res=await fetch("/api/replicate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"strategy",sourceCase:source,setup,target:targetPayload})});const data=await res.json();if(!res.ok)throw new Error(data.error||"策略生成失败");const currentStrategy=data.strategy as ReplicationStrategy;setStrategy(currentStrategy);setCopyTrapBlocked(Boolean(data.metadata?.copyTrapBlocked));
   const scripts=await Promise.all(data.concepts.map((concept:ReplicationConcept)=>generateScript(concept,currentStrategy)));let checked=await check(scripts.map((script,i)=>({id:letters[i],script})));const attempts=[0,0,0];
   for(let round=1;round<=2;round++){const failed=new Set(checked.checks.map((x,i)=>x.originalityPassed?-1:i).filter(i=>i>=0));if(checked.diversity.duplicateIndex!==null)failed.add(checked.diversity.duplicateIndex);if(!failed.size)break;const replacements=await Promise.all([...failed].map(async i=>({i,script:await generateScript(data.concepts[i],currentStrategy,round)})));for(const x of replacements){scripts[x.i]=x.script;attempts[x.i]=round;}checked=await check(scripts.map((script,i)=>({id:letters[i],script,regenerated:attempts[i]>0})));}
   setCandidates(scripts.map((script,i)=>({id:letters[i],concept:data.concepts[i],script,similarity:checked.checks[i],regenerationAttempts:attempts[i]})));setSelected(1);
 }catch(e){setError(e instanceof Error?e.message:"复刻失败");}finally{setBusy(false)}}
 const chosen=candidates[selected];const reference=source&&strategy?replicationReference(source,strategy,setup):"";
 return <section className="vr-shell"><nav className="vr-workflow" aria-label="爆款复刻工作流"><div className="done"><b>1</b><span><small>Source</small>选择爆款案例</span></div><i/><div className="active"><b>2</b><span><small>Strategy</small>配置复刻策略</span></div><i/><div><b>3</b><span><small>Race</small>生成 A / B / C</span></div><i/><div><b>4</b><span><small>Adopt</small>采用并继续创作</span></div></nav><header className="vr-source"><div className="vr-source-copy"><span>SOURCE CASE · CREATIVE INTELLIGENCE</span><h2>{source?.title||"请选择爆款案例"}</h2><p>{source?.analysis.hook.original||"从 Analyzer 或案例库进入"}</p></div>{source?<dl><div><dt>Hook Mechanism</dt><dd>{source.analysis.hook.mechanism}</dd></div><div><dt>Viral Mechanism</dt><dd>{source.analysis.viralMechanisms.slice(0,2).join("；")}</dd></div><div><dt>Reusable Formula</dt><dd>{source.analysis.reusableFormula.join(" → ")}</dd></div></dl>:<button onClick={onAnalyze}>先去爆款拆解</button>}</header>
 <div className="vr-grid"><aside className="vr-setup"><span className="modal-kicker">REPLICATION SETUP</span><h2>目标产品与复刻方式</h2><label>Source Case<select value={sourceId} onChange={e=>{setSourceId(e.target.value);setCandidates([]);setStrategy(null)}}>{sourceOptions.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Target Product<select value={productId} onChange={e=>updateProduct(Number(e.target.value))}>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
  <div className="vr-brief"><label>产品<input value={target.product} onChange={e=>setTarget(p=>({...p,product:e.target.value}))}/></label><label>真实卖点<textarea rows={4} value={target.sellingPoints} onChange={e=>setTarget(p=>({...p,sellingPoints:e.target.value}))}/></label><label>受众<input value={target.audience} onChange={e=>setTarget(p=>({...p,audience:e.target.value}))}/></label></div>
  <div className="vr-fields"><label>Market<input value={setup.market} onChange={e=>setSetup(p=>({...p,market:e.target.value}))}/></label><label>Language<select value={setup.language} onChange={e=>setSetup(p=>({...p,language:e.target.value}))}><option>中文</option><option>西班牙语</option><option>英语</option><option>意大利语</option><option>德语</option></select></label><label>Platform<select value={setup.platform} onChange={e=>setSetup(p=>({...p,platform:e.target.value}))}><option>TikTok</option><option>Reels</option><option>Shorts</option></select></label><label>Duration<select value={setup.duration} onChange={e=>setSetup(p=>({...p,duration:e.target.value}))}><option value="30">30s</option><option value="45">45s</option><option value="60">60s</option></select></label></div>
  <h3>Replication Mode</h3><div className="vr-modes">{modeOptions.map(x=><button className={setup.mode===x.id?"active":""} key={x.id} onClick={()=>setSetup(p=>({...p,mode:x.id}))}><b>{x.label}</b><small>{x.note}</small></button>)}</div><h3>Intensity</h3><div className="vr-intensity">{(["low","medium","high"] as const).map((x,i)=><button className={setup.intensity===x?"active":""} key={x} onClick={()=>setSetup(p=>({...p,intensity:x}))}>{["低","中","高"][i]}</button>)}</div><label>自定义要求<textarea rows={3} value={setup.instruction} onChange={e=>setSetup(p=>({...p,instruction:e.target.value}))} placeholder="只影响创意方向；要求照抄会被Similarity Guard拒绝"/></label>{copyTrapBlocked&&<p className="vr-trap">Copy Trap 已阻止：只迁移机制，不执行保留原文要求。</p>}{error&&<p className="vr-error">{error}</p>}<button className="vr-generate" disabled={busy||!source||!target.product||!target.sellingPoints} onClick={generate}>{busy?"正在生成 Strategy + A/B/C…":"✦ 生成 3 条复刻方向"}</button>
 </aside><main className="vr-main">{!strategy?<div className="vr-empty"><div className="vr-empty-icon">✦</div><span>REPLICATION INTELLIGENCE</span><h2>先定义迁移策略，再生成原创脚本</h2><p>系统会隔离 Source Creative Mechanism 与 Target Product Facts，学习爆款机制，而不是复制原文。</p><div className="vr-empty-grid"><article><b>01</b><div><strong>机制提取</strong><small>Hook、节奏、结构与 Proof 逻辑</small></div></article><article><b>02</b><div><strong>产品映射</strong><small>只使用目标产品的真实知识</small></div></article><article><b>03</b><div><strong>原创赛马</strong><small>A / B / C 三种差异化方向</small></div></article><article><b>04</b><div><strong>安全检查</strong><small>Similarity Guard + Fact Guard</small></div></article></div><div className="vr-empty-hint"><span>←</span> 在左侧完成设置并生成策略</div></div>:<><section className="vr-strategy"><header><span>REPLICATION STRATEGY</span><h2>保留机制，重建表达</h2></header><div className="vr-strategy-grid"><article><b>Transferable</b>{strategy.transferableElements.map(x=><p key={x}>✓ {x}</p>)}</article><article className="dont"><b>Do Not Copy</b>{strategy.nonTransferableElements.map(x=><p key={x}>× {x}</p>)}</article><article><b>Product Mapping</b>{strategy.sellingPointMapping.map((x,i)=><p key={i}>{x.sourceFunction} → <strong>{x.targetSellingPoint}</strong></p>)}</article><article><b>Proof Mapping</b>{strategy.proofMapping.map((x,i)=><p key={i}>{x.sourceProofFunction} → <strong>{x.targetProof}</strong></p>)}</article></div></section>
 <section className="vr-race"><header><div><span>REPLICATION RACE</span><h2>A / B / C 三种原创方向</h2></div><small>一个候选失败只定向重生成该候选</small></header><div className="vr-cards">{candidates.map((x,i)=><article className={selected===i?"selected":""} key={x.id} onClick={()=>setSelected(i)}><header><b>{x.id}</b><div><strong>{x.concept.direction}</strong><small>{x.similarity.originalityPassed?"原创性通过":"原创性失败"}</small></div></header><h3>{x.script.hook}</h3><dl><div><dt>Angle</dt><dd>{x.concept.creativeAngle}</dd></div><div><dt>Scenario</dt><dd>{x.concept.scenario}</dd></div><div><dt>Proof</dt><dd>{x.concept.proofMechanism}</dd></div><div><dt>CTA</dt><dd>{x.concept.ctaStyle}</dd></div></dl><p>{x.concept.whyThisAdaptation}</p><footer><span className={x.similarity.originalityPassed?"pass":"fail"}>表达原创性：{x.similarity.originalityPassed?"通过":"未通过"}</span><span>结构借鉴：{x.similarity.structureSimilarity>.65?"高":x.similarity.structureSimilarity>.35?"中":"低"}</span><span>连续复制：{x.similarity.distinctivePhraseFound?"发现":"未发现"}</span>{x.regenerationAttempts>0&&<em>已定向重生成 {x.regenerationAttempts} 次</em>}</footer></article>)}</div></section>
 {chosen&&<section className="vr-compare"><header><span>SOURCE VS NEW</span><h2>学了什么 / 改了什么</h2></header><table><thead><tr><th>维度</th><th>Source</th><th>Retained Mechanism</th><th>New Version</th></tr></thead><tbody><tr><td>Hook</td><td>{source?.analysis.hook.original}</td><td>{source?.analysis.hook.mechanism}</td><td>{chosen.script.hook}</td></tr><tr><td>Scenario</td><td>{source?.analysis.contentType}</td><td>{chosen.concept.sourceMechanismRetained.join("；")}</td><td>{chosen.concept.scenario}</td></tr><tr><td>Proof</td><td>{source?.analysis.proofMechanisms.map(x=>x.type).join("；")}</td><td>{strategy.proofPlan}</td><td>{chosen.script.proof}</td></tr><tr><td>CTA</td><td>{source?.analysis.ctaStyle}</td><td>{strategy.ctaPlan}</td><td>{chosen.script.cta}</td></tr></tbody></table><div className="vr-actions"><button disabled={!chosen.similarity.originalityPassed} onClick={()=>onAdopt(chosen.script,reference,setup)}>采用此版本 → Script Studio</button><button disabled={!chosen.similarity.originalityPassed} onClick={()=>onDirector(chosen.script,reference,setup)}>采用并进入 AI Director</button></div></section>}</>}</main></div></section>;
}
