"use client";
import {useState} from "react";
import type {AnalysisInput,ViralAnalysisResult,ViralCase} from "./viral-analysis";
import WorkspaceState from "./components/ui/workspace-state";
import {notifyWorkspace} from "./components/ui/workspace-feedback";

type Props={cases:ViralCase[];onSave:(item:ViralCase)=>void;onReplicate:(item:ViralCase)=>void;product?:string;market?:string;language?:string};
const empty=(product="",market="",language=""):AnalysisInput=>({sourceText:"",inputType:"transcript",platform:"TikTok",market,language,product,category:"",durationSeconds:undefined,views:"",likes:"",comments:"",shares:"",saves:"",gmv:"",sourceUrl:"",notes:"",visualNotes:""});
export default function ViralAnalyzer({cases,onSave,onReplicate,product="",market="",language=""}:Props){
 const [input,setInput]=useState(()=>empty(product,market,language));const [result,setResult]=useState<ViralAnalysisResult|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const patch=(value:Partial<AnalysisInput>)=>{setInput(prev=>({...prev,...value}));setResult(null)};
 async function analyze(){setBusy(true);setError("");try{const res=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const data=await res.json();if(!res.ok)throw new Error(data.error||"分析失败");setResult(data.analysis);notifyWorkspace("爆款结构分析完成",{detail:"结果已使用当前输入的真实内容生成"});}catch(e){setError(e instanceof Error?e.message:"分析失败");}finally{setBusy(false)}}
 const currentCase=()=>result?{id:`viral-${Date.now()}`,title:`${input.product||input.category||"爆款内容"}｜${result.hook.type}`,createdAt:new Date().toISOString(),source:input,analysis:result}:null;
 return <section className="va-shell">
  <aside className="va-source"><span className="modal-kicker">来源输入 · 已提供信息</span><h2>输入爆款内容</h2><p>文案与口播文本是本阶段真实分析依据。没有提供的数据不会被补写。</p>
   <div className="va-toggle"><button className={input.inputType==="transcript"?"selected":""} onClick={()=>patch({inputType:"transcript"})}>口播文本</button><button className={input.inputType==="copy"?"selected":""} onClick={()=>patch({inputType:"copy"})}>文案</button></div>
   <label>原始文案 / 口播文本<textarea rows={15} value={input.sourceText} onChange={e=>patch({sourceText:e.target.value})} placeholder="粘贴完整口播、字幕或竞品爆款文案…"/></label>
   <div className="va-fields"><label>平台<input value={input.platform} onChange={e=>patch({platform:e.target.value})}/></label><label>市场<input value={input.market} onChange={e=>patch({market:e.target.value})}/></label><label>语言<input value={input.language} onChange={e=>patch({language:e.target.value})}/></label><label>时长（秒）<input type="number" value={input.durationSeconds||""} onChange={e=>patch({durationSeconds:e.target.value?Number(e.target.value):undefined})}/></label><label>产品<input value={input.product} onChange={e=>patch({product:e.target.value})}/></label><label>品类<input value={input.category} onChange={e=>patch({category:e.target.value})}/></label></div>
   <details><summary>真实表现数据（可选）</summary><div className="va-fields"><label>播放<input value={input.views} onChange={e=>patch({views:e.target.value})}/></label><label>点赞<input value={input.likes} onChange={e=>patch({likes:e.target.value})}/></label><label>评论<input value={input.comments} onChange={e=>patch({comments:e.target.value})}/></label><label>分享<input value={input.shares} onChange={e=>patch({shares:e.target.value})}/></label><label>收藏<input value={input.saves} onChange={e=>patch({saves:e.target.value})}/></label><label>GMV / 销量<input value={input.gmv} onChange={e=>patch({gmv:e.target.value})}/></label></div></details>
   <label>用户补充画面描述（可选）<textarea rows={3} value={input.visualNotes} onChange={e=>patch({visualNotes:e.target.value})} placeholder="未提供时，Visual / Editing会明确标记unknown"/></label>
   {error&&<p className="va-error">{error}</p>}<button className="va-analyze" disabled={busy||input.sourceText.trim().length<20} onClick={analyze}>{busy?"DeepSeek 正在拆解…":"✦ 开始结构化拆解"}</button>
   <div className="va-legacy"><b>视频资产保留</b><span>历史上传与播放器仍在项目中；当前DeepSeek只分析Transcript，不声称看过视频画面。</span></div>
  </aside>
  <main className="va-analysis">{busy?<WorkspaceState kind="loading" eyebrow="AI 爆款分析中心" title="正在理解内容结构" description="正在拆解开场、结构、节奏、卖点、证明与转化逻辑。" detail="不会补写未提供的播放量、GMV 或画面证据。" />:error?<WorkspaceState kind="error" icon="!" title="分析暂时中断" description={error} primary={{label:"重新分析",onClick:analyze}} secondary={{label:"修改输入",onClick:()=>document.querySelector<HTMLTextAreaElement>(".va-source textarea")?.focus()}} />:!result?<WorkspaceState eyebrow="AI 爆款分析中心" icon="◇" title="拆解一条爆款内容" description="粘贴完整口播或文案，AI 将拆解 Hook、结构、节奏、卖点、证明和转化逻辑。" primary={{label:"开始分析",onClick:analyze,disabled:input.sourceText.trim().length<20}} detail={cases.length>0?`案例库已有 ${cases.length} 条真实保存案例`:"分析结果可继续生成复刻方案或脚本"} />:<>
   <div className="va-head"><div><span>AI 分析 · DeepSeek</span><h2>{result.summary}</h2></div><b>{result.score.total}<small>/100</small></b></div>
   <article className="va-hook"><span>开场钩子深度分析</span><blockquote>{result.hook.original}</blockquote><div className="va-chips"><b>{result.hook.type}</b><b>{result.hook.mechanism}</b></div><p><strong>注意力机制</strong>{result.hook.whyItWorks}</p><p><strong>承诺 → 兑现</strong>{result.hook.promise} → {result.hook.payoff}</p></article>
   <section className="va-card"><h3>内容结构</h3>{result.structure.map((x,i)=><article className="va-stage" key={`${x.stage}-${i}`}><b>{i+1}</b><div><strong>{x.stage}</strong><p>{x.content}</p><small>{x.purpose} · {x.viewerPsychology}</small></div></article>)}</section>
   <section className="va-card"><h3>画面 / 口播 / 剪辑时间线</h3><div className="va-timeline-meta"><span>{result.metadata.timelineEstimated?"ESTIMATED TIMELINE":"PROVIDED TIMELINE"}</span><span>{result.metadata.visualEvidenceAvailable?"有用户画面证据":"无画面证据"}</span></div>{result.timeline.map((x,i)=><article className="va-time" key={`${x.start}-${i}`}><b>{x.start}–{x.end}</b><div><strong>{x.stage}</strong><p><em>口播</em>{x.spokenContent}</p><p><em>画面</em>{x.visualDescription}</p><p><em>剪辑</em>{x.editingNote}</p><small>{x.retentionMechanism}</small></div></article>)}</section>
   <div className="va-two"><section className="va-card"><h3>卖点 / 证明</h3>{result.sellingPoints.map((x,i)=><p key={i}><b>{x.priority}</b> {x.point}<small>Observed evidence: {x.evidence}</small></p>)}{result.proofMechanisms.map((x,i)=><p key={`p${i}`}><b>{x.observed?"OBSERVED":"AI ANALYSIS"}</b> {x.type} · {x.content}</p>)}</section><section className="va-card"><h3>留存 / 情绪</h3>{result.pacing.retentionBeats.map((x,i)=><p key={i}>↳ {x}</p>)}{result.emotionCurve.map((x,i)=><p key={`e${i}`}><b>{x.emotion}</b> {x.stage} · {x.trigger}</p>)}</section></div>
  </>}</main>
  <aside className="va-intel">{!result?<><span className="modal-kicker">爆款洞察</span><h2>案例库</h2>{cases.slice(0,5).map(item=><article className="va-saved" key={item.id}><b>{item.title}</b><small>{new Date(item.createdAt).toLocaleString("zh-CN")}</small><button onClick={()=>onReplicate(item)}>基于此案例复刻</button></article>)}</>:<>
   <span className="modal-kicker">爆款洞察</span><h2>为什么可能有效</h2><section className="va-card">{result.viralMechanisms.map((x,i)=><p key={i}>{i+1}. {x}</p>)}</section>
   <h3>ViralFlow 内容分析评分</h3><section className="va-scores">{Object.entries(result.score).filter(([,v])=>typeof v==="number").map(([k,v])=><div key={k}><span>{k}</span><b>{v as number}</b></div>)}<small>规则评分，不是播放量、爆款概率或留存预测。</small></section>
   <h3>可复刻公式</h3><section className="va-formula">{result.reusableFormula.map((x,i)=><div key={i}><b>{i+1}</b><span>{x}</span></div>)}</section>
   <h3>复刻建议</h3><section className="va-card"><b>画面</b>{result.replicationNotes.visualSuggestions.map((x,i)=><p key={i}>{x}</p>)}<b>文案</b>{result.replicationNotes.copySuggestions.map((x,i)=><p key={i}>{x}</p>)}<b>剪辑</b>{result.replicationNotes.editingSuggestions.map((x,i)=><p key={i}>{x}</p>)}</section>
   {result.risks.length>0&&<section className="va-risks"><b>风险</b>{result.risks.map((x,i)=><p key={i}>! {x}</p>)}</section>}
   <div className="va-actions"><button disabled={!result} onClick={()=>{const item=currentCase();if(item){onSave(item);notifyWorkspace("已保存到爆款案例库")}}}>保存到爆款案例库</button><button disabled={!result} onClick={()=>{const item=currentCase();if(item)onReplicate(item)}}>生成复刻方案 →</button></div>
  </>}</aside>
 </section>;
}
