"use client";
import {useEffect,useMemo,useState} from "react";
import WorkspaceState from "./components/ui/workspace-state";
import {notifyWorkspace} from "./components/ui/workspace-feedback";
const languages=[{label:"中文",value:"zh"},{label:"西班牙语",value:"es"},{label:"意大利语",value:"it"},{label:"法语",value:"fr"},{label:"德语",value:"de"},{label:"葡萄牙语",value:"pt"},{label:"英语",value:"en"}];
const voices=[{name:"爽快思思 2.0｜中文女声",id:"zh_female_shuangkuaisisi_uranus_bigtts",lang:"zh"},{name:"知性灿灿 2.0｜中文女声",id:"zh_female_cancan_uranus_bigtts",lang:"zh"},{name:"云舟 2.0｜中文男声",id:"zh_male_m191_uranus_bigtts",lang:"zh"},{name:"Dani｜西班牙男声",id:"es_male_dani_uranus_bigtts",lang:"es"},{name:"Guillem｜西班牙男声",id:"es_male_guillem_uranus_bigtts",lang:"es"},{name:"西班牙女声 BV084",id:"es_female_bv084_uranus_bigtts",lang:"es"},{name:"Enzo｜意大利男声",id:"it_male_enzo_uranus_bigtts",lang:"it"},{name:"德国女声 BV081",id:"de_female_bv081_uranus_bigtts",lang:"de"},{name:"Usseau｜法语男声",id:"fr_male_usseau_uranus_bigtts",lang:"fr"},{name:"法国男声 M29",id:"fr_male_fr_m29_uranus_bigtts",lang:"fr"},{name:"法国女声 F47",id:"fr_female_fr_f47_uranus_bigtts",lang:"fr"},{name:"法国女声 BV078",id:"fr_female_fr_bv078_uranus_bigtts",lang:"fr"},{name:"葡萄牙男声 BV531",id:"pt_male_bv531_uranus_bigtts",lang:"pt"},{name:"Mari｜葡萄牙女声",id:"pt_female_mari_uranus_bigtts",lang:"pt"},{name:"Nadia｜英语女声",id:"en_female_nadia_tips_emo_v2_mars_bigtts",lang:"en"},{name:"Sylus｜英语男声",id:"en_male_sylus_emo_v2_mars_bigtts",lang:"en"}];
const defaults:Record<string,string>={zh:voices[0].id,es:"es_female_bv084_uranus_bigtts",it:"it_male_enzo_uranus_bigtts",fr:"fr_female_fr_f47_uranus_bigtts",de:"de_female_bv081_uranus_bigtts",pt:"pt_female_mari_uranus_bigtts",en:"en_female_nadia_tips_emo_v2_mars_bigtts"};
const presets=[{id:"natural",name:"自然真人",speed:"1",text:"像真人朋友面对镜头自然分享，不要播音腔，语气松弛，有轻微呼吸感"},{id:"koc",name:"KOC种草",speed:"1.05",text:"像真实消费者分享刚发现的好东西，亲切可信，不过度推销"},{id:"sales",name:"强节奏带货",speed:"1.15",text:"短视频带货口吻，节奏有起伏，卖点有力度，但不要机械喊叫"},{id:"surprise",name:"惊讶吸睛",speed:"1.1",text:"开头带真实惊讶和好奇，随后自然解释，避免夸张表演感"},{id:"professional",name:"专业讲解",speed:".95",text:"清晰专业可信，像产品测评人讲解，重点词适当重读"},{id:"gentle",name:"温柔分享",speed:".9",text:"温柔放松、细腻亲和，像朋友轻声分享使用体验"}];
const segmentStyles=["惊讶吸睛","快速悬念","自然聊天","清晰讲解","卖点强调","温柔分享","行动感收尾"],gptVoices=["alloy","ash","ballad","coral","echo","fable","nova","onyx","sage","shimmer","verse"];
export default function VoiceStudio({initialText="",onChange}:{initialText?:string;onChange?:(value:unknown)=>void}){
 const [text,setText]=useState(initialText),[provider,setProvider]=useState<"doubao"|"gpt">("doubao"),[language,setLanguage]=useState("zh"),[speaker,setSpeaker]=useState(defaults.zh),[gptVoice,setGptVoice]=useState("coral"),[speed,setSpeed]=useState("1"),[emotion,setEmotion]=useState("natural"),[instruction,setInstruction]=useState(presets[0].text),[segmented,setSegmented]=useState(true),[smartPause,setSmartPause]=useState(true),[introStyle,setIntroStyle]=useState("惊讶吸睛"),[bodyStyle,setBodyStyle]=useState("自然聊天"),[outroStyle,setOutroStyle]=useState("行动感收尾"),[audioUrl,setAudioUrl]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const selectedVoice=useMemo(()=>provider==="gpt"?gptVoice:(voices.find(item=>item.id===speaker)?.name||speaker),[provider,gptVoice,speaker]);
 useEffect(()=>()=>{if(audioUrl)URL.revokeObjectURL(audioUrl)},[audioUrl]);
 async function generate(){if(!text.trim()||busy)return;setBusy(true);setError("");try{const response=await fetch(provider==="gpt"?"/api/openai-tts":"/api/tts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text,language,speaker:provider==="gpt"?gptVoice:speaker,speed:Number(speed),instruction,emotion,segmented,smartPause,introStyle,bodyStyle,outroStyle})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||"配音生成失败")}const blob=await response.blob();if(audioUrl)URL.revokeObjectURL(audioUrl);setAudioUrl(URL.createObjectURL(blob));onChange?.({text,provider,language,speaker:provider==="gpt"?gptVoice:speaker,speed,emotion,instruction,segmented,smartPause,introStyle,bodyStyle,outroStyle,generatedAt:new Date().toISOString(),audioAvailableInCurrentSession:true});notifyWorkspace("配音生成完成",{detail:"音频已进入当前画布，可试听或下载"});}catch(cause){setError(cause instanceof Error?cause.message:"配音生成失败")}finally{setBusy(false)}}
 function download(){if(!audioUrl)return;const anchor=document.createElement("a");anchor.href=audioUrl;anchor.download=`苏苏${provider==="gpt"?"GPT":"豆包"}配音-${Date.now()}.mp3`;anchor.click();notifyWorkspace("音频下载已开始")}
 return <section className="voice-studio creative-workspace"><header className="creative-workspace-head"><div><p className="eyebrow">AI 语音工作台</p><h1>多语言口播制作</h1><p>在同一条工作流中完成文案、音色、情绪、停顿与音频交付。</p></div><div className="status"><i/>{provider==="gpt"?"GPT 配音":"豆包语音 2.0"}</div></header><div className="voice-layout">
  <aside className="voice-controls workspace-panel"><div className="workspace-panel-head"><span>配置</span><h2>声音设置</h2><small>选择语言、音色和节奏</small></div><div className="provider-tabs"><button className={provider==="doubao"?"selected":""} onClick={()=>{setProvider("doubao");setError("")}}>豆包语音 2.0</button><button className={provider==="gpt"?"selected":""} onClick={()=>{setProvider("gpt");setError("")}}>GPT 配音 <em>待配置</em></button></div><div className="voice-two"><label>语言<select value={language} onChange={event=>{setLanguage(event.target.value);setSpeaker(defaults[event.target.value])}}>{languages.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label>{provider==="gpt"?"GPT 音色":"豆包音色"}<select value={provider==="gpt"?gptVoice:speaker} onChange={event=>provider==="gpt"?setGptVoice(event.target.value):setSpeaker(event.target.value)}>{provider==="gpt"?gptVoices.map(item=><option key={item}>{item[0].toUpperCase()+item.slice(1)}</option>):voices.filter(item=>item.lang===language).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label></div>{provider==="gpt"?<aside><b>GPT 接口已预留</b><p>接口未配置时不会以模拟音频冒充真实结果。</p><button type="button" disabled title="请在 Provider 设置中配置 GPT API">配置模型 · 未配置 API</button></aside>:null}<label>情绪预设<select value={emotion} onChange={event=>{const item=presets.find(value=>value.id===event.target.value)||presets[0];setEmotion(item.id);setSpeed(item.speed);setInstruction(item.text)}}>{presets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><details className="voice-advanced"><summary>高级设置</summary><div className="voice-switches"><button className={segmented?"on":""} onClick={()=>setSegmented(value=>!value)}><i/> 分段情绪控制</button><button className={smartPause?"on":""} onClick={()=>setSmartPause(value=>!value)}><i/> 智能停顿与换气</button></div>{segmented?<div className="segment-grid"><label>前3秒<select value={introStyle} onChange={event=>setIntroStyle(event.target.value)}>{segmentStyles.map(item=><option key={item}>{item}</option>)}</select></label><label>正文<select value={bodyStyle} onChange={event=>setBodyStyle(event.target.value)}>{segmentStyles.map(item=><option key={item}>{item}</option>)}</select></label><label>结尾<select value={outroStyle} onChange={event=>setOutroStyle(event.target.value)}>{segmentStyles.map(item=><option key={item}>{item}</option>)}</select></label></div>:null}<label>语速<select value={speed} onChange={event=>setSpeed(event.target.value)}>{["0.8","0.9","1","1.05","1.1","1.15","1.2"].map(item=><option key={item} value={item}>{item}×</option>)}</select></label><label>语气指令<textarea rows={3} value={instruction} onChange={event=>setInstruction(event.target.value)}/></label></details></aside>
  <main className="voice-editor workspace-panel"><div className="workspace-panel-head"><span>音频画布</span><h2>配音文案与时间轴</h2><small>{text.length}/5000 字</small></div><textarea value={text} onChange={event=>{setText(event.target.value);setError("")}} rows={18} placeholder="粘贴完整口播……"/><div className="voice-timeline" aria-label="音频时间轴"><div><span>开场</span><span>正文</span><span>收尾</span></div><small>{audioUrl?"音频已生成，可试听与下载":"生成后将在这里呈现完整音频"}</small></div><button className="voice-generate vf-button vf-button-primary" aria-busy={busy} title={!text.trim()?"请先输入口播文案":text.length>5000?"文案不能超过 5000 字":provider==="gpt"?"GPT API 尚未配置":undefined} disabled={!text.trim()||text.length>5000||busy} onClick={generate}>{busy?`正在生成${provider==="gpt"?"GPT":"豆包"}配音…`:`♫ 生成${provider==="gpt"?"GPT":"豆包"}配音`}</button>{busy?<WorkspaceState compact kind="loading" title="正在生成真实音频" description={`正在使用${provider==="gpt"?"GPT":"豆包语音 2.0"}处理音色、情绪和停顿。`} steps={["提交当前文案与音色设置","生成真实音频文件","准备试听与下载"]} />:error?<WorkspaceState compact kind="error" icon="!" title="配音生成失败" description={error} primary={{label:"重新生成",onClick:generate}} secondary={{label:"修改文案",onClick:()=>document.querySelector<HTMLTextAreaElement>(".voice-editor>textarea")?.focus()}} />:audioUrl?<div className="voice-player"><audio controls src={audioUrl}/><button className="vf-button vf-button-tertiary" onClick={download}>⇩ 下载 MP3</button></div>:<WorkspaceState compact icon="♫" title={text.trim()?"文案已就绪":"还没有输入口播文案"} description={text.trim()?"确认音色与节奏设置后，生成第一条真实配音。":"粘贴口播文案，选择语言和声音后开始生成。"} primary={{label:"生成第一条配音",onClick:generate,disabled:!text.trim()||text.length>5000}} />}</main>
  <aside className="voice-intelligence workspace-panel"><div className="workspace-panel-head"><span>AI 助手</span><h2>语音制作建议</h2><small>实时设置摘要</small></div><section><small>当前引擎</small><strong>{provider==="gpt"?"GPT 配音":"豆包语音 2.0"}</strong><p>{provider==="gpt"?"接口未配置时不会生成模拟音频。":"使用当前已接入的真实豆包 TTS。"}</p></section><section><small>音色与语言</small><strong>{selectedVoice}</strong><p>{languages.find(item=>item.value===language)?.label} · {speed}× · {presets.find(item=>item.id===emotion)?.name}</p></section><section><small>节奏策略</small><strong>{segmented?"分段情绪已开启":"统一情绪"}</strong><p>{smartPause?"已启用智能停顿与换气。":"使用原文标点控制停顿。"}</p></section><section className="voice-intel-note"><small>制作提醒</small><strong>{text.trim()?"文案已进入配音画布":"等待输入口播文案"}</strong><p>海外文案语言保持原样，中文仅用于系统操作界面。</p></section></aside>
 </div></section>;
}
