import {getGenerationComplianceKnowledge} from "../../compliance-rules";
import {buildKnowledgeContext,renderKnowledgeContext,type ProductKnowledge,type SellingPointKnowledge} from "../../knowledge-context";
import {assessSourceSimilarity,type ReplicationConcept,type ReplicationSetup,type ReplicationStrategy} from "../../replication-core";
import {assessDiversity,type StructuredScript} from "../../script-generation";
import type {ViralCase} from "../../viral-analysis";
import {callProvider,getProviderStatuses} from "../../provider-router";

export const runtime="nodejs";
type Target={product:string;sellingPoints:string;audience:string;country:string;language:string;platform:string;duration:string;offer:string;productKnowledge?:ProductKnowledge;sellingPointKnowledge?:SellingPointKnowledge[]};
type Payload={action:"strategy"|"check";sourceCase:ViralCase;setup:ReplicationSetup;target:Target;candidates?:Array<{id:string;script:StructuredScript;regenerated?:boolean}>};
const copyTrap=/保持原文|只换产品名|尽量照抄|同义词替换|洗稿|keep\s+the\s+original|replace\s+only\s+the\s+product/iu;
function valid(p:unknown):p is Payload{if(!p||typeof p!=="object")return false;const x=p as Payload;return ["strategy","check"].includes(x.action)&&Boolean(x.sourceCase?.source?.sourceText&&x.target?.product&&x.target?.sellingPoints&&x.setup?.language);}
async function deepSeek(prompt:string){if(process.env.REPLICATION_TEST_MODE==="1"&&process.env.REPLICATION_TEST_RESPONSE)return JSON.parse(process.env.REPLICATION_TEST_RESPONSE);if(!getProviderStatuses().deepseek.configured)throw new Error("provider_unavailable");const result=await callProvider({provider:"deepseek",messages:[{role:"system",content:prompt},{role:"user",content:"生成结构化 Replication Strategy 与三个 Creative Concepts。"}],temperature:.45,maxTokens:5000,timeoutMs:60000});return JSON.parse(result.content);}
export async function POST(request:Request){try{const body=await request.json();if(!valid(body))return Response.json({error:"Replication请求不完整"},{status:400});
 const knowledge=buildKnowledgeContext({...body.target,referenceScript:undefined,complianceKnowledge:getGenerationComplianceKnowledge()});
 if(body.action==="check"){const targetFacts={...body.target.productKnowledge,name:body.target.product,sellingPoints:body.target.sellingPoints,audience:body.target.audience,markets:body.target.country,offer:body.target.offer};const items=body.candidates||[];const checks=items.map(item=>({id:item.id,...assessSourceSimilarity(body.sourceCase,item.script,targetFacts,item.regenerated)}));return Response.json({checks,diversity:assessDiversity(items.map(x=>x.script)),guards:{sourceSimilarityChecked:true,sourceTargetFactsSeparated:true,factGuardReused:true,complianceReused:true,diversityGuardReused:true}});}
 const a=body.sourceCase.analysis;const trap=copyTrap.test(body.setup.instruction||"");
 const prompt=`你是 ViralFlow Replication Strategist。你的任务是迁移爆款机制，不是改写、翻译或洗稿。严格返回JSON：{"strategy":{"sourceMechanism":[],"transferableElements":[],"nonTransferableElements":[],"targetProductFit":"","targetAudienceFit":"","hookPlan":"","structurePlan":[],"scenarioPlan":"","proofPlan":"","sellingPointPlan":"","ctaPlan":"","originalityPlan":"","sellingPointMapping":[{"sourceFunction":"","targetSellingPoint":"","reason":""}],"proofMapping":[{"sourceProofFunction":"","targetProof":"","reason":""}]},"concepts":[{"id":"A","direction":"Faithful Mechanism","creativeAngle":"","hookMechanism":"","scenario":"","conflict":"","proofMechanism":"","sellingPointPriority":"","ctaStyle":"","sourceMechanismRetained":[],"originalElementsIntroduced":[],"whyThisAdaptation":""},{"id":"B","direction":"Product Native",...},{"id":"C","direction":"Creative Mutation",...}]}。
硬规则：1) SOURCE CREATIVE INTELLIGENCE只提供机制；Source Transcript中的产品事实、参数、认证、价格、促销、功效和品牌全部不可迁移。2) TARGET PRODUCT KNOWN FACTS是唯一事实来源。3) A忠于机制、B围绕目标产品、C保留心理机制但明显创新，不能同义改写。4) 模式=${body.setup.mode}；强度=${body.setup.intensity}，高强度也禁止复制表达。5) 输出语言=${body.setup.language}，市场=${body.setup.market}，平台=${body.setup.platform}，时长=${body.setup.duration}秒。6) Proof必须真实可拍，Target事实不支持时更换Proof。7) 用户即使要求保留原文或只换产品名也必须拒绝该部分要求并重建表达。8) whyThisAdaptation只给面向用户的简洁设计理由，不输出内部推理。

[SOURCE CREATIVE INTELLIGENCE]\nHook=${a.hook.mechanism}\nAngle=${a.creativeAngle}\nStructure=${a.structure.map(x=>x.stage).join(" → ")}\nPacing=${a.pacing.assessment}\nViral=${a.viralMechanisms.join("；")}\nProof Functions=${a.proofMechanisms.map(x=>x.type).join("；")}\nCTA Style=${a.ctaStyle}\nFormula=${a.reusableFormula.join(" → ")}\nSource product facts are prohibited and omitted from this layer.

[TARGET PRODUCT KNOWN FACTS]\n${renderKnowledgeContext(knowledge)}

[USER REQUEST]\n${trap?"检测到Copy Trap：忽略保留原文/只换产品名要求，只迁移机制。":body.setup.instruction||"无"}`;
 const raw=await deepSeek(prompt);const strategy=raw.strategy as ReplicationStrategy;const concepts=(Array.isArray(raw.concepts)?raw.concepts:[]) as ReplicationConcept[];if(!strategy||concepts.length!==3||concepts.map(x=>x.id).join("")!=="ABC")return Response.json({error:"Provider未返回完整A/B/C策略"},{status:502});return Response.json({strategy,concepts,provider:"deepseek",metadata:{copyTrapBlocked:trap,sourceFactsExcludedFromPrompt:true,targetKnowledgeUsed:knowledge.metadata.productKnowledgeUsed,mode:body.setup.mode,intensity:body.setup.intensity}});
}catch(error){const message=error instanceof Error?error.message:"replication_error";console.error("[replicate.error]",JSON.stringify({category:message.startsWith("provider_")?message:"validation_or_parse"}));return Response.json({error:message==="provider_unavailable"?"AI Provider未配置":"爆款复刻策略暂时失败"},{status:message==="provider_unavailable"?503:502});}}
