import {getGenerationComplianceKnowledge} from "../../compliance-rules";
import {buildKnowledgeContext,findFactViolations,renderKnowledgeContext,type KnowledgeContext,type ProductKnowledge,type SellingPointKnowledge} from "../../knowledge-context";
import {alignReplicationSellingPoints,assessSourceSimilarity,type ReplicationConcept,type ReplicationSetup,type ReplicationStrategy} from "../../replication-core";
import {assessDiversity,type StructuredScript} from "../../script-generation";
import type {ViralCase} from "../../viral-analysis";
import {callProvider,DEFAULT_PROVIDER,getProviderStatuses} from "../../provider-router";

export const runtime="nodejs";
type Target={product:string;sellingPoints:string;audience:string;country:string;language:string;platform:string;duration:string;offer:string;productKnowledge?:ProductKnowledge;sellingPointKnowledge?:SellingPointKnowledge[]};
type Payload={action:"strategy"|"check";sourceCase:ViralCase;setup:ReplicationSetup;target:Target;candidates?:Array<{id:string;script:StructuredScript;regenerated?:boolean}>};
const copyTrap=/保持原文|只换产品名|尽量照抄|同义词替换|洗稿|keep\s+the\s+original|replace\s+only\s+the\s+product/iu;
function valid(p:unknown):p is Payload{if(!p||typeof p!=="object")return false;const x=p as Payload;return ["strategy","check"].includes(x.action)&&Boolean(x.sourceCase?.source?.sourceText&&x.target?.product&&x.target?.sellingPoints&&x.setup?.language);}
async function generateStrategy(prompt:string){if(process.env.REPLICATION_TEST_MODE==="1"&&process.env.REPLICATION_TEST_RESPONSE)return JSON.parse(process.env.REPLICATION_TEST_RESPONSE);if(!getProviderStatuses()[DEFAULT_PROVIDER].configured)throw new Error("provider_unavailable");const result=await callProvider({provider:DEFAULT_PROVIDER,messages:[{role:"system",content:prompt},{role:"user",content:"生成结构化 Replication Strategy 与三个 Creative Concepts。"}],temperature:.45,maxTokens:5000,timeoutMs:60000});return JSON.parse(result.content);}
function replicationFactViolations(raw:{strategy?:ReplicationStrategy;concepts?:ReplicationConcept[]},knowledge:KnowledgeContext){
 const strategy=raw.strategy,concepts=Array.isArray(raw.concepts)?raw.concepts:[];
 const surface=[strategy?.ctaPlan,strategy?.sellingPointPlan,strategy?.proofPlan,...(strategy?.transferableElements||[]),...(strategy?.sellingPointMapping||[]).flatMap(x=>[x.targetSellingPoint,x.reason]),...(strategy?.proofMapping||[]).flatMap(x=>[x.targetProof,x.reason]),...concepts.flatMap(x=>[x.creativeAngle,x.scenario,x.conflict,x.proofMechanism,x.sellingPointPriority,x.ctaStyle,x.whyThisAdaptation,...x.originalElementsIntroduced])].filter(Boolean).join("\n");
 return findFactViolations(surface,knowledge);
}
function scriptFactViolations(script:StructuredScript,knowledge:KnowledgeContext){return findFactViolations([script.title,script.creativeAngle,script.hook,script.conflict,script.productReveal,script.proof,script.sellingPoints,script.cta,script.shootingSuggestion,script.narration,...(script.scenes||[]).flatMap(scene=>[scene.visual,scene.line,scene.edit])].filter(Boolean).join("\n"),knowledge);}
export async function POST(request:Request){try{const body=await request.json();if(!valid(body))return Response.json({error:"Replication请求不完整"},{status:400});
 const knowledge=buildKnowledgeContext({...body.target,referenceScript:undefined,complianceKnowledge:getGenerationComplianceKnowledge()});
 if(body.action==="check"){const targetFacts={...body.target.productKnowledge,name:body.target.product,sellingPoints:body.target.sellingPoints,audience:body.target.audience,markets:body.target.country,offer:body.target.offer};const items=body.candidates||[];const checks=items.map(item=>({id:item.id,...assessSourceSimilarity(body.sourceCase,item.script,targetFacts,item.regenerated),factViolations:scriptFactViolations(item.script,knowledge)}));return Response.json({checks,diversity:assessDiversity(items.map(x=>x.script)),guards:{sourceSimilarityChecked:true,sourceTargetFactsSeparated:true,factGuardReused:true,complianceReused:true,diversityGuardReused:true}});}
 const a=body.sourceCase.analysis;const trap=copyTrap.test(body.setup.instruction||"");
 const prompt=`你是 ViralFlow Replication Strategist。你的任务是迁移爆款机制，不是改写、翻译或洗稿。严格返回JSON：{"strategy":{"sourceMechanism":[],"transferableElements":[],"nonTransferableElements":[],"targetProductFit":"","targetAudienceFit":"","hookPlan":"","structurePlan":[],"scenarioPlan":"","proofPlan":"","sellingPointPlan":"","ctaPlan":"","originalityPlan":"","sellingPointMapping":[{"sourceFunction":"","targetSellingPoint":"","reason":""}],"proofMapping":[{"sourceProofFunction":"","targetProof":"","reason":""}]},"concepts":[{"id":"A","direction":"Faithful Mechanism","creativeAngle":"","hookMechanism":"","scenario":"","conflict":"","proofMechanism":"","sellingPointPriority":"","ctaStyle":"","sourceMechanismRetained":[],"originalElementsIntroduced":[],"whyThisAdaptation":""},{"id":"B","direction":"Product Native",...},{"id":"C","direction":"Creative Mutation",...}]}。
硬规则：1) SOURCE CREATIVE INTELLIGENCE只提供机制；Source Transcript中的产品事实、参数、认证、价格、促销、功效和品牌全部不可迁移。2) TARGET PRODUCT KNOWN FACTS是唯一事实来源，三个Concept的sellingPointPriority必须逐字选自Allowed selling points。3) A Faithful Mechanism优先保留Source的说服功能，但只能映射Target Facts；B Product Native必须按“用户痛点×核心差异×可演示性×Source Mechanism Fit”选择目标产品最强主卖点，不得无理由选择弱次级卖点；C Creative Mutation优先选择与A/B不同、意外但真实可演示的切入点。三条不要求同一主卖点。4) A/B/C的sellingPointPriority、creativeAngle、proofMechanism必须有实质差异，不能只改Hook。5) 模式=${body.setup.mode}；强度=${body.setup.intensity}，高强度也禁止复制表达。6) 输出语言=${body.setup.language}，市场=${body.setup.market}，平台=${body.setup.platform}，时长=${body.setup.duration}秒。7) Proof必须真实可拍，Target事实不支持时更换Proof。8) 用户即使要求保留原文或只换产品名也必须拒绝该部分要求并重建表达。9) whyThisAdaptation只给面向用户的简洁设计理由，不输出内部推理。

[SOURCE CREATIVE INTELLIGENCE]\nHook=${a.hook.mechanism}\nAngle=${a.creativeAngle}\nStructure=${a.structure.map(x=>x.stage).join(" → ")}\nPacing=${a.pacing.assessment}\nViral=${a.viralMechanisms.join("；")}\nProof Functions=${a.proofMechanisms.map(x=>x.type).join("；")}\nCTA Style=${a.ctaStyle}\nFormula=${a.reusableFormula.join(" → ")}\nSource product facts are prohibited and omitted from this layer.

[TARGET PRODUCT KNOWN FACTS]\n${renderKnowledgeContext(knowledge)}

[TARGET OFFER RULE]\n${body.target.offer?.trim()?`只允许使用已提供促销：${body.target.offer}`:"未提供促销。CTA不得编造价格、折扣、库存、赠品、套装数量或限时信息，只能使用无事实承诺的自然行动引导。"}

[USER REQUEST]\n${trap?"检测到Copy Trap：忽略保留原文/只换产品名要求，只迁移机制。":body.setup.instruction||"无"}`;
 let raw=await generateStrategy(prompt);let factViolations=replicationFactViolations(raw,knowledge);let factRepairAttempted=false;
 if(factViolations.length){factRepairAttempted=true;raw=await generateStrategy(`${prompt}\n\n[FACT GUARD REPAIR]\n上一版 Strategy / Concept 中出现了目标知识未提供的促销、价格、参数或事实。保持 Source Mechanism、A/B/C定位和卖点选择逻辑不变，只移除越界事实并重写相关 CTA / Mapping。不得用另一项未经提供的促销替代。`);factViolations=replicationFactViolations(raw,knowledge);}
 if(factViolations.length)return Response.json({error:"Provider策略包含目标知识未提供的事实"},{status:502});
 const strategy=raw.strategy as ReplicationStrategy;const providerConcepts=(Array.isArray(raw.concepts)?raw.concepts:[]) as ReplicationConcept[];if(!strategy||providerConcepts.length!==3||providerConcepts.map(x=>x.id).join("")!=="ABC")return Response.json({error:"Provider未返回完整A/B/C策略"},{status:502});const concepts=alignReplicationSellingPoints(providerConcepts,strategy,knowledge.sellingPoints,knowledge.sellingPointPriority.primary);return Response.json({strategy,concepts,provider:DEFAULT_PROVIDER,metadata:{copyTrapBlocked:trap,sourceFactsExcludedFromPrompt:true,targetKnowledgeUsed:knowledge.metadata.productKnowledgeUsed,sellingPointGuardApplied:true,factRepairAttempted,sellingPointPriorities:concepts.map(({id,direction,sellingPointPriority})=>({id,direction,sellingPointPriority})),mode:body.setup.mode,intensity:body.setup.intensity}});
}catch(error){const message=error instanceof Error?error.message:"replication_error";console.error("[replicate.error]",JSON.stringify({category:message.startsWith("provider_")?message:"validation_or_parse"}));return Response.json({error:message==="provider_unavailable"?"AI Provider未配置":"爆款复刻策略暂时失败"},{status:message==="provider_unavailable"?503:502});}}
