import {callProvider,ProviderCallError} from "../../provider-router";
import {directorFactViolations,directorKnowledge,fallbackDirector,rebalanceShots,targetDuration,validateDirector,type DirectorRequest,type DirectorResult} from "../../director-core";
import {renderKnowledgeContext} from "../../knowledge-context";
import type {ProviderErrorType} from "../../provider-types";

const safeError=(error:unknown):ProviderErrorType=>error instanceof ProviderCallError?error.category:"schema_validation_error";
const outputShape={directorPlan:{recommendationType:"Director Recommendation",creativeIntent:"string",visualStyle:"string",hookExecution:"string",pacingStrategy:"string",proofStrategy:"string",productRevealStrategy:"string",ctaExecution:"string",shootingComplexity:"Simple | Standard | Advanced",requiredTalent:["string"],requiredProps:["string"],requiredLocations:["string"]},shots:[{shotId:"shot-01",order:1,startTime:0,endTime:3,duration:3,sourceBlockId:"scene-1",stage:"HOOK",purpose:"Attention",shotType:"Attention Shot",framing:"Extreme Close-Up",cameraAngle:"Eye Level",cameraMovement:"Static",visualDescription:"string",subject:"string",productAction:"string",talentAction:"string",props:["string"],environment:"string",dialogue:"string or empty",voiceover:"string or empty",onScreenText:"string or empty",proofRequirement:"string or empty",transition:"Hard Cut",editingNotes:"string",audioSfx:"string",continuityNotes:"string",priority:"Critical | High | Normal"}]};
function prompt(request:DirectorRequest,repair=false){const knowledge=directorKnowledge(request);return{system:`你是TikTok电商短视频导演。输出是 Director Recommendation，不是对原视频视觉的观察。把结构化脚本转换成可直接拍摄的导演总纲和Shot List。一个Block可拆多镜，短Block可合并，但每个Shot必须用sourceBlockId追踪。前三秒按Hook Strategy设计真实视觉机制；Proof必须包含操作前、关键动作、操作后可见结果。只使用知识上下文里的产品事实。Dialogue、Voiceover、On-screen Text按创作模式分工，不能复制三份。镜头自然可执行，避免无意义复杂运镜。总时长尽量等于${targetDuration(request.context.targetDuration)}秒。${repair?"上一版没有通过结构或事实校验。本次必须逐字段补齐，sourceBlockId只能使用输入中的scene-N，不增加任何产品事实。":""}严格返回JSON，不要解释，不要Markdown。输出必须逐字段符合此结构：${JSON.stringify(outputShape)}\n${renderKnowledgeContext(knowledge)}`,user:JSON.stringify({script:request.script,context:request.context,settings:request.settings,allowedEnums:{framing:["Extreme Close-Up","Close-Up","Medium Close-Up","Medium","Wide","Over-the-Shoulder","Top-Down","Product Macro"],cameraAngle:["Eye Level","High Angle","Low Angle","Top-Down","Side Angle","45 Degree"],cameraMovement:["Static","Push In","Pull Out","Pan","Tilt","Handheld","Tracking"]},sourceBlockIds:(request.script.scenes||[]).map((_,index)=>`scene-${index+1}`)})};}
export async function POST(request:Request){let body:DirectorRequest;try{body=await request.json() as DirectorRequest;}catch{return Response.json({error:"Director输入不是有效JSON"},{status:400});}if(!body?.script||!body.context?.product)return Response.json({error:"缺少结构化Script或Director Context"},{status:400});const provider=body.settings?.provider||"deepseek";const target=targetDuration(body.context.targetDuration);let output:ReturnType<typeof fallbackDirector>|null=null,responseTimeMs:number|null=null,errorType:ProviderErrorType|null=null;
 try{for(let attempt=0;attempt<2;attempt++){const messages=prompt(body,attempt===1);const response=await callProvider({provider,messages:[{role:"system",content:messages.system},{role:"user",content:messages.user}],temperature:attempt?0.4:.62,maxTokens:7500,timeoutMs:55000});responseTimeMs=(responseTimeMs||0)+response.responseTimeMs;let parsed:ReturnType<typeof fallbackDirector>;try{parsed=JSON.parse(response.content) as ReturnType<typeof fallbackDirector>;}catch{if(!attempt)continue;throw new ProviderCallError("json_parse_error","Director JSON无效");}const normalized={...parsed,shots:rebalanceShots(parsed.shots||[],target)};const validation=validateDirector(normalized,body),facts=directorFactViolations(normalized,body);if(validation.length||facts.length){if(!attempt)continue;throw new ProviderCallError(facts.length?"fact_validation_error":"schema_validation_error",[...validation,...facts].join("；"));}output=normalized;break;}if(!output)throw new ProviderCallError("schema_validation_error","Director结构修复失败");}catch(error){errorType=safeError(error);output=fallbackDirector(body);}
 const planned=Number(output.shots.reduce((sum,shot)=>sum+shot.duration,0).toFixed(1));const knowledge=directorKnowledge(body);const metadata:DirectorResult["metadata"]={providerRequested:provider,providerUsed:errorType?"local":provider,aiGenerated:!errorType,fallbackUsed:Boolean(errorType),providerErrorType:errorType,responseTimeMs,targetDuration:target,plannedDuration:planned,durationDelta:Number((planned-target).toFixed(1)),durationRebalanced:true,shotCount:output.shots.length,sourceType:body.context.sourceType,productKnowledgeUsed:knowledge.metadata.productKnowledgeUsed,factGuardPassed:directorFactViolations(output,body).length===0};return Response.json({...output,metadata} satisfies DirectorResult);}
