import {callProvider,DEFAULT_PROVIDER,ProviderCallError} from "../../provider-router";
import {checkContextIntegrity,directorContextId,directorFactViolations,directorKnowledge,fallbackDirector,rebalanceShots,targetDuration,validateDirector,type DirectorRequest,type DirectorResult,type DirectorShot} from "../../director-core";
import {renderKnowledgeContext} from "../../knowledge-context";
import {validateScriptLanguage} from "../../language-guard";
import {evaluateShotIntelligenceBatch} from "../../director-intelligence";
import type {ProviderErrorType} from "../../provider-types";

export const maxDuration=120;

type DirectorAction="generate"|"regenerate-shot"|"suggest-shot"|"evaluate-shots";
type ShotActionRequest=DirectorRequest&{action:"regenerate-shot"|"suggest-shot";contextId:string;currentShot?:DirectorShot;previousShot?:DirectorShot;nextShot?:DirectorShot;directorPlan:DirectorResult["directorPlan"];sourceBlock?:{id:string;stage:string;text:string;visual?:string};preset?:string;instruction?:string};
type IntelligenceActionRequest=DirectorRequest&{action:"evaluate-shots";contextId:string;shots:DirectorShot[];directorPlan:DirectorResult["directorPlan"];force?:boolean};
type Payload=DirectorRequest&{action?:DirectorAction;contextId?:string;shots?:DirectorShot[];directorPlan?:DirectorResult["directorPlan"];force?:boolean};
const safeError=(error:unknown):ProviderErrorType=>error instanceof ProviderCallError?error.category:"schema_validation_error";
const shotShape={shotId:"unchanged",order:1,startTime:0,endTime:3,duration:3,sourceBlockId:"scene-1",stage:"PROOF",purpose:"Demonstration / Verification",shotType:"Proof Shot",framing:"Product Macro",cameraAngle:"45 Degree",cameraMovement:"Static",visualDescription:"string",subject:"string",productAction:"string",talentAction:"string",props:["string"],environment:"string",dialogue:"string or empty",voiceover:"string or empty",onScreenText:"string or empty",proofRequirement:"string or empty",transition:"Hard Cut",editingNotes:"string",audioSfx:"string",continuityNotes:"string",priority:"Critical | High | Normal"};
const outputShape={directorPlan:{recommendationType:"Director Recommendation",creativeIntent:"string",visualStyle:"string",hookExecution:"string",pacingStrategy:"string",proofStrategy:"string",productRevealStrategy:"string",ctaExecution:"string",shootingComplexity:"Simple | Standard | Advanced",requiredTalent:["string"],requiredProps:["string"],requiredLocations:["string"]},shots:[shotShape]};
function safeGenerationContext(request:DirectorRequest){const {referenceScript:_,replication,...current}=request.context;void _;return{...current,replication:replication?{sourceMechanism:replication.sourceMechanism||"",sellingPointMapping:replication.sellingPointMapping||"",proofMapping:replication.proofMapping||"",creativeAngle:request.context.creativeAngle}:undefined};}
function prompt(request:DirectorRequest,repair=false){const knowledge=directorKnowledge(request);return{system:`你是TikTok电商短视频导演。输出是 Director Recommendation，不是对原视频视觉的观察。CURRENT STRUCTURED SCRIPT 是台词、动作和Shot Content的唯一正文来源；CURRENT PRODUCT KNOWLEDGE 是产品事实的唯一来源。Replication Context只说明机制与映射，禁止复制其产品、道具、台词或场景。把当前结构化脚本转换成可直接拍摄的导演总纲和Shot List。一个Block可拆多镜，短Block可合并，但每个Shot必须用sourceBlockId追踪。前三秒按Hook Strategy设计真实视觉机制；Proof必须包含操作前、关键动作、操作后可见结果。Dialogue、Voiceover、On-screen Text按创作模式分工，不能复制三份。镜头自然可执行，避免无意义复杂运镜。总时长尽量等于${targetDuration(request.context.targetDuration)}秒。${repair?"上一版没有通过结构、事实或Context Grounding校验。本次只能使用当前Script和Knowledge中的实体，逐字段修复。":""}严格返回JSON，不要解释，不要Markdown。输出必须逐字段符合此结构：${JSON.stringify(outputShape)}\n${renderKnowledgeContext(knowledge)}`,user:JSON.stringify({currentStructuredScript:request.script,currentContext:safeGenerationContext(request),settings:request.settings,allowedEnums:{framing:["Extreme Close-Up","Close-Up","Medium Close-Up","Medium","Wide","Over-the-Shoulder","Top-Down","Product Macro"],cameraAngle:["Eye Level","High Angle","Low Angle","Top-Down","Side Angle","45 Degree"],cameraMovement:["Static","Push In","Pull Out","Pan","Tilt","Handheld","Tracking"]},sourceBlocks:(request.script.scenes||[]).map((scene,index)=>({id:`scene-${index+1}`,line:scene.line,visual:scene.visual}))})};}
function shotPrompt(request:ShotActionRequest){const knowledge=directorKnowledge(request);const mode=request.action==="suggest-shot"?"在前后镜头之间建议一个全新、可执行的镜头":"只重写当前镜头";return{system:`你是TikTok电商短视频导演。${mode}。不能重写整条Director Plan，不能改变相邻镜头。保持sourceBlockId、shotId、order、startTime、endTime和duration；输出语言为${request.context.language}，Dialogue / Voiceover / On-screen Text必须保持该语言。视觉描述与内部导演说明可用中文。锁定的产品事实和Proof逻辑不可扩写，禁止添加知识库不存在的认证、参数、价格或效果。请兼顾前后镜头连续性与手机可拍性。严格只返回单个Shot JSON，不要Markdown：${JSON.stringify(shotShape)}\n${renderKnowledgeContext(knowledge)}`,user:JSON.stringify({preset:request.preset||"更 TikTok 原生",instruction:request.instruction||"",currentShot:request.currentShot||null,previousShot:request.previousShot||null,nextShot:request.nextShot||null,directorPlan:request.directorPlan,sourceScriptBlock:request.sourceBlock||null,market:request.context.market,language:request.context.language,platform:request.context.platform,sellingPointPriority:request.context.sellingPoints})};}
function normalizeShot(candidate:DirectorShot,request:ShotActionRequest){const basis=request.currentShot||request.previousShot||request.nextShot;if(!basis)throw new ProviderCallError("missing_field","缺少镜头上下文");const duration=request.action==="suggest-shot"?Math.max(.5,Number(candidate.duration)||Math.min(2,basis.duration)):basis.duration;return{...candidate,shotId:basis.shotId,sourceBlockId:request.sourceBlock?.id||basis.sourceBlockId,order:basis.order,startTime:basis.startTime,endTime:Number((basis.startTime+duration).toFixed(1)),duration};}
function validateShot(candidate:DirectorShot,request:ShotActionRequest){const shell={directorPlan:request.directorPlan,shots:[candidate]};const structure=validateDirector(shell,request).filter(x=>x!=="director_structure");const facts=directorFactViolations(shell,request);const language=validateScriptLanguage({scenes:[{line:candidate.dialogue},{line:candidate.voiceover},{line:candidate.onScreenText}]},request.context.language);const context=checkContextIntegrity(shell,request,request.contextId).issues;return[...structure,...facts,...language.reasons,...context.map(issue=>`context:${issue.code}:${issue.value||""}`)];}
async function handleShotAction(body:ShotActionRequest){if(!body.contextId||body.contextId!==directorContextId(body))return Response.json({error:"导演上下文已变化，请为当前脚本生成新的导演方案。",contextIntegrity:{status:"Needs Attention",issues:[{code:"context_identity",message:"镜头生成上下文与当前脚本不一致"}]}},{status:409});const provider=body.settings?.provider||DEFAULT_PROVIDER;let candidate:DirectorShot|null=null,errorType:ProviderErrorType|null=null,responseTimeMs:number|null=null;try{for(let attempt=0;attempt<2;attempt++){const messages=shotPrompt({...body,instruction:`${body.instruction||""}${attempt?"；上一版未通过字段、语言、事实或上下文校验，只修复问题，不新增事实。":""}`});const response=await callProvider({provider,messages:[{role:"system",content:messages.system},{role:"user",content:messages.user}],temperature:attempt?.35:.58,maxTokens:2600,timeoutMs:45000});responseTimeMs=(responseTimeMs||0)+response.responseTimeMs;let parsed:DirectorShot;try{parsed=JSON.parse(response.content) as DirectorShot;}catch{if(!attempt)continue;throw new ProviderCallError("json_parse_error","镜头 JSON 无效");}const normalized=normalizeShot(parsed,body);const errors=validateShot(normalized,body);if(errors.length){if(!attempt)continue;throw new ProviderCallError(errors.some(x=>/使用了未提供|禁用表达|fact/i.test(x))?"fact_validation_error":errors.some(x=>/language/.test(x))?"language_validation_error":"schema_validation_error",errors.join("；"));}candidate=normalized;break;}if(!candidate)throw new ProviderCallError("schema_validation_error","镜头修复失败");}catch(error){errorType=safeError(error);if(errorType==="fact_validation_error")return Response.json({error:"该镜头包含未经产品资料支持的信息，已拒绝。",factGuardPassed:false},{status:422});const basis=body.currentShot||body.previousShot||body.nextShot;if(!basis)return Response.json({error:"缺少镜头上下文"},{status:400});candidate={...basis,visualDescription:`${basis.visualDescription}（安全回退：保留原证明逻辑，建议用更近景别和清晰动作节点拍摄。）`,editingNotes:`${basis.editingNotes}；在关键变化处做轻微推进，保持手机可拍。`};}
 return Response.json({candidate,metadata:{providerRequested:provider,providerUsed:errorType?"local":provider,aiGenerated:!errorType,fallbackUsed:Boolean(errorType),providerErrorType:errorType,responseTimeMs,factGuardPassed:directorFactViolations({directorPlan:body.directorPlan,shots:[candidate]},body).length===0,language:body.context.language}});
}
async function handleIntelligenceAction(body:IntelligenceActionRequest){
 console.log(JSON.stringify({scope:"director_intelligence",event:"intelligence_request_started",shotCount:Array.isArray(body.shots)?body.shots.length:0,force:Boolean(body.force),provider:body.settings?.provider||DEFAULT_PROVIDER}));
 if(!body.contextId||body.contextId!==directorContextId(body))return Response.json({error:"导演上下文已变化，请重新评估当前导演方案。",category:"context_identity",contextIntegrity:{status:"Needs Attention",issues:[{code:"context_identity",message:"评分上下文与当前脚本不一致"}]}},{status:409});
 if(!body.directorPlan||!Array.isArray(body.shots)||!body.shots.length)return Response.json({error:"缺少 Director Plan 或待评估镜头",category:"missing_field"},{status:400});
 const shell={directorPlan:body.directorPlan,shots:body.shots},structure=validateDirector(shell,body).filter(issue=>issue!=="director_structure"),facts=directorFactViolations(shell,body),contextIssues=checkContextIntegrity(shell,body,body.contextId).issues;
 if(structure.length||facts.length||contextIssues.length)return Response.json({error:"Shot Intelligence 输入未通过结构或事实校验",category:facts.length?"fact_validation_error":"schema_validation_error",diagnostics:[...structure,...facts,...contextIssues.map(issue=>`context:${issue.code}:${issue.value||""}`)]},{status:422});
 const provider=body.settings?.provider||DEFAULT_PROVIDER;
 try{return Response.json(await evaluateShotIntelligenceBatch({request:body,directorPlan:body.directorPlan,shots:body.shots,contextId:body.contextId,provider,force:body.force}));}
 catch(error){const category=safeError(error),status=category==="missing_field"?503:category==="rate_limit"?429:category==="fact_validation_error"||category==="schema_validation_error"||category==="structured_fields_missing"?422:502;return Response.json({error:category==="timeout"?"Shot Intelligence 评分超时，请重试。":category==="fact_validation_error"?"优化建议包含未经产品资料支持的信息，已拒绝。":"Shot Intelligence 暂时不可用，请重试。",category},{status});}
}
export async function POST(request:Request){let body:Payload;try{body=await request.json() as Payload;}catch{return Response.json({error:"Director输入不是有效JSON"},{status:400});}if(!body?.script||!body.context?.product)return Response.json({error:"缺少结构化Script或Director Context"},{status:400});if(body.action==="regenerate-shot"||body.action==="suggest-shot")return handleShotAction(body as ShotActionRequest);
 if(body.action==="evaluate-shots")return handleIntelligenceAction(body as IntelligenceActionRequest);
 const provider=body.settings?.provider||DEFAULT_PROVIDER;const target=targetDuration(body.context.targetDuration),contextId=directorContextId(body);let output:ReturnType<typeof fallbackDirector>|null=null,responseTimeMs:number|null=null,errorType:ProviderErrorType|null=null;
 try{for(let attempt=0;attempt<2;attempt++){const messages=prompt(body,attempt===1);const response=await callProvider({provider,messages:[{role:"system",content:messages.system},{role:"user",content:messages.user}],temperature:attempt?.4:.62,maxTokens:7500,timeoutMs:55000});responseTimeMs=(responseTimeMs||0)+response.responseTimeMs;let parsed:ReturnType<typeof fallbackDirector>;try{parsed=JSON.parse(response.content) as ReturnType<typeof fallbackDirector>;}catch{if(!attempt)continue;throw new ProviderCallError("json_parse_error","Director JSON无效");}const normalized={...parsed,shots:rebalanceShots(parsed.shots||[],target)};const validation=validateDirector(normalized,body),facts=directorFactViolations(normalized,body),contextIssues=checkContextIntegrity(normalized,body,contextId).issues;if(validation.length||facts.length||contextIssues.length){if(!attempt)continue;throw new ProviderCallError(facts.length?"fact_validation_error":"schema_validation_error",[...validation,...facts,...contextIssues.map(issue=>`context:${issue.code}:${issue.value||""}`)].join("；"));}output=normalized;break;}if(!output)throw new ProviderCallError("schema_validation_error","Director结构修复失败");}catch(error){errorType=safeError(error);output=fallbackDirector(body);}
 const planned=Number(output.shots.reduce((sum,shot)=>sum+shot.duration,0).toFixed(1));const knowledge=directorKnowledge(body),contextIntegrity=checkContextIntegrity(output,body,contextId);const metadata:DirectorResult["metadata"]={providerRequested:provider,providerUsed:errorType?"local":provider,aiGenerated:!errorType,fallbackUsed:Boolean(errorType),providerErrorType:errorType,responseTimeMs,targetDuration:target,plannedDuration:planned,durationDelta:Number((planned-target).toFixed(1)),durationRebalanced:true,shotCount:output.shots.length,sourceType:body.context.sourceType,productKnowledgeUsed:knowledge.metadata.productKnowledgeUsed,factGuardPassed:directorFactViolations(output,body).length===0,contextId,contextIntegrity};return Response.json({...output,metadata} satisfies DirectorResult);}
